Repository gravitee-io/gravitee-api-management, pull requests merged in 2023-07, with the labels that each got.

#4460 fix: define useFixedInterval instead of interval to be compliant with…
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/AbstractElasticsearchQueryCommand.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/AbstractElasticsearchQueryCommand.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/analyticsRequest.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/dateHistogram.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/healthcheck/avg-availability.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/healthcheck/avg-date-histogram.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/healthcheck/avg-response-time.ftl
Labels: apply-on-master

#4468 Bump `gravitee-policy-dynamic-routing` to `1.11.3`
  gravitee-apim-distribution/pom.xml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#4470 fix: throw the right error when accessing api or application
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_GetUserMemberTest.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#4489 Fix test managed endpoint rule
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/test/java/io/gravitee/gateway/services/healthcheck/http/AbstractManagedEndpointRuleHandlerTest.java
Labels: apply-on-3-20-x, apply-on-master

#4495 Fix the readonly page condition
  gravitee-apim-console-webui/src/management/configuration/portal/portal.component.ts
  gravitee-apim-console-webui/src/management/configuration/portal/portal.html
Labels: apply-on-3-20-x

#4487 chore: add logs to be able to investigate issues while an exception o…
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/core/processor/chain/AbstractStreamableProcessorChain.java
Labels: apply-on-master

#4515 fix(portal): readonly component for metadata
  gravitee-apim-portal-webui/src/app/pages/application/application-metadata/application-metadata.component.spec.ts
  gravitee-apim-portal-webui/src/app/pages/application/application-metadata/application-metadata.component.ts
Labels: apply-on-3-19-x, apply-on-3-18-x, apply-on-master

#4548 feat: update helm elasticsearch
  helm/Chart.yaml
  helm/requirements.lock
  helm/requirements.yaml
  helm/values.yaml
Labels: apply-on-3-20-x

#4553 Automatically scroll to top of content component on API view
  gravitee-apim-console-webui/src/management/api/apiAdmin.html
Labels: ready_to_test

#4575 fix: remove token from internal attributes in V3
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/security/PlanBasedAuthenticationHandler.java
Labels: apply-on-4-0-x

#4594 Console - Clean Gateways page
  gravitee-apim-console-webui/src/management/instances/instances.controller.ts
  gravitee-apim-console-webui/src/management/instances/instances.html
Labels: apply-on-master

#4578 fix: clean any security token if selection rule doesn't match
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/security/PlanBasedAuthenticationHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/jupiter/handlers/api/security/plan/SecurityPlan.java
Labels: apply-on-3-20-x

#4597 fix(console): change api permission resolution priority
  gravitee-apim-console-webui/src/management/api/apis.module.ts
Labels: apply-on-master

#4604 fix(e2e): use correct variable for bridge client
  gravitee-apim-e2e/docker/common/docker-compose-bridge.yml
Labels: apply-on-4-0-x

#4602 fix: verify custom api key setting for apikey renew endpoint
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiSubscriptionsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiSubscriptionsResource_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiSubscriptionsResource_RenewApiKeysTest.java
Labels: apply-on-master

#4617 test: removes obsolete test cases concerning Show-History toggle switch
  gravitee-apim-e2e/ui-test/integration/apim/ui/gateways/ui-gateway-information.spec.ts
Labels: apply-on-4-0-x

#4627 ci: select a dedicated folder when uploading a pre-release version [s…
  .circleci/config.yml
Labels: apply-on-master

#4632 Do not create `-ee` tag any more
  .circleci/config.yml
Labels: apply-on-master

#4636 Apim 2192
  gravitee-apim-distribution/pom.xml
Labels: apply-on-4-0-x, apply-on-master

#4621 fix: increase title size in the notification template
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v3_19_19/schema.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master

#4623 Fix docker default run e2e
  gravitee-apim-console-webui/docker/Dockerfile
  gravitee-apim-console-webui/docker/Dockerfile-from-download
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/Dockerfile-from-download
Labels: apply-on-master, ready_to_test

#4641 chore: move repository bridge to distribution -dev
  gravitee-apim-distribution/pom.xml
Labels: apply-on-master

#4624 Display doc page with invalid template as it instead of blank
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/InvalidTemplateException.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/NotificationTemplateServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/NotificationTemplateServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/PageService_TemplateTest.java
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master, ready_to_test

#4665 Add missing websocket config in gravitee.yml of the gateway
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master

#4612 fix: use dedicated validation resource for context-path updates
  gravitee-apim-console-webui/src/management/api/portal/details/api-portal-details-duplicate-dialog/api-portal-details-duplicate-dialog.component.ts
  gravitee-apim-console-webui/src/management/api/proxy/entrypoints/api-proxy-entrypoints.component.spec.ts
  gravitee-apim-console-webui/src/management/api/proxy/entrypoints/context-path/api-proxy-entrypoints-context-path.component.ts
  gravitee-apim-console-webui/src/services-ngx/api.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/api.service.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/param/VerifyApiParam.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiResourceTest.java
Labels: apply-on-4-0-x, apply-on-master

#4674 chore: bump xslt policy version
  pom.xml
Labels: apply-on-master

#4676 chore(deps): bump solace endpoint plugin
  pom.xml
Labels: apply-on-master

#4635 fix(console): resolve org menu display when user come from page with …
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/src/organization/configuration/navigation/org-navigation.component.html
Labels: apply-on-4-0-x

#4452 Archi 253 plugin override
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/README.md
  helm/templates/_helpers.tpl
  helm/templates/api/api-deployment.yaml
  helm/templates/api/api-upgrader-job.yaml
  helm/templates/gateway/gateway-deployment.yaml
  helm/values.yaml
  pom.xml
Labels: apply-on-master, ready_to_test

#4695 Update router state for subscription edition
  gravitee-apim-console-webui/src/management/api/analytics/logs/log.html
  gravitee-apim-console-webui/src/management/api/apis.route.ts
  gravitee-apim-console-webui/src/management/platform/logs/platform-log.html
  gravitee-apim-console-webui/src/management/tasks/tasks.component.spec.ts
  gravitee-apim-console-webui/src/management/tasks/tasks.component.ts
Labels: apply-on-master

#4700 remove 'document' step mention in api creation workflow
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/step-2-entrypoints/step-2-entrypoints-0-architecture.component.ts
Labels: apply-on-master

#4699 Apim 2254 bug change subscription end date
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/components/dialogs/creation/api-portal-subscription-creation-dialog.component.ts
  gravitee-apim-portal-webui/src/app/pages/api/api-subscribe/api-subscribe.component.ts
  gravitee-apim-portal-webui/src/app/pages/application/application-creation/application-creation.component.ts
Labels: apply-on-master

#4701 refactor(console): prepare API menu migration to angular for V1&V2 APIs
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/ApiMenuService.ts
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/MenuGroupItem.ts
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-navigation-tabs/api-ng-navigation-tabs.component.ts
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-navigation.component.ts
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-v1-v2-menu.service.ts
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-v4-menu.service.ts
Labels: apply-on-master, ready_to_test

#4704 Allow import v4 api
  gravitee-apim-console-webui/src/management/api/creation/api-creation-get-started.component.html
  gravitee-apim-console-webui/src/services-ngx/api-v2.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/api-v2.service.ts
  gravitee-apim-console-webui/src/shared/components/gio-api-import-dialog/gio-api-import-dialog.component.html
  gravitee-apim-console-webui/src/shared/components/gio-api-import-dialog/gio-api-import-dialog.component.scss
  gravitee-apim-console-webui/src/shared/components/gio-api-import-dialog/gio-api-import-dialog.component.ts
Labels: apply-on-master

#4718 chore(deps): bump dependencies
  pom.xml
Labels: apply-on-master

#4712 Use CircleCI parallel runs for integration tests
  .circleci/config.yml
Labels: apply-on-master

#4729 fix: allow to update application that has push plans subscriptions
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_UpdateTest.java
Labels: apply-on-master

#4724 fix: use applicationType from db instead of optional metadata
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_UpdateTest.java
Labels: apply-on-3-19-x, apply-on-4-0-x, apply-on-master

#4680 fix(portal): resolve markdown links
  gravitee-apim-portal-webui/src/app/components/gv-documentation/gv-documentation.component.html
  gravitee-apim-portal-webui/src/app/components/gv-documentation/gv-documentation.component.spec.ts
  gravitee-apim-portal-webui/src/app/components/gv-documentation/gv-documentation.component.ts
  gravitee-apim-portal-webui/src/app/components/gv-page-markdown/gv-page-markdown.component.spec.ts
  gravitee-apim-portal-webui/src/app/components/gv-page-markdown/gv-page-markdown.component.ts
  gravitee-apim-portal-webui/src/app/components/gv-page/gv-page.component.ts
  gravitee-apim-portal-webui/src/app/pages/api/api-documentation/api-documentation.component.html
  gravitee-apim-portal-webui/src/app/pages/api/api-documentation/api-documentation.component.ts
  gravitee-apim-portal-webui/src/app/pages/api/api-general/api-general.component.html
  gravitee-apim-portal-webui/src/app/pages/api/api-general/api-general.component.ts
  gravitee-apim-portal-webui/src/app/pages/homepage/homepage.component.html
  gravitee-apim-portal-webui/src/app/pages/homepage/homepage.component.ts
  gravitee-apim-portal-webui/src/app/pages/single-page/single-page.component.html
  gravitee-apim-portal-webui/src/app/pages/single-page/single-page.component.ts
  gravitee-apim-portal-webui/src/app/services/scroll.service.ts
Labels: apply-on-3-19-x, apply-on-4-0-x, apply-on-master

#4723 fix: hide upgrade banner on v2 apis
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/step-5-summary/step-5-summary.component.html
  gravitee-apim-console-webui/src/management/api/portal/details/api-portal-details-danger-zone/api-portal-details-danger-zone.component.spec.ts
  gravitee-apim-console-webui/src/management/api/portal/details/api-portal-details-danger-zone/api-portal-details-danger-zone.component.ts
  gravitee-apim-console-webui/src/management/api/portal/details/api-portal-details.component.spec.ts
Labels: apply-on-master

#4752 chore(deps): bump plugins to use official version
  pom.xml
Labels: apply-on-master

#4746 fix: allow to create flows for paths without policy during import
  gravitee-apim-console-webui/src/shared/components/gio-api-import-dialog/gio-api-import-dialog.component.html
  gravitee-apim-console-webui/src/shared/components/gio-api-import-dialog/gio-api-import-dialog.component.spec.ts
  gravitee-apim-console-webui/src/shared/components/gio-api-import-dialog/gio-api-import-dialog.component.ts
Labels: apply-on-master

#4742 feat(console): delete tooltip from api list
  gravitee-apim-console-webui/src/management/api/list/api-list.component.html
Labels: apply-on-master

#4763 chore(deps): bump plugins version
  pom.xml
Labels: apply-on-master

#4765 feat: update default portal theme
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/themes/definition.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/themes/favicon.png
Labels: apply-on-master

#4722 perf: refactor portal api page resource
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPageResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResourceNotAuthenticatedTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPageResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/AccessControlService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/PageService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AccessControlServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/SearchIndexUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/ApiAuthorizationService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiAuthorizationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/AccessControlServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/SearchIndexUpgraderTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiAuthorizationServiceImplTest.java
Labels: apply-on-3-19-x

#4775 chore(deps): upgrade rabbitmq endpoint to 1.0.1
  pom.xml
Labels: apply-on-master

#4771 test: add delay on message post in http post integration test
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/messages/httppost/HttpPostEntrypointRabbitMQEndpointIntegrationTest.java
Labels: apply-on-master

#4782 chore: bump hazelcast to 5.0.5
  pom.xml
Labels: apply-on-3-20-x

#4781 fix: ignore rejected subscription in api authorization service query
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AccessControlServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiAuthorizationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/AccessControlServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiAuthorizationServiceImplTest.java
Labels: apply-on-3-19-x

#4780 Improve sanitization of log values when exporting as CSV
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/CsvUtils.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/LogsServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/CsvUtilsTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/LogsServiceTest.java
Labels: apply-on-master

#4609 2174: V4 API command handler implemented for Cockpit command
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/V4ApiCommandHandler.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/V4ApiServiceCockpit.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/V4ApiServiceCockpitImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/V4ApiCommandHandlerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/services/V4ApiServiceCockpitTest.java
  pom.xml
Labels: apply-on-master

#4799 chore: bump policies version
  gravitee-apim-distribution/pom.xml
  pom.xml
Labels: apply-on-master

#4802 chore: Plan's general conditions typo
  gravitee-apim-console-webui/src/management/api/component/plan/1-general-step/plan-edit-general-step.component.html
Labels: apply-on-master

#4801 fix: Rewrite log for API v4 support
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/verticle/EndpointDiscoveryVerticle.java
Labels: apply-on-master

#4803 fix: Remove useless summary step info from API v4 creation wizard
  gravitee-apim-console-webui/src/management/api/creation-v4/api-creation-v4.component.spec.ts
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/step-5-summary/step-5-summary.component.html
Labels: apply-on-master

#4811 chore: bump kafka endpoint
  pom.xml
Labels: apply-on-master

#4816 Console - fix : Not possible to access alerts in the UI
  gravitee-apim-console-webui/src/components/alerts/dashboard/alerts-dashboard.component.ts
  gravitee-apim-console-webui/src/management/api/notifications/apis.notifications.settings.route.ts
Labels: apply-on-master

#4824 Move some plugins in the default bundle
  gravitee-apim-distribution/pom.xml
Labels: apply-on-master

#4826 chore: update cockpit-connectors version
  pom.xml
Labels: apply-on-master

#4846 chore(deps): bump json-xml policy to 3.0.2
  pom.xml
Labels: apply-on-master

#4842 chore: log message when error occurs during request/message processing
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/processor/error/AbstractFailureProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/appender/MemoryAppender.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/processor/error/SimpleFailureProcessorTest.java
  pom.xml
Labels: apply-on-4-0-x

#4850 feat(helm): define gateway http max sizes
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-4-0-x

#4849 fix(rest-api): map null to empty string for flow step serialization
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/FlowDeserializer.java
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/StepDeserializer.java
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/FlowSerializer.java
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/StepSerializer.java
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/test/java/io/gravitee/definition/jackson/api/FlowSerializerTest.java
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/test/resources/io/gravitee/definition/jackson/flow-missingfields.json
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/test/resources/io/gravitee/definition/jackson/flow-nullvalue.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/jackson/ser/FlowStepSerializer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/converter/FlowConverterTest.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#4855 feat(helm): add snyk scan in CI
  .circleci/config.yml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#4867 fix: prevent having logout path in redirectUri
  gravitee-apim-portal-webui/src/app/services/auth.service.ts
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master
