Repository gravitee-io/gravitee-api-management, pull requests merged in 2023-03, with the labels that each got.

#3190 Fix best match flow selector
  gravitee-apim-gateway/gravitee-apim-gateway-flow/src/main/java/io/gravitee/gateway/jupiter/flow/BestMatchFlowSelector.java
  gravitee-apim-gateway/gravitee-apim-gateway-flow/src/test/java/io/gravitee/gateway/jupiter/flow/BestMatchFlowBaseTest.java
Labels: apply-on-3-20-x, apply-on-3-19-x

#3221 Filter by environment when searching APIs with SearchEngine - `3.19.x`
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/ApiDocumentSearcher.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/SearchEngineServiceTest.java
Labels: apply-on-3-20-x

#3226 Bump `@gravitee/ui-components` to `3.38.8`
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-3-19-x

#3236 fix(gateway): configure stream before handling connection
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/core/invoker/EndpointInvoker.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#3242 Use JSON schema with JS-YAML lib to convert YAML to JSON
  gravitee-apim-portal-webui/src/app/utils/yaml-parser.spec.ts
  gravitee-apim-portal-webui/src/app/utils/yaml-parser.ts
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#3250 fix: bump traffic shadowing version to 2.0.0
  gravitee-apim-distribution/pom.xml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#3258 Handle special characters in user/password of MongoDB uri
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/common/AbstractRepositoryConfiguration.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/java/io/gravitee/repository/mongodb/common/AbstractRepositoryConfigurationTest.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#3272 fix: escape uri components in log queries
  gravitee-apim-console-webui/src/services/api.service.ts
Labels: apply-on-3-20-x, apply-on-3-19-x

#3280 fix: log all timeouts when chaining calls
  gravitee-apim-gateway/gravitee-apim-gateway-http/src/main/java/io/gravitee/gateway/http/vertx/VertxHttpServerResponse.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#3295 Display list of API members in the transfer ownership screen
  gravitee-apim-console-webui/src/management/api/portal/userGroupAccess/transferOwnership/transferOwnership.controller.ts
Labels: apply-on-3-20-x, apply-on-3-19-x

#3305 fix: bump elastic reporter to 3.12.5
  gravitee-apim-distribution/pom.xml
Labels: apply-on-3-19-x

#3317 Update Changelog script to use Jira Release
  .circleci/config.yml
  release/ci-steps/doc-new-release-notes.mjs
  release/helpers/jira-helper.mjs
  release/helpers/version-helper.mjs
Labels: apply-on-3-20-x, apply-on-3-18-x, apply-on-master

#3329 fix(management): add etag to createApi http response
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/v4/api/ApisResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/v4/api/ApisResourceTest.java
Labels: apply-on-master

#3333 fix: add client response in logs with jupiter
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/jupiter/reactor/DefaultHttpRequestDispatcher.java
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/test/java/io/gravitee/gateway/jupiter/reactor/DefaultHttpRequestDispatcherTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-integration/src/test/java/io/gravitee/gateway/tests/http/logging/LoggingIntegrationTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-integration/src/test/java/io/gravitee/gateway/tests/http/logging/LoggingV3CompatibilityIntegrationTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-integration/src/test/java/io/gravitee/gateway/tests/http/logging/LoggingV3IntegrationTest.java
Labels: apply-on-3-19-x, apply-on-master, apply-on-3-21-x

#3361 Add an empty option when selecting the general condition of a plan
  gravitee-apim-console-webui/src/management/api/portal/plans/plan/plan-wizard-general.html
Labels: apply-on-3-20-x, apply-on-3-19-x

#3360 Update `connector-http` to `2.1.2`
  gravitee-apim-distribution/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/pom.xml
Labels: apply-on-3-20-x, apply-on-3-19-x

#3370 Bump `connector-http` to `3.0.0`
  gravitee-apim-distribution/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/pom.xml
Labels: apply-on-master

#3377 Properly select series labels in pie chart
  gravitee-apim-console-webui/src/components/widget/pie/widget-chart-pie.component.ts
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master, apply-on-3-21-x

#3384 fix: match documentation and implementation for attach media api
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPageMediaResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalPageMediaResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/JerseySpringTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiPageMediaResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/PortalPageMediaResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/PageService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master, apply-on-3-21-x

#3367 test: add gateway mode for gatewaytest annotation
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/AbstractGatewayTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/annotations/GatewayTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/configuration/GatewayMode.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/GatewayRunner.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/test/java/GatewayTestingExtensionTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/test/java/testcases/GatewayModeTestCase.java
Labels: apply-on-3-20-x, apply-on-master

#3414 ci: update ingress gateway deployment name
  .circleci/config.yml
Labels: apply-on-master

#3425 ci: fix ingress gateway deployment name
  .circleci/config.yml
Labels: apply-on-3-21-x

#3450 Exclude Flow Ids from API Sync check
  gravitee-apim-console-webui/src/management/api/audit/history/apiHistory.controller.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-3-21-x

#3441 fix: Redis connection URI not secured when activating SSL
  gravitee-apim-repository/gravitee-apim-repository-redis/src/main/java/io/gravitee/repository/redis/common/RedisConnectionFactory.java
  gravitee-apim-repository/gravitee-apim-repository-redis/src/main/java/io/gravitee/repository/redis/vertx/RedisClient.java
  gravitee-apim-repository/gravitee-apim-repository-redis/src/test/java/io/gravitee/repository/redis/common/RedisConnectionFactoryTest.java
Labels: apply-on-3-21-x

#3461 fix: remove use of `ApiRepository.findAll`
  .run/Rest API - JDBC.run.xml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiRepository.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/OrphanCategoryUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/PlansDataFixUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/PlansFlowsDefinitionUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/SearchIndexUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/OrphanCategoryUpgraderTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/PlansDataFixUpgraderTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/PlansFlowsDefinitionUpgraderTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/SearchIndexUpgraderTest.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master, apply-on-3-21-x
