Repository gravitee-io/gravitee-api-management, pull requests merged in 2023-11, with the labels that each got.

#5715 fix: force user role when importing V2 api with wrong user role
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorService_CreateWithDefinitionTest.java
Labels: ready_to_test

#5735 fix: bump http-get and websocket entrypoint versions
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#5727 fix(helm): remove nonexistant existingClaim attribute
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-4-1-x

#5729 Console - notification details - webhook bug fix
  gravitee-apim-console-webui/src/components/notifications/notifications-list/notification-details/notification-settings-details.component.html
  gravitee-apim-console-webui/src/components/notifications/notifications-list/notification-details/notification-settings-details.component.scss
  gravitee-apim-console-webui/src/components/notifications/notifications-list/notification-details/notification-settings-details.component.spec.ts
  gravitee-apim-console-webui/src/components/notifications/notifications-list/notification-details/notification-settings-details.component.ts
  gravitee-apim-console-webui/src/components/notifications/notifications-list/notification-settings-list.module.ts
Labels: ready_to_test

#5718 fix(rest-api): keep dynamic property specification & body into string
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/mapper/ServiceMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/fixtures/ServiceFixture.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/mapper/ServiceMapperTest.java
Labels: apply-on-4-0-x, ready_to_test

#5742 Improve performances when querying AlertEvent related metrics
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/AlertEventRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcAlertEventRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoAlertEventRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/api/AlertEventMongoRepositoryCustom.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/api/AlertEventMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/create-index.js
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/AlertEventRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/alertevent-tests/alertEvents.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AlertServiceImpl.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5726 feat(helm): backport HTTP 2 configuration from gravitee.yml to helm values
  helm/Chart.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_http_test.yaml
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-4-1-x

#5743 proxy logs settings
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs-settings/runtime-logs-proxy-settings/api-runtime-logs-proxy-settings.component.html
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs-settings/runtime-logs-proxy-settings/api-runtime-logs-proxy-settings.component.scss
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs-settings/runtime-logs-proxy-settings/api-runtime-logs-proxy-settings.component.spec.ts
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs-settings/runtime-logs-proxy-settings/api-runtime-logs-proxy-settings.component.ts
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs-settings/runtime-logs-proxy-settings/api-runtime-logs-proxy-settings.harness.ts
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs-settings/runtime-logs-proxy-settings/api-runtime-logs-proxy-settings.module.ts
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs-settings/runtime-logs-proxy-settings/api-runtime-logs-proxy-settings.stories.ts
Labels: ready_to_test

#5767 3.20.x - bump gravitee-reporter-(elasticsearch|file|tcp) to fix espace issue
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/processor/error/SimpleFailureProcessorTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/reporter/FakeReporter.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/reporter/FakeReporter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/pom.xml
  pom.xml
Labels: ready_to_test

#5768 4.0.x - bump gravitee-reporter-(elasticsearch|file|tcp) to fix espace issue
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/pom.xml
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5772 feat: change default password policy
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/validator/RegexPasswordValidator.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/validator/RegexPasswordValidatorTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5792 fix: bump groovy policy
  pom.xml
Labels: apply-on-master, ready_to_test, apply-on-4-1-x

#5800 Bump gravitee-policy-generate-jwt to 1.7.1
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5779 fix(helm); replace default mongodb and elastic endpoint url
  helm/tests/gateway/configmap_es_reporter_test.yaml
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-4-1-x

#5805 fix: ignore empty argument
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-bootstrap/src/main/java/io/gravitee/rest/api/standalone/boostrap/Bootstrap.java
Labels: apply-on-master, apply-on-4-1-x

#5812 ci: fix openjdk image version to 17.0.8 [skip ci]
  .circleci/ci/src/config.ts
  .circleci/ci/src/pipelines/tests/resources/bridge-compatibility-tests/bridge-compatibility-tests.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/nexus-staging/nexus-staging-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
  .circleci/ci/src/pipelines/tests/resources/repositories-tests/repositories-tests.yml
Labels: apply-on-master, apply-on-4-1-x

#5786 feat(helm): improve metrics configuration in helm charts
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/api/configmap_metrics_test.yaml
  helm/tests/gateway/configmap_metrics_test.yaml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-4-1-x

#5804 chore: bump gravitee node
  pom.xml
Labels: apply-on-4-1-x

#5817 fix: we should allow verification for update permission
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5826 Apim 3246 edit markdown name and visibility
  gravitee-apim-console-webui/src/entities/management-api-v2/documentation/page.fixture.ts
  gravitee-apim-console-webui/src/management/api/apis.route.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/api-documentation-v4.module.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/api-documentation-v4-page-header/api-documentation-v4-page-header.component.html
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/api-documentation-v4-page-header/api-documentation-v4-page-header.component.scss
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/api-documentation-v4-page-header/api-documentation-v4-page-header.component.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/api-documentation-v4-visibility/api-documentation-v4-visibility.harness.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-edit-page/api-documentation-v4-edit-page.component.html
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-edit-page/api-documentation-v4-edit-page.component.scss
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-edit-page/api-documentation-v4-edit-page.component.spec.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-edit-page/api-documentation-v4-edit-page.component.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-edit-page/api-documentation-v4-edit-page.harness.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-new-page/api-documentation-v4-new-page.component.html
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-new-page/api-documentation-v4-new-page.component.scss
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-new-page/api-documentation-v4-new-page.component.spec.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-new-page/api-documentation-v4-new-page.component.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-new-page/api-documentation-v4-new-page.harness.ts
Labels: ready_to_test

#5835 Bump policy-transformheaders
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5838 fix: make the history page work with lots of events
  gravitee-apim-console-webui/src/management/api/audit/apis.audit.route.ts
  gravitee-apim-console-webui/src/management/api/audit/history/apiHistory.controller.ts
  gravitee-apim-console-webui/src/management/api/audit/history/apiHistory.html
  gravitee-apim-console-webui/src/services/api.service.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiEventsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/param/EventSearchParam.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/EventService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EventServiceImpl.java
Labels: apply-on-4-0-x, ready_to_test

#5765 Console - application general migration - first part
  gravitee-apim-console-webui/src/entities/application/application.ts
  gravitee-apim-console-webui/src/management/api/general/subscriptions/list/api-general-subscription-list.component.spec.ts
  gravitee-apim-console-webui/src/management/application/applications.route.ts
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general.component.html
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general.component.scss
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general.component.ts
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general.module.ts
  gravitee-apim-console-webui/src/management/application/environment-application.module.ts
  gravitee-apim-console-webui/src/management/management.module.ajs.ts
  gravitee-apim-console-webui/src/services-ngx/application.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/application.service.ts
Labels: ready_to_test

#5862 Fix regex used to check if a branch is support branch or master
  .circleci/ci/src/utils/branch.ts
  .circleci/ci/src/utils/tests/branch.spec.ts
Labels: apply-on-4-0-x, apply-on-4-1-x

#5848 Console - application general migration - second part
  gravitee-apim-console-webui/src/entities/application/application.ts
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general.component.html
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general.component.scss
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general.component.ts
Labels: ready_to_test

#5855 Use current year in the "All rights reserved" mention on Portal
  gravitee-apim-portal-webui/src/app/app.component.html
  gravitee-apim-portal-webui/src/app/app.component.ts
  gravitee-apim-portal-webui/src/assets/i18n/cs.json
  gravitee-apim-portal-webui/src/assets/i18n/en.json
  gravitee-apim-portal-webui/src/assets/i18n/fr.json
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5880 fix(console): make history screen rework
  gravitee-apim-console-webui/src/management/api/audit/history/apiHistory.controller.ajs.ts
Labels: apply-on-master

#5904 feat: allow to use responseTime in HC assertion
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5924 fix(rest-api): add missing setApiKeyMode for console rest-api
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiSubscriptionsResource.java
Labels: apply-on-4-0-x, apply-on-4-1-x

#5911 fix(e2e): check apikey mode nullity
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
Labels: apply-on-4-0-x

#5943 feat: add requestTimeout and requestTimeoutGraceDelay in helm charts
  helm/CHANGELOG.md
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_http_test.yaml
  helm/values.yaml
Labels: apply-on-master, apply-on-4-1-x

#5939 feat(console): move add new page button in api documentation
  gravitee-apim-console-webui/src/management/api/documentation-v4/api-documentation-v4.component.html
  gravitee-apim-console-webui/src/management/api/documentation-v4/api-documentation-v4.component.spec.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-list-navigation-header/api-documentation-v4-list-navigation-header.component.html
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-list-navigation-header/api-documentation-v4-list-navigation-header.component.scss
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-list-navigation-header/api-documentation-v4-list-navigation-header.component.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-list-navigation-header/api-documentation-v4-list-navigation-header.harness.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-pages-list/api-documentation-v4-pages-list.component.html
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-pages-list/api-documentation-v4-pages-list.component.scss
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-pages-list/api-documentation-v4-pages-list.component.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/documentation-pages-list/api-documentation-v4-pages-list.harness.ts
Labels: ready_to_test

#5941 fix: ensure that groups of an API is a mutable set
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIConverter.java
Labels: apply-on-master, apply-on-4-1-x

#5949 fix(console): re add angularJs component to select plan in application souscription page
  gravitee-apim-console-webui/src/management/application/components/api-plan/api-plan.component.ts
  gravitee-apim-console-webui/src/management/application/components/api-plan/api-plan.html
  gravitee-apim-console-webui/src/management/management.module.ajs.ts
Labels: ready_to_test

#5953 [4.0.x] Add server templating in OpenAPI file of mAPI v2
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
Labels: apply-on-4-1-x

#5963 ci: adapt release note generation to improvements
  release/ci-steps/generate-changelog.mjs
  release/helpers/changelog-helper.mjs
  release/helpers/jira-helper.mjs
Labels: apply-on-master, apply-on-4-1-x

#5968 doc: change mAPIv2 openapi server URL
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
Labels: apply-on-4-1-x

#5973 fix: bump oauth2 provider lib & resources
  pom.xml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5940 Bump dependencies
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5974 feat(console): remove reload true for smoother transitions in page list
  gravitee-apim-console-webui/src/management/api/documentation-v4/api-documentation-v4.component.spec.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/api-documentation-v4.component.ts
Labels: ready_to_test

#6011 Fix package bundle for pre-releases
  .circleci/ci/src/jobs/job-package-bundle.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-no-dry-run.yml
Labels: apply-on-master

#6021 fix: defer some @Value resolution and bean instantiation
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/endpoint/ApiManagementEndpoint.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/endpoint/ApisManagementEndpoint.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/spring/ApiHandlerConfiguration.java
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/vertx/VertxReactorConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-idp/gravitee-apim-rest-api-idp-core/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-idp/gravitee-apim-rest-api-idp-core/src/main/java/io/gravitee/rest/api/idp/core/authentication/impl/ReferenceSerializer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-idp/gravitee-apim-rest-api-idp-core/src/main/java/io/gravitee/rest/api/idp/core/spring/IdentityProviderPluginConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-security/src/main/java/io/gravitee/rest/api/security/csrf/CookieCsrfSignedTokenRepository.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AlertServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/HttpClientServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ReCaptchaServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/notifiers/impl/WebNotifierServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/AlertServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/AlertService_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ReCaptchaServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-container/src/main/java/io/gravitee/rest/api/standalone/jetty/JettyConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-container/src/main/java/io/gravitee/rest/api/standalone/jetty/JettyEmbeddedContainer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-container/src/main/java/io/gravitee/rest/api/standalone/jetty/JettyServerFactory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-container/src/main/java/io/gravitee/rest/api/standalone/spring/StandaloneConfiguration.java
  pom.xml
Labels: apply-on-master
