Repository gravitee-io/gravitee-api-management, pull requests merged in 2023-12, with the labels that each got.

#6063 fix(console): prevent virtual host overflow
  gravitee-apim-console-webui/src/management/api/component/gio-form-listeners/gio-form-listeners-virtual-host/gio-form-listeners-virtual-host.component.html
  gravitee-apim-console-webui/src/management/api/component/gio-form-listeners/gio-form-listeners-virtual-host/gio-form-listeners-virtual-host.component.scss
Labels: apply-on-4-2-x

#6070 fix: bump gateway-api
  pom.xml
Labels: apply-on-4-1-x

#6068 Fix proxiPath regex
  helm/templates/api/api-configmap.yaml
  helm/tests/api/configmap_test_installation.yaml
Labels: apply-on-master, ready_to_test

#6066 fix(helm): license deleted after helm upgrade
  helm/Chart.yaml
  helm/templates/common/licenses-secrets.yaml
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x

#6049 refactor: migrate debug api use case
  gravitee-apim-console-webui/src/services-ngx/debug-api.service.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/spring/InMemoryConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/mapper/DebugApiMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/provider/NotAllowedDomainExceptionMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/provider/NotFoundDomainExceptionMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/provider/TechnicalDomainExceptionMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/provider/ValidationDomainExceptionMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/AbstractResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GraviteeManagementApplication.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/mapper/DebugApiMapperTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiResourceDebugTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/spring/InMemoryConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/DebugApiEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/InstanceEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/PluginEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/ApiEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/spring/InMemoryConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/crud_service/ApiCrudService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/ApiPolicyValidatorDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/debug/exceptions/DebugApiInvalidDefinitionVersionException.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/debug/exceptions/DebugApiNoCompatibleInstanceException.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/debug/exceptions/DebugApiNoValidPlanException.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/debug/model/ApiDebugStatus.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/debug/use_case/DebugApiUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/event/crud_service/EventCrudService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/event/model/Event.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/gateway/model/Instance.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/gateway/query_service/InstanceQueryService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/policy/domain_service/PolicyValidationDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/EventAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/InstanceAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/api/ApiCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/event/EventCrudServiceLegacyWrapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/policy/PolicyValidationDomainServiceLegacyWrapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/query_service/gateway/InstanceQueryServiceLegacyWrapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/spring/CoreServiceSpringConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/spring/UsecaseSpringConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/EventService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/DebugApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EventServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/architecture/CoreRulesTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/fixtures/core/model/ApiFixtures.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/ApiCrudServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/EventCrudInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/InstanceQueryServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/PolicyValidationDomainServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/domain_service/ApiPolicyValidatorDomainServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/debug/use_case/DebugApiUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/adapter/ApiAdapterTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/adapter/EventAdapterTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/DebugApiServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/EventServiceTest.java
Labels: ready_to_test

#6091 feat(helm): update regex for portal base_href and console
  helm/templates/_helpers.tpl
  helm/templates/portal/portal-deployment.yaml
  helm/templates/ui/ui-deployment.yaml
  helm/tests/portal/deployment_test.yaml
  helm/tests/ui/deployment_test.yaml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x

#6067 feat: add a paged resource for API subscribers
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiSubscribersResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiSubscribersResourceTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6112 fix(helm): AE system mail notification without keystore
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-configmap.yaml
  helm/tests/api/configmap_email_test.yaml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6149 disable api promotion for multi-tenant installation
  gravitee-apim-console-webui/src/entities/consoleSettings.ts
  gravitee-apim-console-webui/src/management/api/general/details/api-general-info.component.spec.ts
  gravitee-apim-console-webui/src/management/api/general/details/api-general-info.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Management.java
Labels: apply-on-master

#6165 feat(helm): override standalone configuration
  helm/templates/api/api-configmap.yaml
  helm/values.yaml
Labels: apply-on-4-2-x

#6168 Set a default "unknown" name to deleted API and APP ref in support tickets
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/TicketServiceTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6162 fix(console): an endpoint does not inherit its group by default
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/groups/endpoint/edit/api-proxy-group-endpoint-edit.component.spec.ts
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/groups/endpoint/edit/api-proxy-group-endpoint-edit.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6208 Use official versions of Secret Provider
  pom.xml
Labels: apply-on-master

#6212 feat(helm): add network policy
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/common/networkpolicy.yaml
  helm/tests/common/networkPolicy_test.yaml
  helm/values.yaml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6217 fix: update organization role for user
  gravitee-apim-console-webui/src/entities/Constants.ts
  gravitee-apim-console-webui/src/index.ts
  gravitee-apim-console-webui/src/organization/configuration/user/detail/org-settings-user-detail.component.spec.ts
  gravitee-apim-console-webui/src/organization/configuration/user/detail/org-settings-user-detail.component.ts
  gravitee-apim-console-webui/src/shared/testing/gio-http.testing.module.ts
Labels: apply-on-master

#6226 Add abstract super class to fix issue with javadoc generation
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/flow/selector/FlowSelector.java
Labels: apply-on-master

#6229 Properly display wide headers in Application logs
  gravitee-apim-console-webui/src/management/application/details/application-navigation/application-navigation.component.scss
  gravitee-apim-console-webui/src/management/application/details/logs/application-log.html
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6234 fix: make service discovery creating HttpEndpoint instead of Endpoint
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/verticle/EndpointDiscoveryVerticle.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6252 [4.2.x] Bump policies
  gravitee-apim-distribution/pom.xml
  pom.xml
Labels: apply-on-master

#6207 Console - application general migration - seventh part
  gravitee-apim-console-webui/src/management/application/details/user-group-access/groups/application-general-groups.component.html
  gravitee-apim-console-webui/src/management/application/details/user-group-access/groups/application-general-groups.component.scss
  gravitee-apim-console-webui/src/management/application/details/user-group-access/groups/application-general-groups.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/user-group-access/groups/application-general-groups.component.ts
Labels: ready_to_test

#6266 [CI][Bridge] Adapt bridge compatibility tests - 4.2.x
  .circleci/ci/src/pipelines/tests/resources/bridge-compatibility-tests/bridge-compatibility-tests.yml
  .circleci/ci/src/workflows/workflow-bridge-compatibility-tests.ts
Labels: apply-on-master

#6262 fix: use addControl to add new control dynamically
  gravitee-apim-portal-webui/src/app/pages/registration/registration.component.html
  gravitee-apim-portal-webui/src/app/pages/registration/registration.component.ts
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6259 feat: allow to delete all events of a given API
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/EventRepository.java
  gravitee-apim-repository/gravitee-apim-repository-gateway-bridge-http/gravitee-apim-repository-gateway-bridge-http-client/src/main/java/io/gravitee/repository/bridge/client/management/HttpEventRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcEventRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoEventRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryCustom.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/EventRepositoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/EventService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EventServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x
