Repository gravitee-io/gravitee-api-management, pull requests merged in 2023-08, with the labels that each got.

#4877 fix(cockpit): trial api creating duplicate plan fixed
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/V4ApiServiceCockpitImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/services/V4ApiServiceCockpitTest.java
Labels: apply-on-master

#4883 fix: use criteria to filter APIs in plan upgraders
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/PlansDataFixUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/PlansFlowsDefinitionUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/PlansDataFixUpgraderTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/PlansFlowsDefinitionUpgraderTest.java
Labels: apply-on-master

#4885 fix: bump repository bridge
  pom.xml
Labels: apply-on-master

#4888 chore: remove unnecessary jar file
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/gravitee-apim-rest-api-service-3.21.0-SNAPSHOT.jar
Labels: apply-on-master

#4886 Add a property to simplify the distribution build
  .circleci/config.yml
  Taskfile.yml
  gravitee-apim-distribution/pom.xml
  release/ci-steps/package-bundles.mjs
Labels: apply-on-master

#4902 fix(mongodb): improve mongodb indexes
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/apis/EnvironmentIdNameDefinitionVersionIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/events/PropertiesApiIdTypeIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/events/PropertiesApiIdUpdatedAtIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/events/PropertiesDictionaryIdUpdatedAtIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/events/TypeUpdatedAtIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/subscriptions/UpdatedAtAscIndexUpgrader.java
Labels: apply-on-master

#4904 feat(helm): define es settings
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_es_reporter_ingest_plugins_test.yaml
  helm/tests/gateway/configmap_es_reporter_test.yaml
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#4910 ci: fix pr environment links
  .circleci/config.yml
Labels: apply-on-3-20-x, apply-on-4-0-x

#4896 fix(mongodb): improve mongodb indexes
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/create-index.js
Labels: apply-on-3-20-x

#4924 chore: update endpoint dependencies for more information cards
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-mock/src/main/resources/images/mock.png
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-mock/src/main/resources/plugin.properties
  pom.xml
Labels: apply-on-4-0-x

#4923 fix: redirect to staging plans after creating one
  gravitee-apim-console-webui/src/management/api/portal/plans/edit/api-portal-plan-edit.component.spec.ts
  gravitee-apim-console-webui/src/management/api/portal/plans/edit/api-portal-plan-edit.component.ts
Labels: apply-on-4-0-x

#4933 Apim 2448 gko subscriptions
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/list/api-portal-subscription-list.component.html
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/list/api-portal-subscription-list.component.spec.ts
Labels: apply-on-master

#4938 fix: preserve parent route params
  gravitee-apim-console-webui/src/management/api/policy-studio/gio-policy-studio-routing.module.ts
Labels: ready_to_test

#4942 add missing libc6-compat for kafka compression feature
  gravitee-apim-gateway/docker/Dockerfile-from-download
Labels: apply-on-master

#4947 fix: ignore the checksum validation on 3.20.x liquibase changeSet.
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v3_20_0/schema.yml
Labels: apply-on-master

#4948 fix: adapt libc6-compat to platform architecture [skip ci]
  gravitee-apim-gateway/docker/Dockerfile
  gravitee-apim-gateway/docker/Dockerfile-from-download
Labels: apply-on-master

#4952 fix: add changeset to add subscription failure cause column [skip ci]
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_0_3/schema.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
Labels: apply-on-master

#4916 Allow to edit restriction form during creation workflow
  gravitee-apim-console-webui/src/management/api/component/plan/3-restriction-step/plan-edit-restriction-step.component.ts
  gravitee-apim-console-webui/src/management/api/component/plan/api-plan-form.component.html
  gravitee-apim-console-webui/src/management/api/component/plan/api-plan-form.component.ts
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/step-4-security/step-4-security-1-plans.harness.ts
Labels: apply-on-master

#4957 fix: align Alert Engine CTA's with other OS
  gravitee-apim-console-webui/jest.setup.js
  gravitee-apim-console-webui/src/components/alerts/alertEnginePromotion/alert-engine-promotion-component.ts
  gravitee-apim-console-webui/src/components/alerts/alertEnginePromotion/alert-engine-promotion.html
  gravitee-apim-console-webui/src/components/alerts/alerts.component.ajs.ts
  gravitee-apim-console-webui/src/components/alerts/alerts.html
  gravitee-apim-console-webui/src/components/alerts/dashboard/alerts-dashboard.component.ts
  gravitee-apim-console-webui/src/components/alerts/dashboard/alerts-dashboard.html
  gravitee-apim-console-webui/src/management/management.module.ajs.ts
  gravitee-apim-console-webui/src/shared/components/gio-license/gio-license-data.ts
Labels: apply-on-4-0-x

#4963 Remove git branch creation and PR process in Helm release
  release/ci-steps/release-helm.mjs
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master

#4978 fix: revert a change made in 4.x because vertx actually didn't fix the issue
  gravitee-apim-gateway/gravitee-apim-gateway-http/src/main/java/io/gravitee/gateway/reactive/http/vertx/VertxHttpServerResponse.java
Labels: apply-on-4-0-x

#4980 feat: allow to set client identifier/transaction id using query param
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/processor/subscription/SubscriptionProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/processor/subscription/SubscriptionProcessorTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/transaction/TransactionRequestProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/processor/transaction/TransactionRequestProcessorTest.java
Labels: apply-on-4-0-x

#4985 refactor: allow configuring deterministic generator for UuidString
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/common/UuidString.java
Labels: apply-on-4-0-x

#4988 fix: builders of Listener
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ApiBuilder.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/listener/Listener.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/listener/http/HttpListener.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/listener/subscription/SubscriptionListener.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/listener/tcp/TcpListener.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/mapper/ListenerMapperTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiEntrypointServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiLicenseServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-test-fixtures/src/main/java/fixtures/ListenerModelFixtures.java
Labels: apply-on-4-0-x

#4944 chore: bump gravitee-common-elasticsearch dependency
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/pom.xml
Labels: apply-on-4-0-x, apply-on-master

#4991 fix: index system folder locally
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/PageType.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/test/java/io/gravitee/rest/api/model/PageTypeTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/PageService_CreateTest.java
  gravitee-apim-rest-api/pom.xml
Labels: apply-on-4-0-x

#5014 chore: delombok listener class in models package
  gravitee-apim-definition/gravitee-apim-definition-model/pom.xml
  pom.xml
Labels: apply-on-master

#5017 Improve MAPI v2 documentation
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
Labels: apply-on-master

#5020 fix: resolve license popup for api config
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/step-2-entrypoints/step-2-entrypoints-1-list.component.ts
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/step-5-summary/step-5-summary.component.ts
Labels: apply-on-4-0-x

#5026 fix: enable right click on menu items
  gravitee-apim-console-webui/src/components/gio-side-nav/gio-side-nav.component.html
  gravitee-apim-console-webui/src/components/gio-side-nav/gio-side-nav.component.scss
  gravitee-apim-console-webui/src/components/gio-side-nav/gio-side-nav.component.ts
  gravitee-apim-console-webui/src/components/gio-side-nav/gio-side-nav.module.ts
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.html
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.scss
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.ts
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.module.ts
  gravitee-apim-console-webui/src/management/application/details/application-navigation/application-navigation.component.html
  gravitee-apim-console-webui/src/management/application/details/application-navigation/application-navigation.component.scss
  gravitee-apim-console-webui/src/management/application/details/application-navigation/application-navigation.component.ts
  gravitee-apim-console-webui/src/management/application/details/application-navigation/application-navigation.module.ts
  gravitee-apim-console-webui/src/management/configuration/settings-navigation/settings-navigation.component.html
  gravitee-apim-console-webui/src/management/configuration/settings-navigation/settings-navigation.component.scss
  gravitee-apim-console-webui/src/management/configuration/settings-navigation/settings-navigation.component.ts
  gravitee-apim-console-webui/src/management/configuration/settings-navigation/settings-navigation.module.ts
Labels: apply-on-4-0-x, apply-on-master, ready_to_test

#5038 fix: enable right click on menu items
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-navigation.component.html
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-navigation.component.scss
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-navigation.component.ts
  gravitee-apim-console-webui/src/management/configuration/settings-navigation/settings-navigation.component.scss
  gravitee-apim-console-webui/src/organization/configuration/navigation/org-navigation.component.html
  gravitee-apim-console-webui/src/organization/configuration/navigation/org-navigation.component.scss
  gravitee-apim-console-webui/src/organization/configuration/navigation/org-navigation.component.ts
Labels: apply-on-4-0-x

#5045 fix: do not allow to delete application primay owner via management API
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/PrimaryOwnerRemovalException.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/MembershipService_DeleteMemberTest.java
Labels: apply-on-3-19-x, apply-on-4-0-x, apply-on-master

#5065 fix: map sampling in API V4 analytics
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/mapper/AnalyticsMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/mapper/ApiMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/fixtures/AnalyticsFixtures.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/mapper/AnalyticsMapperTest.java
Labels: apply-on-4-0-x

#5078 fix: read pem certs and keys as list for elasticsearch configuration
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/configuration/RepositoryConfiguration.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/configuration/ElasticsearchRepositoryConfigurationTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/resources/configuration/gravitee.yml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#5091 Bump `gravitee-reporter-elasticsearch` to `4.2.2`
  pom.xml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#5089 feat(helm): add podSecurityContext
  helm/Chart.yaml
  helm/templates/api/api-deployment.yaml
  helm/templates/gateway/gateway-deployment.yaml
  helm/templates/portal/portal-deployment.yaml
  helm/templates/ui/ui-deployment.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/gateway/deployment_test.yaml
  helm/tests/portal/deployment_test.yaml
  helm/tests/ui/deployment_test.yaml
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-4-0-x

#5118 Run repository tests against MongoDB 7.0
  .circleci/config.yml
  gravitee-apim-repository/gravitee-apim-repository-mongodb/README.md
Labels: apply-on-master

#5117 feat(helm): avoid empty user
  helm/Chart.yaml
  helm/templates/api/api-configmap.yaml
  helm/tests/api/configmap_test.yaml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-4-0-x
