Repository gravitee-io/gravitee-api-management, pull requests merged in 2023-09, with the labels that each got.

#5136 feat: enable v4 support on file reporter
  pom.xml
Labels: apply-on-4-0-x

#5140 chore: bump custom-query-parameters-parser to 2.0.0
  gravitee-apim-distribution/pom.xml
  gravitee-apim-integration-tests/pom.xml
  pom.xml
Labels: apply-on-master

#5149 docs: add 4.1.0 changes to helm chart and changelog
  helm/CHANGELOG.md
  helm/Chart.yaml
Labels: apply-on-4-1-x

#5174 chore: bump gravitee-common version
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerV4Test.java
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#5164 fix: make gateway use v4 emulation engine by default
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandlerFactory.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/ApiReactorHandlerFactoryTest.java
Labels: apply-on-4-0-x, apply-on-4-1-x

#5186 feat: add request upgrade on entrypoint config
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/api-entrypoints-v4-general.component.html
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/api-entrypoints-v4-general.component.spec.ts
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/api-entrypoints-v4-general.component.ts
  gravitee-apim-console-webui/src/shared/components/gio-license/gio-license-data.ts
Labels: apply-on-4-0-x, apply-on-4-1-x

#5198 fix(docker): prevent $uri replacement in nginx configuration
  gravitee-apim-console-webui/docker/Dockerfile
  gravitee-apim-console-webui/docker/Dockerfile-from-download
  gravitee-apim-console-webui/docker/config/default.conf
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/Dockerfile-from-download
  gravitee-apim-portal-webui/docker/config/default.conf
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-4-0-x, ready_to_test, apply-on-4-1-x

#5226 chore: bump gravitee common version
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/manager/ApiManagerV4Test.java
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#5235 fix: add guard to routes under license
  gravitee-apim-console-webui/src/management/api/apis.route.ts
  gravitee-apim-console-webui/src/management/configuration/notifications/global.notifications.settings.route.ts
  gravitee-apim-console-webui/src/management/management.route.ts
Labels: apply-on-4-0-x, apply-on-4-1-x

#5182 Update Guava from `31.0.1-jre` to `32.1.2-jre`
  pom.xml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5242 fix: bump jwt policy to 4.1.1
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#5220 fix: handle path mappings containing wildwards
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ApiDeserializer.java
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/test/resources/io/gravitee/definition/jackson/api-with-wildcard-in-path-mapping.json
Labels: apply-on-3-19-x, apply-on-4-0-x, apply-on-4-1-x

#5253 Use latest version of wiremock
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/AbstractWiremockGatewayTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-services/gravitee-apim-rest-api-services-dictionary/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-services/gravitee-apim-rest-api-services-dynamic-properties/pom.xml
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5274 Fix action name for bridge tests
  .circleci/ci/src/pipelines/config-factory.ts
  .circleci/config.yml
Labels: apply-on-master, apply-on-4-1-x

#5296 fix(sync): order subscriptions during incremental sync
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/synchronizer/api/ApiKeyAppender.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/synchronizer/api/SubscriptionAppender.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/repository/synchronizer/api/ApiKeyAppenderTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/repository/synchronizer/api/SubscriptionAppenderTest.java
Labels: apply-on-master, apply-on-4-1-x

#5303 refactor(console): rewords logs entry in submenu
  gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-v4-menu.service.ts
Labels: apply-on-master

#5289 feat(helm): allow ingress wildcard
  helm/Chart.yaml
  helm/templates/api/api-ingress-management.yaml
  helm/templates/api/api-ingress-portal.yaml
  helm/templates/gateway/gateway-ingress.yaml
  helm/templates/portal/portal-ingress.yaml
  helm/templates/ui/ui-ingress.yaml
  helm/tests/api/ingress_management_test.yaml
  helm/tests/api/ingress_portal_test.yaml
  helm/tests/gateway/ingress_test.yaml
  helm/tests/portal/ingress_test.yaml
  helm/tests/ui/ingress_test.yaml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master, apply-on-4-1-x

#5171 feat(helm): remove smtp default example configuration
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-configmap.yaml
  helm/tests/api/configmap_email_test.yaml
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-4-0-x, apply-on-master

#5323 avoid blinking in request logs page
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs/components/api-runtime-logs-list/api-runtime-logs-list.component.html
Labels: apply-on-master

#5325 fix(ci): fix branch selection from commit
  .circleci/ci/src/index.ts
  .circleci/config.yml
Labels: apply-on-master, apply-on-4-1-x

#5329 fix(import): compute page general condition id on api import
  gravitee-apim-e2e/api-test/src/mapi-v2/import/definition/api-import-with-everything.spec.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiIdsCalculatorServiceImpl.java
Labels: apply-on-master, apply-on-4-1-x

#5290 fix: don't use requestStream() to avoid memory leak
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/main/java/io/gravitee/gateway/reactive/standalone/vertx/HttpProtocolVerticle.java
Labels: apply-on-4-0-x, apply-on-4-1-x

#5338 fix(ci): compute right k8s namespace
  .circleci/ci/src/jobs/job-deploy-on-azure.ts
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
Labels: apply-on-master, apply-on-4-1-x

#5339 feat(helm): add unknownExpireAfter parameter in management-api
  helm/Chart.yaml
  helm/templates/api/api-configmap.yaml
  helm/tests/api/configmap_test.yaml
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-4-0-x, apply-on-4-1-x

#5357 Console - make Failover save works
  gravitee-apim-console-webui/src/management/api/proxy/failover/api-proxy-failover.component.spec.ts
  gravitee-apim-console-webui/src/management/api/proxy/failover/api-proxy-failover.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
Labels: apply-on-4-1-x

#5368 Fix Slack notification on failure
  .circleci/ci/src/commands/cmd-notify-on-failure.ts
  .circleci/ci/src/pipelines/tests/resources/bridge-compatibility-tests/bridge-compatibility-tests.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-console-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-portal-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
  .circleci/ci/src/pipelines/tests/resources/repositories-tests/repositories-tests.yml
Labels: apply-on-master, apply-on-4-1-x

#5373 Console - small fix on api groups management
  gravitee-apim-console-webui/src/management/api/general/user-group-access/members/api-general-members.component.ts
Labels: apply-on-master

#5382 chore: bump mock policy
  gravitee-apim-distribution/pom.xml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5393 fix: use new path parameter processor at each call
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/RequestProcessorChainFactory.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-integration/src/test/java/io/gravitee/gateway/tests/http/PathParametersIntegrationTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-integration/src/test/resources/logback-test.xml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5401 Fix CI - Use typescript for version replacement
  .circleci/ci/src/jobs/job-release-commit-and-prepare-next-version.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
Labels: apply-on-master, apply-on-4-1-x

#5405 Sanitize path in debug request for V4 engine
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/AbstractRequest.java
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/MutableRequest.java
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/test/java/io/gravitee/gateway/reactive/core/context/AbstractRequestTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactive/reactor/DefaultHttpRequestDispatcher.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/reactive/debug/handlers/api/DebugSyncApiReactor.java
Labels: apply-on-master, apply-on-4-1-x
