Repository gravitee-io/gravitee-api-management, pull requests merged in 2023-02, with the labels that each got.

#3090 Display redundant spaces in API, Application and Plan deletion popup
  gravitee-apim-console-webui/src/components/dialog/confirmAndValidate.dialog.html
Labels: backport-to-3-19-x

#3117 Remove all entries of a subscription from cache
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/services/SubscriptionService.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/service/SubscriptionServiceTest.java
Labels: apply-on-3-19-x

#3127 Correctly handle IDP with name containing upper case character
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/IdentityProviderUpgrader.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#3126 filter gateway started expired events
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/InstanceServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/InstanceServiceTest.java
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#3150 Display full query param values when they contain `=` in them
  gravitee-apim-console-webui/src/management/api/analytics/logs/log.component.spec.ts
  gravitee-apim-console-webui/src/management/api/analytics/logs/log.component.ts
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-master

#3160 Add SPIKE_ARREST_TOO_MANY_REQUESTS template key
  gravitee-apim-console-webui/src/entities/alerts/api.metrics.ts
  gravitee-apim-console-webui/src/entities/gateway-error-keys/GatewayErrorKeys.ts
  gravitee-apim-console-webui/src/management/api/proxy/general/response-templates/response-template.controller.ts
Labels: apply-on-3-19-x

#3161 Add SPIKE_ARREST_TOO_MANY_REQUESTS template key - 3.20.x
  gravitee-apim-console-webui/src/entities/alerts/api.metrics.ts
  gravitee-apim-console-webui/src/entities/gateway-error-keys/GatewayErrorKeys.ts
  gravitee-apim-console-webui/src/management/api/proxy/response-templates/edit/api-proxy-response-templates-edit.component.ts
Labels: apply-on-master

#3175 Display API version in APIs list - Backport #3170 on 3.20.x
  gravitee-apim-console-webui/src/management/api/list/api-list.component.html
  gravitee-apim-console-webui/src/management/api/list/api-list.component.spec.ts
  gravitee-apim-console-webui/src/management/api/list/api-list.component.ts
Labels: apply-on-master
