Repository gravitee-io/gravitee-api-management, pull requests merged in 2023-10, with the labels that each got.

#5342 feat(helm): Allow users to define extra manifests
  helm/Chart.yaml
  helm/templates/extra-manifests.yaml
  helm/tests/extra-manifests_test.yaml
  helm/values.yaml
Labels: apply-on-3-20-x, apply-on-3-19-x, apply-on-4-0-x, apply-on-4-1-x

#5423 refactor(console): add filter in api logs rul
  gravitee-apim-console-webui/src/management/api/apis.module.ts
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs/api-runtime-logs.component.spec.ts
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs/api-runtime-logs.component.ts
Labels: apply-on-master

#5436 fix(ci): fix helm releases
  .circleci/ci/src/jobs/helm/job-release-helm.ts
  .circleci/ci/src/pipelines/tests/pipeline-release-helm.spec.ts
Labels: apply-on-master, apply-on-4-1-x

#5439 Console - add date time picker instead of only date for subscription date field
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/api-portal-subscriptions.module.ts
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/components/dialogs/change-end-date/api-portal-subscription-change-end-date-dialog.component.html
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/components/dialogs/expire-api-key/api-portal-subscription-expire-api-key-dialog.component.html
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/components/dialogs/validate/api-portal-subscription-validate-dialog.component.html
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/components/dialogs/validate/api-portal-subscription-validate-dialog.component.ts
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/edit/api-portal-subscription-edit.component.scss
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/edit/api-portal-subscription-edit.component.spec.ts
  gravitee-apim-console-webui/src/scss/gio-global-style.scss
Labels: apply-on-master, apply-on-4-1-x

#5442 Bump Oauth2 Generic resource to fix userClaim selection
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5451 Fix - allow API_PUBLISHER only to manage subscription
  gravitee-apim-console-webui/src/entities/management-api-v2/application/baseApplication.fixture.ts
  gravitee-apim-console-webui/src/entities/management-api-v2/application/baseApplication.ts
  gravitee-apim-console-webui/src/entities/management-api-v2/subscription/subscription.fixture.ts
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/edit/api-portal-subscription-edit.component.spec.ts
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/edit/api-portal-subscription-edit.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
Labels: apply-on-master, apply-on-4-1-x

#5453 fix: bump alert-engine connector
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5464 fix(console): make api-key expire not required
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/components/dialogs/expire-api-key/api-portal-subscription-expire-api-key-dialog.component.html
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/components/dialogs/expire-api-key/api-portal-subscription-expire-api-key-dialog.component.ts
Labels: apply-on-master, apply-on-4-1-x

#5477 test(ui): plans fix solution, looking for unique string
  gravitee-apim-e2e/ui-test/integration/apim/ui/apis/ui-api-plans.spec.ts
Labels: apply-on-4-1-x

#5475 fix: add request and response phases to groovy messages
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#5492 fix: do not remove pathInfo method
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/AbstractRequest.java
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/MutableRequest.java
Labels: apply-on-master, apply-on-4-1-x

#5495 fix: minor bugs with group admin
  gravitee-apim-console-webui/src/management/configuration/groups/group/group.component.ts
  gravitee-apim-console-webui/src/management/configuration/groups/group/group.html
  gravitee-apim-console-webui/src/management/configuration/groups/groups.component.ts
  gravitee-apim-console-webui/src/management/configuration/groups/groups.html
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5478 fix: handle mapping of health checks to definition model
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/fixtures/EndpointFixtures.java
Labels: apply-on-4-0-x, apply-on-4-1-x

#5483 chore: add tcp reporter to default bundle
  gravitee-apim-distribution/pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#5505 Bump policy-oauth2
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5513 Bump policy cache to 2.0.2
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5521 fix: allow usage if EL in endpoint for healthCheck
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/test/java/io/gravitee/gateway/services/healthcheck/http/AbstractManagedEndpointRuleHandlerTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5526 chore: exclude all transitive dependencies from runtime dep
  gravitee-apim-distribution/pom.xml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5531 fix: resolve client call url using X-Forwarded headers
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/bootstrap/ManagementUIBootstrapResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/bootstrap/PortalUIBootstrapResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
  helm/templates/api/api-configmap.yaml
Labels: ready_to_test

#5543 fix useSystemProxy for health-check
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5542 test: improve UserServiceTest by forcing no auth
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/UserServiceTest.java
Labels: apply-on-master

#5548 chore: bump gravitee-json-validation
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5557 Fix changelog path
  release/ci-steps/generate-changelog.mjs
Labels: apply-on-master, apply-on-4-1-x

#5552 Increase the size of notification template description to 512 chars
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v3_20_22/schema.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/NotificationTemplateRepositoryTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5558 Do not remove attached media when renaming an API Doc Page
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5573 Do not throw when OpenAPI to import contains unused variables
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIConverter.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5571 fix: create default alerts on API creation
  gravitee-apim-console-webui/src/components/alerts/alert/alert.html
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/AlertService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AlertServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/AlertService_CreateDefaultsTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_CreateWithDefinitionTest.java
Labels: apply-on-4-0-x, apply-on-master, ready_to_test, apply-on-4-1-x

#5598 chore: bump jaeger tracer to a compatible version
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5601 Remove max length on user email extensions
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/EmailValidator.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/EmailValidatorTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5614 Use the correct API version when updating it with import
  gravitee-apim-console-webui/src/entities/api/Api.ts
  gravitee-apim-console-webui/src/management/api/creation/api-creation-get-started.component.ts
  gravitee-apim-console-webui/src/management/api/portal/details/api-portal-details.component.ts
  gravitee-apim-console-webui/src/services-ngx/api.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/api.service.ts
  gravitee-apim-console-webui/src/shared/components/gio-api-import-dialog/gio-api-import-dialog.component.html
  gravitee-apim-console-webui/src/shared/components/gio-api-import-dialog/gio-api-import-dialog.component.ts
Labels: apply-on-master, apply-on-4-1-x

#5254 fix: accept wide logo on portal
  gravitee-apim-portal-webui/src/app/app.component.css
Labels: apply-on-3-20-x, apply-on-4-0-x, ready_to_test, apply-on-4-1-x

#5643 Bump IP Filtering policy
  pom.xml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5659 fix(helm): protect namespace with quote
  helm/templates/common/rolebinding.yaml
  helm/tests/common/rolebinding_test.yaml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master

#5660 feat: add reset filters button in connection logs list
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs/api-runtime-logs.component.spec.ts
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs/components/api-runtime-logs-quick-filters/api-runtime-logs-quick-filters.component.html
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs/components/api-runtime-logs-quick-filters/api-runtime-logs-quick-filters.component.scss
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs/components/api-runtime-logs-quick-filters/api-runtime-logs-quick-filters.component.ts
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs/components/api-runtime-logs-quick-filters/api-runtime-logs-quick-filters.harness.ts
Labels: ready_to_test

#5678 chore(deps): update rabbitmq endpoint to 1.2.0
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#5681 Allow null host for virtual hosts
  gravitee-apim-console-webui/src/management/api/proxy/entrypoints/api-proxy-entrypoints.component.ts
  gravitee-apim-console-webui/src/management/api/proxy/entrypoints/virtual-host/api-proxy-entrypoints-virtual-host.component.ts
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5668 Console - global metadata migration
  gravitee-apim-console-webui/src/components/gio-metadata/gio-metadata.component.ts
  gravitee-apim-console-webui/src/management/configuration/configuration.route.ts
  gravitee-apim-console-webui/src/management/configuration/metadata/environment-metadata.component.html
  gravitee-apim-console-webui/src/management/configuration/metadata/environment-metadata.component.spec.ts
  gravitee-apim-console-webui/src/management/configuration/metadata/environment-metadata.component.ts
  gravitee-apim-console-webui/src/management/configuration/metadata/environment-metadata.module.ts
  gravitee-apim-console-webui/src/management/management.module.ajs.ts
  gravitee-apim-console-webui/src/management/management.module.ts
  gravitee-apim-console-webui/src/services-ngx/environment-metadata.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/environment-metadata.service.ts
Labels: ready_to_test

#5699 chore: bump gravitee-policy-jws version
  pom.xml
Labels: apply-on-master

#5692 Console - application metadata migration
  gravitee-apim-console-webui/src/components/gio-metadata/gio-metadata.component.ts
  gravitee-apim-console-webui/src/management/application/applications.route.ts
  gravitee-apim-console-webui/src/management/application/details/metadata/application-metadata.component.html
  gravitee-apim-console-webui/src/management/application/details/metadata/application-metadata.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/metadata/application-metadata.component.ts
  gravitee-apim-console-webui/src/management/application/details/metadata/application-metadata.module.ts
  gravitee-apim-console-webui/src/management/application/environment-application.module.ts
  gravitee-apim-console-webui/src/management/management.module.ajs.ts
  gravitee-apim-console-webui/src/services-ngx/application-metadata.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/application-metadata.service.ts
Labels: ready_to_test

#5694 fix: fix readonly setting at org level
  gravitee-apim-console-webui/src/organization/configuration/console/org-settings-general.component.html
  gravitee-apim-console-webui/src/organization/configuration/console/org-settings-general.component.spec.ts
  gravitee-apim-console-webui/src/organization/configuration/console/org-settings-general.component.ts
Labels: apply-on-4-0-x, apply-on-4-1-x

#5707 fix: subscription closed,paused and resumed template
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/templates/subscriptionClosed.html
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/templates/subscriptionPaused.html
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/templates/subscriptionResumed.html
Labels: apply-on-master, apply-on-4-1-x

#5704 fix: let gko to start/stop APIs
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/v4/api/ApiResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_StartTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImplTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#5719 chore: bump policy-mock
  pom.xml
Labels: apply-on-master, apply-on-4-1-x

#5723 Console - metadata migration bug fix
  gravitee-apim-console-webui/src/components/gio-metadata/gio-metadata.component.ts
  gravitee-apim-console-webui/src/management/api/general/documentation/metadata/api-portal-documentation-metadata.component.scss
Labels: ready_to_test
