Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-09, with the labels that each got.

#8805 chore: upgrade reporter-cloud to 1.1.0
  pom.xml
Labels: apply-on-master

#8863 fix(console): add message condition for step in PS
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-master, apply-on-4-4-x

#8856 fix: update Keycloak docker compose
  docker/quick-setup/keycloak/README.md
  docker/quick-setup/keycloak/docker-compose.yml
  docker/quick-setup/keycloak/realm/realm-gio.json
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8877 chore(gateway): bump opentelemetry plugin version to 1.0.1
  pom.xml
Labels: apply-on-master

#8841 fix: Handle MongoDB exception in GatewayNodeMetadataResolver during installation id retrieval
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/main/java/io/gravitee/gateway/standalone/node/GatewayNodeMetadataResolver.java
Labels: apply-on-master

#8893 fix(helm): add missing common.labels in gateway-technical-ingress.yaml
  helm/templates/gateway/gateway-technical-ingress.yaml
  helm/tests/gateway/ingress_labels_test.yaml
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8885 feat(helm): improve the probes definition for the gateway
  helm/templates/gateway/gateway-deployment.yaml
  helm/tests/gateway/deployment_probes_test.yaml
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8903 fix(console): include correct application type in oauth2 settings
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.ts
Labels: apply-on-master, apply-on-4-4-x

#8904 fix(console): order APIs by name only when no query
  gravitee-apim-console-webui/src/management/api/list/api-list.component.html
  gravitee-apim-console-webui/src/management/api/list/api-list.component.spec.ts
  gravitee-apim-console-webui/src/management/api/list/api-list.component.ts
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8892 fix: make "reset" force reload the edit page
  gravitee-apim-console-webui/src/components/documentation/edit-page.component.ajs.ts
Labels: apply-on-master, apply-on-4-4-x

#8922 APIM-6492-deployment-Number-Increment-Fix
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImpl_DeployTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8915 fix(console): add information on OAuth settings update
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.html
  gravitee-apim-console-webui/src/management/application/details/general/application-general.module.ts
Labels: apply-on-master, apply-on-4-4-x

#8937 fix(management): add pre condition to 4.0.20-dashboards script
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_0_20/schema-dashboards.yml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#8949 chore: upgrade nginx base image to 1.26.2
  gravitee-apim-console-webui/docker/Dockerfile
  gravitee-apim-console-webui/docker/Dockerfile-from-download
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/Dockerfile-from-download
Labels: run-e2e-tests

#8961 Distrib : Bump gravitee policy assign attributes
  pom.xml
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8967 fix: bump message filtering policy version
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8978 fix: improve event_organizations and events_latest_organizations tables creation
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_2/00_add_event_organizations.yml
Labels: apply-on-master

#8954 feat: update hide gateways view for cloud flag
  gravitee-apim-console-webui/src/components/gio-side-nav/gio-side-nav.component.ts
  gravitee-apim-console-webui/src/entities/consoleSettings.ts
  gravitee-apim-console-webui/src/management/cloud-guard.ts
  gravitee-apim-console-webui/src/management/management-routing.module.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Cloud.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/ConsoleConfigEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/ConsoleSettingsEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
Labels: run-e2e-tests

#8992 fix(rest-api-service): use right path operator when add OAS validation policy
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/use_case/OAIToImportApiUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/OAIToImportApiUseCaseTest.java
Labels: apply-on-master

#8989 refactor: add abstract super class to fix issue with javadoc generation
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/pom.xml
Labels: apply-on-master

#9001 ci: fix typo in PublishProdDockerImagesJob
  .circleci/ci/src/jobs/job-publish-prod-docker-images.ts
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-no-dry-run-as-latest.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9008 [Helm] update helm versions and changelog syntax
  helm/Chart.yaml
Labels: apply-on-master

#9000 chore: bump bump-policy-assign-attributes
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8995 feat: also disable gateway resources if cloud.enabled flag is true in…
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/InstanceResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/InstancesResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/MonitoringResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/AbstractResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/InstanceResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/InstancesResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/MonitoringResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/CloudEnabledException.java
Labels: apply-on-master

#8985 APIM 5428: info page refresh after duplicating
  gravitee-apim-console-webui/src/management/api/general-info/api-general-info.component.spec.ts
  gravitee-apim-console-webui/src/management/api/general-info/api-general-info.component.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x

#9024 fix(scoring): auto-detect documentation page content type
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/scoring/ScoringProviderImpl.java
Labels: apply-on-master

#9034 fix(integration): check the good permission to verify rights to add group to integration
  gravitee-apim-console-webui/src/management/integrations/user-group-access/groups/integration-general-groups.component.spec.ts
  gravitee-apim-console-webui/src/management/integrations/user-group-access/groups/integration-general-groups.component.ts
Labels: apply-on-4-5-x

#9030 ci: enable debug for aqua/fs_scan job
  .circleci/ci/src/config.ts
  .circleci/ci/src/orbs/aquasec.ts
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-no-dry-run-as-latest.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-distribution-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-gateway-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-integration-tests-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-plugin-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-rest-api-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-console-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-helm-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-portal-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
  .circleci/ci/src/workflows/workflow-pull-requests.ts
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9032 Apim 6857 hide app subcriptions
  gravitee-apim-portal-webui-next/src/app/app.routes.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-subscriptions/application-tab-subscriptions.component.html
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-subscriptions/application-tab-subscriptions.component.scss
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-subscriptions/application-tab-subscriptions.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-subscriptions/application-tab-subscriptions.component.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application.component.html
Labels: apply-on-master

#9063 chore: bump mock policy to 1.14.0
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9055 Apim 6853 consol setting both portals
  gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.html
  gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.scss
  gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.spec.ts
  gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.ts
  gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.harness.ts
Labels: apply-on-master

#9081 fix: change suggested model in AI SPG
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/shared_policy_group/use_case/InitializeSharedPolicyGroupUseCase.java
Labels: apply-on-master

#9077 fix: update conflicting cloud flag
  gravitee-apim-console-webui/src/components/gio-side-nav/gio-side-nav.component.ts
  gravitee-apim-console-webui/src/entities/consoleSettings.ts
  gravitee-apim-console-webui/src/management/cloud-hosted-guard.ts
  gravitee-apim-console-webui/src/management/management-routing.module.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/InstanceResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/InstancesResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/MonitoringResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/InstanceResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/InstancesResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/MonitoringResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/CloudHosted.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/ConsoleConfigEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/ConsoleSettingsEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/CloudEnabledException.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
Labels: apply-on-master

#9070 fix(integration): filtering of integration shouldn't rely only on group
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/IntegrationRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcIntegrationRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoIntegrationRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/integration/IntegrationMongoRepositoryCustom.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/integration/IntegrationMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/java/io/gravitee/repository/mongodb/management/MongoIntegrationRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/java/io/gravitee/repository/mongodb/management/internal/integration/IntegrationMongoRepositoryImplTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/IntegrationRepositoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/integration/IntegrationsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/query_service/IntegrationQueryService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/use_case/GetIntegrationsUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/query_service/integration/IntegrationQueryServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/IntegrationQueryServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/integration/use_case/GetIntegrationsUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/query_service/integration/IntegrationQueryServiceImplTest.java
Labels: apply-on-4-5-x

#9096 feat(integration): pass parameters to (un)subscribe
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/model/IntegrationSubscription.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/integration/IntegrationAgentImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/integration/IntegrationAgentImplTest.java
Labels: apply-on-4-5-x

#9084 fix: update api alert and refresh data
  gravitee-apim-console-webui/src/components/alerts/alert/alert.component.ajs.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x

#9061 fix: dashboard tenant widget
  gravitee-apim-console-webui/src/services/analytics.service.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9083 fix(portal-next): handle api plan permissions for user in subscription details
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-subscriptions/subscriptions-details/subscriptions-details.component.html
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-subscriptions/subscriptions-details/subscriptions-details.component.scss
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-subscriptions/subscriptions-details/subscriptions-details.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-subscriptions/subscriptions-details/subscriptions-details.component.ts
Labels: apply-on-master

#9121 fix: bump callout policy version
  pom.xml
Labels: apply-on-4-5-x, apply-on-master

#9073 fix(console): update api details
  gravitee-apim-console-webui/src/portal/customization/api/api-list/portal-api-list.component.spec.ts
  gravitee-apim-console-webui/src/portal/customization/api/api-list/portal-api-list.component.ts
  gravitee-apim-console-webui/src/portal/customization/api/api-list/portal-api-list.harness.ts
Labels: apply-on-master

#9101 fix: add sync from to v2 definition context
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiDefinitionContextResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/DefinitionContextEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiCRDServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDefinitionContextServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDefinitionContextServiceTest.java
Labels: apply-on-master

#9118 feat: add api v2 group validation
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiValidationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiValidationServiceImplTest.java
Labels: apply-on-4-5-x

#9062 APIM-6599: handle EL dynamic limit for portal api mapping
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/ApiTemplateVariables.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/PlanMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApiResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/PlanMapperTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiPlansResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceNotAuthenticatedTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApiResourceTest.java
Labels: apply-on-4-5-x, apply-on-master

#9129 migrate dictionaries event with latest start or stop publish or unpublish state
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/EventService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EventServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/EventsLatestUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/EventsLatestUpgraderTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9043 fix: use context user as a po for k8s resources
  gravitee-apim-console-webui/src/management/api/user-group-access/members/api-general-members.component.html
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/ValidateApiCRDDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/domain_service/ValidateApplicationCRDDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/member/domain_service/ValidateCRDMembersDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/member/CRDMembersDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/MembershipService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiCRDServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiValidationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/fixtures/core/model/AuditInfoFixtures.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/domain_service/ValidateApiCRDDomainServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/domain_service/ValidateCRDMembersDomainServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/ImportApiCRDUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/application/ImportApplicationCRDUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/member/CRDMembersDomainServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiCRDService_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiCRDService_UpdateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiValidationServiceImplTest.java
Labels: apply-on-master

#9094 fix: show sharding tag endpoints with access points in portal
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiEntrypointServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiEntrypointServiceImplTest.java
Labels: apply-on-master, apply-on-4-4-x

#9164 fix: restore default metadata for compatibility
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/MetadataReferenceType.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoMetadataRepository.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/metadata/model/Metadata.java
Labels: apply-on-master, apply-on-4-4-x

#9166 fix(portal-next): fix banner secondary button
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.html
Labels: apply-on-master

#9187 fix: bump data logging masking policy version
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9132 feat(console): api-score-dashboard summary backend data
  gravitee-apim-console-webui/src/management/api-score/api-score-dashboard/api-score-dashboard.component.html
  gravitee-apim-console-webui/src/management/api-score/api-score-dashboard/api-score-dashboard.component.scss
  gravitee-apim-console-webui/src/management/api-score/api-score-dashboard/api-score-dashboard.component.spec.ts
  gravitee-apim-console-webui/src/management/api-score/api-score-dashboard/api-score-dashboard.component.ts
  gravitee-apim-console-webui/src/management/api-score/api-score.model.ts
  gravitee-apim-console-webui/src/services-ngx/api-scoring.service.ts
Labels: apply-on-4-5-x

#9163 Console: In case of error 401 logout the user and allow them to reconnect
  gravitee-apim-console-webui/src/auth/auth.service.ts
  gravitee-apim-console-webui/src/shared/interceptors/http-error.interceptor.spec.ts
  gravitee-apim-console-webui/src/shared/interceptors/http-error.interceptor.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-security/src/main/java/io/gravitee/rest/api/security/csrf/CsrfRequestMatcher.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-security/src/test/java/io/gravitee/rest/api/security/csrf/CsrfRequestMatcherTest.java
Labels: apply-on-4-5-x, apply-on-4-3-x, apply-on-4-4-x

#9167 Rest API: should delete SPG history when delete SPG
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/shared_policy_group/crud_service/SharedPolicyGroupHistoryCrudService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/shared_policy_group/use_case/DeleteSharedPolicyGroupUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/shared_policy_group/SharedPolicyGroupHistoryCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/SharedPolicyGroupHistoryCrudServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/shared_policy_group/use_case/DeleteSharedPolicyGroupUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/crud_service/shared_policy_group/SharedPolicyGroupHistoryCrudServiceImplTest.java
Labels: apply-on-master

#9206 Apim 5778 add missing configuration helm
  helm/Chart.yaml
  helm/README.md
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_ssl_test.yaml
Labels: apply-on-4-5-x, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9196 fix(portal-next): remove company name from footer
  gravitee-apim-portal-webui-next/src/components/footer/footer.component.html
  gravitee-apim-portal-webui-next/src/components/footer/footer.component.ts
Labels: apply-on-master

#9194 feat(console): docker config files for agents
  gravitee-apim-console-webui/src/management/integrations/integration-agent/integration-agent.configuration.ts
Labels: apply-on-4-5-x

#9222 fix(console): use utc timezone to select From To datetime & use 0-base index page for events
  gravitee-apim-console-webui/src/management/home/components/gio-api-events-table/gio-api-events-table.component.spec.ts
  gravitee-apim-console-webui/src/management/home/components/gio-api-events-table/gio-api-events-table.component.ts
  gravitee-apim-console-webui/src/management/home/components/gio-quick-time-range/gio-quick-time-range.component.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-4-x

#9217 feat(api-score): add links for api-score dashboard APIs table.
  gravitee-apim-console-webui/src/management/api-score/api-score-dashboard/api-score-dashboard.component.html
  gravitee-apim-console-webui/src/management/api-score/api-score-dashboard/api-score-dashboard.component.spec.ts
  gravitee-apim-console-webui/src/management/api-score/api-score.model.ts
Labels: apply-on-4-5-x

#9234 fix(scoring): send null values when no data
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/ScoringEnvironmentApi.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/ScoringEnvironmentSummary.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcScoringReportRepository.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/ScoringReportReportRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/scoring-tests/apis.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/ScoringReportAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/query_service/scoring/ScoringReportQueryServiceImplTest.java
Labels: apply-on-master

#9240 chore(deps): bump ui-components to 4.2.5
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-4-2-x, apply-on-4-3-x

#9241 chore(deps): bump ui-components to 4.2.5
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-4-5-x, apply-on-master

#9235 feat(api-score): add handling no data with null values
  gravitee-apim-console-webui/src/management/api-score/api-score-dashboard/api-score-dashboard.component.html
Labels: apply-on-4-5-x

#9215 Console: make etag / if-match work with angular & angularJs
  gravitee-apim-console-webui/src/app.interceptor.ajs.ts
  gravitee-apim-console-webui/src/management/api/creation-v2/steps/api-creation-v2.controller.ajs.ts
  gravitee-apim-console-webui/src/management/api/properties-v1/properties.controller.ajs.ts
  gravitee-apim-console-webui/src/services/api.service.ts
  gravitee-apim-console-webui/src/shared/interceptors/if-match-etag.interceptor.spec.ts
  gravitee-apim-console-webui/src/shared/interceptors/if-match-etag.interceptor.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-4-x

#9228 fix: redeploy the apikey with the proper plan id and subscription ins…
  gravitee-apim-gateway/gravitee-apim-gateway-security/gravitee-apim-gateway-security-apikey/src/main/java/io/gravitee/gateway/security/apikey/ApiKeyAuthenticationHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-security/gravitee-apim-gateway-security-apikey/src/test/java/io/gravitee/gateway/security/apikey/ApiKeyAuthenticationHandlerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/SubscriptionServiceTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9256 fix: allow to search for path with multiple '/'
  gravitee-apim-portal-webui-next/src/services/application-log.service.spec.ts
  gravitee-apim-portal-webui-next/src/services/application-log.service.ts
Labels: apply-on-master

#9255 fix: avoid duplicates keys for categories
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/CategoryServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/CategoryService_CreateTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9274 Remove all usage of Snyk in the CI
  .circleci/ci/src/commands/cmd-add-docker-image-in-snyk.ts
  .circleci/ci/src/commands/cmd-build-ui-image.ts
  .circleci/ci/src/commands/index.ts
  .circleci/ci/src/config.ts
  .circleci/ci/src/jobs/helm/index.ts
  .circleci/ci/src/jobs/helm/job-snyk-apim-charts.ts
  .circleci/ci/src/jobs/index.ts
  .circleci/ci/src/jobs/job-add-docker-images-in-snyk.ts
  .circleci/ci/src/jobs/job-build-backend-images.ts
  .circleci/ci/src/orbs/index.ts
  .circleci/ci/src/orbs/snyk.ts
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-no-dry-run-as-latest.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
  .circleci/ci/src/workflows/workflow-build-rpm-and-docker-images.ts
  .circleci/ci/src/workflows/workflow-full-release.ts
  .circleci/ci/src/workflows/workflow-pull-requests.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9239 chore: downgrade gravitee-bom
  pom.xml
Labels: apply-on-master

#9247 feat(api-score): demo and feedback improvements for API Score
  gravitee-apim-console-webui/src/management/api-score/api-score-dashboard/api-score-dashboard.component.html
  gravitee-apim-console-webui/src/management/api-score/api-score-dashboard/api-score-dashboard.component.scss
  gravitee-apim-console-webui/src/management/api/scoring/api-scoring.component.html
  gravitee-apim-console-webui/src/management/api/scoring/api-scoring.component.spec.ts
  gravitee-apim-console-webui/src/management/api/scoring/api-scoring.fixture.ts
  gravitee-apim-console-webui/src/management/api/scoring/api-scoring.model.ts
Labels: apply-on-4-5-x

#9265 fix: fix error handling
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-logs/application-log-table/application-log-table.component.ts
Labels: apply-on-master

#9229 Fix reset button in v2 API documentation
  gravitee-apim-console-webui/src/components/documentation/edit-page.component.ajs.ts
  gravitee-apim-console-webui/src/components/documentation/edit-page.html
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x

#9145 refactor: mv env/org media liquibase script to 4.4
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_10/00_add_media_org_env.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_0/07_add_scoring_ruleset_table.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
Labels: apply-on-master

#9273 fix(scoring): should delete APIs reports when deleting API
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl_findAllTest.java
Labels: apply-on-master

#9248 feat: add delete membership command
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteMembershipCommandHandler.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteMembershipCommandHandlerTest.java
Labels: apply-on-4-5-x, apply-on-master

#9298 fix: bump bridge repository version
  pom.xml
Labels: apply-on-master

#9303 chore: bump ui particles
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-4-2-x

#9294 feat: disable mTLS plans for TCP APIs
  gravitee-apim-console-webui/src/management/api/creation-v4/api-creation-v4.tcp-proxy.component.spec.ts
  gravitee-apim-console-webui/src/services-ngx/constants.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/constants.service.ts
  gravitee-apim-definition/gravitee-apim-definition-model/src/test/java/fixtures/definition/PlanFixtures.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/plan/use_case/CreatePlanUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/fixtures/core/model/PlanFixtures.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/plan/use_case/CreatePlanUseCaseTest.java
Labels: apply-on-master

#9305 chore(console): bump ui particles
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x

#9304 fix: avoid possible npe during subscription transfer
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
Labels: apply-on-4-1-x, apply-on-4-2-x

#9313 fix: bump webhook version
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x

#9314 fix: bump webhook version
  pom.xml
Labels: apply-on-4-5-x, apply-on-master

#9319 chore(deps): bump redis-cache to 1.5.0
  pom.xml
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9330 fix(console): make etag / if-match work with angular & angularJs
  gravitee-apim-console-webui/src/shared/interceptors/if-match-etag.interceptor.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x

#9331 fix: bump webhook version
  pom.xml
Labels: apply-on-4-5-x, apply-on-4-4-x

#9335 fix: bump webhook version
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x

#9327 fix(console): hide add link for read permissions
  gravitee-apim-console-webui/src/portal/customization/top-bar/menu-link-list/menu-link-list.component.html
  gravitee-apim-console-webui/src/portal/customization/top-bar/menu-link-list/menu-link-list.component.spec.ts
  gravitee-apim-console-webui/src/portal/customization/top-bar/menu-link-list/menu-link-list.component.ts
Labels: apply-on-master

#9342 fix: plan security type can be null
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/plan/use_case/CreatePlanUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/plan/use_case/CreatePlanUseCaseTest.java
Labels: apply-on-master, run-e2e-tests

#9321 fix(api-score): scoring badge color fix
  gravitee-apim-console-webui/src/management/api/scoring/api-scoring.component.html
  gravitee-apim-console-webui/src/management/api/scoring/api-scoring.component.scss
Labels: apply-on-4-5-x
