Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-02, with the labels that each got.

#6519 feat: add apiId in HealthCheck log
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6518 fix: fix request only v2 api log
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/pom.xml
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/spring/DatabaseHydrator.java
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6534 fix(console): only subscriptions to api key plans can validate with c…
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/components/dialogs/validate/api-portal-subscription-validate-dialog.harness.ts
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/edit/api-portal-subscription-edit.component.spec.ts
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/edit/api-portal-subscription-edit.component.ts
Labels: apply-on-4-1-x, apply-on-4-2-x

#6541 Console - settings api quality - first part
  gravitee-apim-console-webui/src/management/settings/api-quality-rules-ng/api-quality-rules-ng-add-dialog/api-quality-rules-ng-add-dialog.component.html
  gravitee-apim-console-webui/src/management/settings/api-quality-rules-ng/api-quality-rules-ng-add-dialog/api-quality-rules-ng-add-dialog.component.scss
  gravitee-apim-console-webui/src/management/settings/api-quality-rules-ng/api-quality-rules-ng-add-dialog/api-quality-rules-ng-add-dialog.component.ts
  gravitee-apim-console-webui/src/management/settings/api-quality-rules-ng/api-quality-rules-ng.component.html
  gravitee-apim-console-webui/src/management/settings/api-quality-rules-ng/api-quality-rules-ng.component.scss
  gravitee-apim-console-webui/src/management/settings/api-quality-rules-ng/api-quality-rules-ng.component.spec.ts
  gravitee-apim-console-webui/src/management/settings/api-quality-rules-ng/api-quality-rules-ng.component.ts
  gravitee-apim-console-webui/src/management/settings/api-quality-rules-ng/api-quality-rules-ng.module.ts
  gravitee-apim-console-webui/src/management/settings/settings.module.ts
  gravitee-apim-console-webui/src/management/settings/settings.route.ts
  gravitee-apim-console-webui/src/services-ngx/quality-rule.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/quality-rule.service.ts
Labels: ready_to_test

#6569 Endpoints Proxy V4 - add "Propagate client Accept-Encoding header" option
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/main/resources/schemas/sharedConfiguration/schema-form.json
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-2-x

#6582 fix: use correct method to fetch user's application
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApplicationService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiAuthorizationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiAuthorizationServiceImplTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6610 fix(portal): security type may be empty for push plans
  gravitee-apim-portal-webui/src/app/pages/application/application-subscriptions/application-subscriptions.component.ts
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6620 fix(mapiv2): ignore case on endpoint type
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/mapper/EndpointMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/mapper/EndpointMapperTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6632 Update dependencies
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6646 fix(export): plan excluded groups don't depend on api's groups
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/jackson/ser/api/ApiSerializer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_EnumValueWittenLowercaseTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6664 fix(console): first page is 1 not 0
  gravitee-apim-console-webui/src/management/configuration/groups/group/group.component.ts
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6654 feat: create dql endpoint group from compatible entrypoint
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/create/api-endpoint-group-create.component.html
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/create/api-endpoint-group-create.component.spec.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/create/api-endpoint-group-create.component.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/create/api-endpoint-group-create.harness.ts
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/api-entrypoints-v4.module.ts
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/edit/api-entrypoints-v4-edit.component.html
Labels: ready_to_test

#6678 fix(shared key): update apikey atomically to avoid concurrency issue
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/ApiKeyRepository.java
  gravitee-apim-repository/gravitee-apim-repository-gateway-bridge-http/gravitee-apim-repository-gateway-bridge-http-client/src/main/java/io/gravitee/repository/bridge/client/management/HttpApiKeyRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoApiKeyRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/key/ApiKeyMongoRepositoryCustom.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/key/ApiKeyMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/ApiKeyRepositoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiKeyServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiKeyServiceTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6709 fix: avoid npe when importing with a group PO
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorService_CreateWithDefinitionTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/import-api.definition+primaryOwner.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/import-api.definition+primaryOwnerGroup.json
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#6714 fix: avoid NPE when transfering ownership on imports
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorService_CreateWithDefinitionTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x

#6726 fix(logging): override http method when capturing endpoint request
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/analytics/logging/LoggingHook.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/v4/analytics/logging/LoggingHookTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6734 Rest api - fix creating application with "@" in name
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/sanitizer/HtmlSanitizer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/test/java/io/gravitee/rest/api/sanitizer/HtmlSanitizerTest.java
Labels: apply-on-3-20-x, apply-on-master, ready_to_test, apply-on-4-1-x, apply-on-4-2-x

#6704 feat(ui-health-check-endpoint): Enable health-check config for the en…
  gravitee-apim-console-webui/src/entities/management-api-v2/api/v4/endpointServices.ts
  gravitee-apim-console-webui/src/management/api/component/health-check-v4-form/api-health-check-v4-form.component.html
  gravitee-apim-console-webui/src/management/api/component/health-check-v4-form/api-health-check-v4-form.component.scss
  gravitee-apim-console-webui/src/management/api/component/health-check-v4-form/api-health-check-v4-form.component.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/api-endpoint-group.component.spec.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint/api-endpoint.component.html
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint/api-endpoint.component.spec.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint/api-endpoint.component.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint/api-endpoint.harness.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint/api-endpoint.module.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/validation/EndpointGroupsValidationServiceImpl.java
Labels: ready_to_test

#6685 Apim 1428 configure publisher messages
  gravitee-apim-console-webui/src/management/api/api-navigation/api-v4-menu.service.ts
  gravitee-apim-console-webui/src/management/messages/messages.component.html
Labels: ready_to_test

#6785 fix(portal): documentation menu expanded by default
  gravitee-apim-portal-webui/src/app/components/gv-documentation/gv-documentation.component.html
Labels: apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x

#6779 Description field in v4 APIs is nullable
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/v4/api/NewApiEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/mapper/ApiMapper.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x
