Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-05, with the labels that each got.

#7417 fix: bump entrypoint-webhook
  pom.xml
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#7426 fix: added missing ssl configuration missing from helm chart
  helm/CHANGELOG.md
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_redis_test.yaml
  helm/values.yaml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7424 ci: adapt release note for gitbook [skip CI]
  release/helpers/changelog-helper.mjs
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7437 Lucene index: compute the max clause count limit only if necessary
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/AbstractDocumentSearcher.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/ApiDocumentSearcher.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7422 APIM-4805: User can search APIs within a category
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/filtering/FilteringService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/filtering/FilteringServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/ApiAuthorizationService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiAuthorizationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/FilteringServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiAuthorizationServiceImplTest.java
Labels: ready_to_test

#7463 fix(ui): bump swagger-ui to the latest version
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
  gravitee-apim-portal-webui/package-lock.json
  gravitee-apim-portal-webui/package.json
Labels: apply-on-master

#7353 feat(console): Filter logs by entrypoint
  gravitee-apim-console-webui/src/entities/management-api-v2/log/apiLogsResponse.ts
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs/api-runtime-logs.component.html
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs/api-runtime-logs.component.spec.ts
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs/api-runtime-logs.component.ts
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs/components/api-runtime-logs-quick-filters/api-runtime-logs-quick-filters.component.html
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs/components/api-runtime-logs-quick-filters/api-runtime-logs-quick-filters.component.scss
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs/components/api-runtime-logs-quick-filters/api-runtime-logs-quick-filters.component.ts
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs/models/api-runtime-logs-quick-filters.models.ts
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs/services/quick-filters-store.service.ts
  gravitee-apim-console-webui/src/services-ngx/api-logs-v2.service.ts
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/log/v4/model/connection/ConnectionLog.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/log/v4/model/connection/ConnectionLogQuery.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/log/adapter/connection/SearchConnectionLogQueryAdapter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/log/adapter/connection/SearchConnectionLogResponseAdapter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/log/adapter/connection/SearchConnectionLogQueryAdapterTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/log/param/SearchLogsParam.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/analytics/SearchLogsFilters.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/v4/log/connection/BaseConnectionLog.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/log/ConnectionLogsCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/ConnectionLogsCrudServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/log/use_case/SearchConnectionLogsUseCaseTest.java
Labels: ready_to_test

#7485 fix: ensure custom resources names are rfc 1123 compliant
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsCustomResource-contextPath.yml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsCustomResource-contextRef.yml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsCustomResource-noIds.yml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsCustomResource-version.yml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/export-convertAsCustomResource.yml
  pom.xml
Labels: apply-on-4-2-x, apply-on-4-3-x

#7491 fix(console): Display API Events in Home Overview only when user is permitted
  gravitee-apim-console-webui/src/management/home/home-overview/home-overview.component.html
  gravitee-apim-console-webui/src/management/home/home-overview/home-overview.component.spec.ts
  gravitee-apim-console-webui/src/management/home/home.module.ts
Labels: apply-on-master, ready_to_test, apply-on-4-3-x

#7511 fix: make members read-only
  gravitee-apim-console-webui/src/management/api/user-group-access/groups/api-general-groups.component.ts
  gravitee-apim-console-webui/src/management/api/user-group-access/members/api-general-members.component.ts
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7516 chore: bump gravitee-node to include new interops SP plugins
  pom.xml
Labels: apply-on-master

#7473 fix(mapi): add lucene index on user custom fields
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/AbstractDocumentSearcher.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/searcher/UserDocumentSearcher.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/UserDocumentTransformer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/initializer/SearchIndexInitializer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/initializer/SearchIndexInitializerTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7537 fix: fix node monitoring
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/pom.xml
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7545 fix(mapi): validate qos entrypoint with endpoint supported qos
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/edit/api-entrypoints-v4-edit.component.spec.ts
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/edit/api-entrypoints-v4-edit.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/validation/ListenerValidationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/validation/ListenerValidationServiceImplTest.java
Labels: apply-on-master, ready_to_test, apply-on-4-1-x, apply-on-4-3-x

#7558 fix: adapt widget loading
  gravitee-apim-console-webui/src/management/home/home-overview/home-overview.component.ts
Labels: apply-on-master

#7572 chore: upgrade reporter-cloud to 1.0.0-alpha.2
  pom.xml
Labels: apply-on-master

#7574 fix: save metadata on v4 api crd import
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/ApiImportDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/ApiMetadataDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/use_case/ImportCRDUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/MetadataAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/api/ApiImportDomainServiceLegacyWrapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/domain_service/ApiMetadataDomainServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/ImportCRDUseCaseTest.java
Labels: apply-on-4-4-x

#7576 fix: skip notification when exporting a v4 api crd
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/api/ApiCRDExportDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/api/ApiCRDExportDomainServiceImplTest.java
Labels: apply-on-4-4-x

#7577 fix: update docs link in api v4 crd export dialog
  gravitee-apim-console-webui/src/management/api/general-info/api-general-info-export-v4-dialog/api-general-info-export-v4-dialog.component.html
Labels: apply-on-4-4-x

#7569 Apim 4343 filter subscription
  gravitee-apim-portal-webui-next/src/app/api-details/api-tab-subscriptions/api-tab-subscriptions.component.html
  gravitee-apim-portal-webui-next/src/app/api-details/api-tab-subscriptions/api-tab-subscriptions.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/api-details/api-tab-subscriptions/api-tab-subscriptions.component.ts
  gravitee-apim-portal-webui-next/src/entities/subscription/subscription.ts
  gravitee-apim-portal-webui-next/src/services/subscription.service.spec.ts
  gravitee-apim-portal-webui-next/src/services/subscription.service.ts
Labels: apply-on-master

#7592 fix: add vertx-auth-jwt dependency to avoid classpath issue
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-container/pom.xml
Labels: apply-on-master

#7597 fix: avoid conflict when member role changes on v2 import
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImplTest.java
Labels: apply-on-4-4-x

#7595 feat(openapi): crete an upgrader that transitions api.categories from…
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/converter/ApiConverter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiV4CategoriesUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/UpgraderOrder.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/mapper/ApiMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/converter/ApiConverterTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiV4CategoriesUpgraderTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/mapper/ApiMapperTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-services/gravitee-apim-rest-api-services-dynamic-properties/src/test/java/io/gravitee/rest/api/services/dynamicproperties/DynamicPropertiesServiceTest.java
Labels: apply-on-master

#7633 test: update API analytics import in e2e tests
  gravitee-apim-e2e/api-test/src/apis/logging/mapi-v2/search-api-v4-connection-and-message-logs.spec.ts
  gravitee-apim-e2e/api-test/src/apis/logging/mapi-v2/search-api-v4-connection-logs.spec.ts
Labels: apply-on-master

#7638 chore: bump bridge version
  pom.xml
Labels: apply-on-master

#7645 Apim 4851 add null check to api categories upgrader
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiV4CategoriesUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiV4CategoriesUpgraderTest.java
Labels: apply-on-master
