Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-06, with the labels that each got.

#7646 chore: bump bridge version to 5.0.0-alpha3
  pom.xml
Labels: apply-on-master

#7659 fix(gateway): pause the WS endpoint request when upgrading
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/main/java/io/gravitee/plugin/endpoint/http/proxy/connector/WebSocketConnector.java
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7673 Fix bridge e2e tests
  pom.xml
Labels: apply-on-master

#7672 fix(cockpit-service): fix checking context-path
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/ApiServiceCockpitImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/services/ApiServiceCockpitImplTest.java
Labels: apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#7680 fix(jdbc): adapt liquibase environmentId script by dbms
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_0/05_add_environment_id.yml
Labels: apply-on-4-4-x

#7669 fix: no fallback needed for additional information configuration
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/spring/InstallationConfiguration.java
Labels: apply-on-master

#7667 fix: use the pathname in the redirect_uri
  gravitee-apim-console-webui/src/auth/auth.service.ts
Labels: apply-on-master, ready_to_test, apply-on-4-4-x

#7691 fix(console): inverse message when category is hidden or shown
  gravitee-apim-console-webui/src/management/settings/categories/categories.component.ts
Labels: apply-on-master

#7670 refactor: add logs for setting defaults roles to a member
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiImportExportServiceImpl.java
Labels: apply-on-4-4-x

#7679 Bump transform protobuf policies to add debug information
  pom.xml
Labels: apply-on-master, apply-on-4-4-x

#7699 fix: upgrade reactor-message and reporter dependences
  pom.xml
Labels: apply-on-master

#7702 Update fetcher plugins for APIM 4.x
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7682 Apim catalog category clean up
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.html
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.scss
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.ts
  gravitee-apim-portal-webui-next/src/components/api-filter/api-filter.component.html
  gravitee-apim-portal-webui-next/src/components/api-filter/api-filter.component.ts
  gravitee-apim-portal-webui-next/src/components/search-bar/search-bar.component.scss
Labels: apply-on-master

#7711 fix(import): endpoint config inherit by default
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIConverter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/swagger/converter/api/OAIToAPIConverterTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7701 fix: make sync process sequential
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/DefaultSyncManager.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/repository/DefaultSyncManagerTest.java
Labels: apply-on-master

#7567 fix(mapi): suppress html comments to prevent XSS attack
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/sanitizer/HtmlSanitizer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/sanitizer/HtmlSanitizerTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-4-x

#7724 fix: update v2 kubernetes export documentation link
  gravitee-apim-console-webui/src/management/api/general-info/api-general-info-export-v2-dialog/api-general-info-export-v2-dialog.component.html
  gravitee-apim-console-webui/src/management/api/general-info/api-general-info-export-v4-dialog/api-general-info-export-v4-dialog.component.html
Labels: apply-on-4-4-x

#7732 Reduce bundle size
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7743 Fix environment documentation edition
  gravitee-apim-console-webui/src/components/documentation/documentation-management.component.ts
  gravitee-apim-console-webui/src/components/documentation/edit-page.component.ts
Labels: apply-on-master, apply-on-4-4-x

#7753 docs: revert CHANGELOG.md
  helm/CHANGELOG.md
Labels: apply-on-master

#7731 feat(rest-api): allow to exchange token by QueryParam or POST body
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/model/ExchangePayloadEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
Labels: apply-on-master, ready_to_test

#7741 feat(service): User can enable the new portal from environment setting
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/PortalNext.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/portal-openapi.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapperTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/expectedPortalConfiguration.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/portalSettingsEntity.json
Labels: apply-on-master

#7764 fix(portal-next): show error message for api documentation
  gravitee-apim-portal-webui-next/src/app/api-details/api-tab-documentation/api-tab-documentation.component.html
Labels: apply-on-master

#7761 Update the list of http status code in log filter
  gravitee-apim-console-webui/src/components/logs/logs-filters.controller.ts
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7749 feat(federation): let federation plugin choose if a plan should be manual or auto validated
  gravitee-apim-console-webui/src/management/api/subscriptions/components/dialogs/creation/api-portal-subscription-creation-dialog.component.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/creation/application-subscription-creation-dialog.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/creation/application-subscription-creation-dialog.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/model/IntegrationApi.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/use_case/IngestIntegrationApisUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/integration/use_case/IngestIntegrationApisUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/integration/IntegrationAgentImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ConfigServiceTestNew.java
  pom.xml
Labels: apply-on-4-4-x

#7730 Console: improve use of gio-form-file-picker & fix some behaviour with gio-layout
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/src/management/api/general-info/api-general-info.component.html
  gravitee-apim-console-webui/src/management/api/general-info/api-general-info.component.scss
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.html
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.scss
  gravitee-apim-console-webui/src/management/settings/categories/category/category.component.html
  gravitee-apim-console-webui/src/management/settings/categories/category/category.component.scss
  gravitee-apim-console-webui/src/scss/gio-layout.scss
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-master

#7787 fix(console): make entrypoint read-only for GKO apis
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/api-entrypoints-v4-general.component.html
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/api-entrypoints-v4-general.component.ts
Labels: apply-on-4-4-x

#7762 fix: override queryParams when routing to logs
  gravitee-apim-console-webui/src/management/application/details/analytics/application-analytics.controller.ts
Labels: apply-on-master, ready_to_test, apply-on-4-4-x

#7794 feat(settings): make PUSH plans available by default for new installa…
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
Labels: apply-on-master

#7789 fix(portal): force angular sync when redoc is loaded
  gravitee-apim-portal-webui/package.json
  gravitee-apim-portal-webui/src/app/components/gv-documentation/gv-documentation.component.ts
  gravitee-apim-portal-webui/src/app/components/gv-page-redoc/gv-page-redoc.component.ts
Labels: apply-on-4-0-x, apply-on-master, ready_to_test, apply-on-4-1-x, apply-on-4-3-x, apply-on-4-4-x

#6910 fix: http redirection to https
  helm/CHANGELOG.md
  helm/tests/gateway/ingress_annotations_test.yaml
  helm/values.yaml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7818 fix(console): organisation user token - best effort to find envId if not defined with global constants
  gravitee-apim-console-webui/src/organization/configuration/user/detail/tokens/org-settings-user-generate-token.component.ts
Labels: apply-on-master, apply-on-4-4-x

#7769 fix(portal): do not render markdown if description does not exist
  gravitee-apim-portal-webui/src/app/pipes/markdown-description.pipe.ts
Labels: apply-on-master, ready_to_test, apply-on-4-4-x

#7837 avoid endpoint connectors icons to be cropped in api V4 creation flow
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/api-creation-steps-common.component.scss
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/step-3-endpoints/step-3-endpoints-1-list.component.html
Labels: apply-on-master, apply-on-4-4-x

#7841 feat: start integration controller as soon as possible
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/initializer/InitializerOrder.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/initializer/IntegrationControllerInitializerTest.java
Labels: apply-on-master

#7838 docs(helm): fill missing chart changelog
  helm/Chart.yaml
Labels: apply-on-4-1-x

#7785 add azure service bus plugin in dev distribution
  gravitee-apim-distribution/pom.xml
  pom.xml
Labels: apply-on-master, ready_to_test

#7853 feat(federation): banner message update
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.html
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.spec.ts
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.ts
  gravitee-apim-console-webui/src/services-ngx/integrations.service.ts
Labels: apply-on-master

#7859 fix(repository): remove limit keyword for mssql compatibility
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiCategoryOrderRepository.java
Labels: apply-on-master

#7844 fix: avoid npe on autofetch for pages managed by the operator
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/ApiStateDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/use_case/ImportCRDUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/api/ApiStateDomainServiceLegacyWrapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/documentation/PageSourceDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/ImportCRDUseCaseTest.java
Labels: apply-on-4-4-x

#7797 WIP: Apim 5354 user can redirect to new portal
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalRedirectResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/auth/ConsoleAuthenticationResource.java
Labels: apply-on-master

#7696 refactor: use configmap instead deployment for cloud configuration
  helm/templates/api/api-configmap.yaml
  helm/templates/api/api-deployment.yaml
  helm/tests/api/configmap_cloud_test.yaml
  helm/tests/api/deployment_cloud_test.yaml
  helm/values.yaml
Labels: apply-on-master

#7855 fix(helm): enable federation by default
  helm/templates/api/api-configmap.yaml
  helm/templates/api/api-deployment.yaml
  helm/templates/api/api-ingress-federation-controller.yaml
  helm/templates/api/api-service.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/api/ingress_federationcontroller_test.yaml
  helm/tests/api/service_integrationcontroller_test.yaml
  helm/tests/api/service_test.yaml
  helm/values.yaml
Labels: apply-on-master

#7864 fix(federation): fix update categories of APIs
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/CategoryDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/ValidateFederatedApiDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/use_case/UpdateFederatedApiUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/api/CategoryDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/UpdateFederatedApiUseCaseTest.java
Labels: apply-on-master

#7880 fix: allow to configure keepalive timeout in UI for V2 APIs
  gravitee-apim-console-webui/src/entities/management-api-v2/api/v2/httpClientOptions.ts
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/components/endpoint-http-config/endpoint-http-config.component.html
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/components/endpoint-http-config/endpoint-http-config.component.spec.ts
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/components/endpoint-http-config/endpoint-http-config.component.ts
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/components/endpoint-http-config/endpoint-http-config.harness.ts
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/groups/edit/api-proxy-group-edit.component.spec.ts
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/groups/endpoint/edit/api-proxy-group-endpoint-edit.component.spec.ts
Labels: apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#7888 fix(console): recreate configuration tab whenever httpConfig form group has changed
  gravitee-apim-console-webui/src/management/api/endpoints/components/endpoint-http-config/endpoint-http-config.component.spec.ts
  gravitee-apim-console-webui/src/management/api/endpoints/components/endpoint-http-config/endpoint-http-config.component.ts
Labels: apply-on-4-0-x, apply-on-master, ready_to_test, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-4-x

#7887 chore: bump gravitee-node version
  pom.xml
Labels: apply-on-master

#7695 fix(upgrader): category id is kept when upgrading v4 categories
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiV4CategoriesUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiV4CategoriesUpgraderTest.java
Labels: apply-on-master

#7901 chore(deps): update gravitee-integration-api
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/model/IntegrationApi.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/use_case/IngestIntegrationApisUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/integration/use_case/IngestIntegrationApisUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/integration/IntegrationAgentImplTest.java
  pom.xml
Labels: apply-on-master

#7903 chore: bump gravitee-parent
  pom.xml
Labels: apply-on-master

#7917 chore: bump kafka endpoint
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7916 chore: bump webhook entrypoint
  pom.xml
Labels: apply-on-4-2-x, apply-on-4-3-x

#7927 chore: bump webhook entrypoint
  pom.xml
Labels: apply-on-master

#7925 fix(console): disable create app when one already pending
  gravitee-apim-console-webui/src/management/application/creation/steps/application-creation-step4.html
  gravitee-apim-console-webui/src/management/application/creation/steps/application-creation.controller.ts
Labels: apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x

#7748 feat: apply bridge client changes to helm chart
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
  helm/.gitignore
  helm/CHANGELOG.md
  helm/templates/api/api-configmap.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/api/configmap_bridge_test.yaml
  helm/tests/api/configmap_email_test.yaml
  helm/tests/api/configmap_metrics_test.yaml
  helm/tests/api/configmap_mongodb_test.yaml
  helm/tests/api/configmap_services_test.yaml
  helm/tests/api/configmap_test.yaml
  helm/tests/gateway/configmap_bridge_test.yaml
  helm/tests/gateway/configmap_http_repo_test.yaml
  helm/tests/gateway/configmap_metrics_test.yaml
  helm/tests/gateway/configmap_redis_test.yaml
  helm/tests/gateway/configmap_ssl_test.yaml
  helm/tests/gateway/configmap_test.yaml
  helm/tests/gateway/configmap_tracing_test.yaml
  helm/values.yaml
Labels: apply-on-master, ready_to_test

#7940 fix: change wording on API v2 creation
  gravitee-apim-console-webui/src/management/api/creation-get-started/api-creation-get-started.component.html
Labels: apply-on-master

#7942 fix(console): change import openAPI wording
  gravitee-apim-console-webui/src/management/api/import-v4/api-import-v4.component.html
Labels: apply-on-master

#7945 fix: fix NPE happening when updating index after deleting federated api
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/search/model/IndexableApi.java
Labels: apply-on-master

#7902 Apim 5403 fix category management
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/ApiCategoryOrderRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiCategoryOrderRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/test/java/io/gravitee/repository/jdbc/JdbcTestRepositoryInitializer.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoApiCategoryOrderRepository.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/AbstractManagementRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/ApiCategoryOrderRepositoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/CategoryDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/ValidateFederatedApiDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/use_case/UpdateFederatedApiUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/membership/domain_service/ApiPrimaryOwnerDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/ApiAdapterDecorator.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/api/CategoryDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiSearchServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/mapper/ApiMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/mapper/GenericApiMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/UpdateCategoryApiDomainServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/domain_service/ValidateFederatedApiDomainServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/UpdateDynamicPropertiesUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/UpdateFederatedApiUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/integration/use_case/IngestIntegrationApisUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiCategoryServiceImplTest.java
Labels: apply-on-master

#7939 Apim 5136 - Filtered api: empty message
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.html
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.spec.ts
Labels: apply-on-master

#7896 chore: Add OpenTelemetry tracer to the final bundle
  gravitee-apim-distribution/pom.xml
  gravitee-apim-integration-tests/pom.xml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_tracing_test.yaml
  pom.xml
Labels: apply-on-master

#7958 fix: don't use the router to navigate
  gravitee-apim-portal-webui-next/src/guards/redirect.guard.spec.ts
  gravitee-apim-portal-webui-next/src/guards/redirect.guard.ts
Labels: apply-on-master

#7964 fix: bump kafka endpoint
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7960 fix: do not override sync delay with default value
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  helm/README.md
  helm/tests/gateway/configmap_sync_test.yaml
  helm/values.yaml
Labels: apply-on-master

#7976 fix: properly generate license flowable
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/fetcher/LicenseFetcher.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/repository/fetcher/LicenseFetcherTest.java
Labels: apply-on-master

#7926 Apim 4231 - Subscribe to api
  gravitee-apim-portal-webui-next/src/app/api-details/api-details.component.html
  gravitee-apim-portal-webui-next/src/app/api-details/api-details.component.ts
  gravitee-apim-portal-webui-next/src/app/api-details/api-tab-subscriptions/subscriptions-details/subscriptions-details.component.ts
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-checkout/subscribe-to-api-checkout.component.html
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-checkout/subscribe-to-api-checkout.component.scss
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-checkout/subscribe-to-api-checkout.component.ts
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-choose-application/subscribe-to-api-choose-application.component.html
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-choose-application/subscribe-to-api-choose-application.component.scss
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-choose-application/subscribe-to-api-choose-application.component.ts
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-choose-plan/subscribe-to-api-choose-plan.component.html
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-choose-plan/subscribe-to-api-choose-plan.component.scss
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-choose-plan/subscribe-to-api-choose-plan.component.ts
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api.component.html
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api.component.scss
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api.component.ts
  gravitee-apim-portal-webui-next/src/app/app.routes.ts
  gravitee-apim-portal-webui-next/src/components/subscribe/plan-card/plan-card.component.html
  gravitee-apim-portal-webui-next/src/components/subscribe/plan-card/plan-card.component.scss
  gravitee-apim-portal-webui-next/src/components/subscribe/plan-card/plan-card.component.ts
  gravitee-apim-portal-webui-next/src/entities/api/api.fixtures.ts
  gravitee-apim-portal-webui-next/src/entities/api/api.ts
  gravitee-apim-portal-webui-next/src/pipe/time-unit.pipe.spec.ts
  gravitee-apim-portal-webui-next/src/pipe/time-unit.pipe.ts
Labels: apply-on-master, ready_to_test

#7979 chore: update node version (needed for tracing otel feature)
  pom.xml
Labels: apply-on-master

#7981 Refactor for supporting RO filesystem
  gravitee-apim-console-webui/docker/Dockerfile
  gravitee-apim-console-webui/docker/Dockerfile-from-download
  gravitee-apim-console-webui/docker/config/default.conf
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/Dockerfile-from-download
  gravitee-apim-portal-webui/docker/config/default.conf
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7985 Refactor for supporting RO filesystem - 4.4.x
  gravitee-apim-console-webui/docker/Dockerfile
  gravitee-apim-console-webui/docker/Dockerfile-from-download
  gravitee-apim-console-webui/docker/config/default.conf
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/Dockerfile-from-download
  gravitee-apim-portal-webui/docker/config/default.conf
Labels: apply-on-master

#7962 feat(federation): when federation is activated, use cluster mode
  helm/templates/api/api-configmap.yaml
  helm/templates/api/api-deployment.yaml
  helm/templates/api/api-rbac.yaml
  helm/tests/api/deployment_cloud_test.yaml
  helm/tests/api/deployment_cockpit_test.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/api/external_configuration.yaml
Labels: apply-on-master

#7995 chore(deps): bump gravitee-integration-api
  pom.xml
Labels: apply-on-master

#7994 feat(federation): when federation is activated, use cluster mode
  helm/templates/api/api-configmap.yaml
  helm/templates/api/api-deployment.yaml
  helm/templates/api/api-rbac.yaml
  helm/tests/api/configmap_federation_test.yaml
  helm/tests/api/deployment_cloud_test.yaml
  helm/tests/api/deployment_cockpit_test.yaml
  helm/tests/api/deployment_federation_test.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/api/external_configuration.yaml
  helm/values.yaml
Labels: apply-on-master

#7999 Apim 5515 null categories
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/api/CategoryDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/api/CategoryDomainServiceTest.java
Labels: apply-on-master

#8004 fix(portal-next): Apim 4231 - Subscribe to api
  gravitee-apim-portal-webui-next/src/app/api-details/api-details.component.html
  gravitee-apim-portal-webui-next/src/app/api-details/api-tab-subscriptions/subscriptions-details/subscriptions-details.component.ts
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-checkout/subscribe-to-api-checkout.component.html
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-checkout/subscribe-to-api-checkout.component.ts
  gravitee-apim-portal-webui-next/src/app/api-details/subscribe-to-api/subscribe-to-api-choose-plan/subscribe-to-api-choose-plan.component.ts
  gravitee-apim-portal-webui-next/src/components/subscribe/plan-card/plan-card.component.html
  gravitee-apim-portal-webui-next/src/entities/api/api.fixtures.ts
  gravitee-apim-portal-webui-next/src/entities/api/api.ts
  gravitee-apim-portal-webui-next/src/pipe/time-unit.pipe.ts
Labels: apply-on-master

#8009 chore: bump endpoint kafka to update documentation
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7992 Fix license sync
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/fetcher/LicenseFetcher.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/spring/RepositorySyncConfiguration.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/repository/fetcher/DebugEventFetcherTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/repository/fetcher/LicenseFetcherTest.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/search/LicenseCriteria.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcLicenseRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/license/LicenseMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/LicenseRepositoryTest.java
Labels: apply-on-master

#8003 fix: avoid overflow in api history when json contain long string values
  gravitee-apim-console-webui/src/management/api/audit/history/_apiHistory.scss
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8022 feat(federated): change tech preview message
  gravitee-apim-console-webui/src/services-ngx/integrations.service.ts
Labels: apply-on-master

#8017 chore: bump policy-ipfiltering
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8036 feat(portal): update tech preview message
  gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.html
  gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.ts
Labels: apply-on-master

#7988 chore(ui): add yarn start alias for legacy frontends
  gravitee-apim-portal-webui-next/README.md
  gravitee-apim-portal-webui-next/package.json
Labels: apply-on-master

#7970 fix(user): Check the email format when updating a user
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/UserServiceTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7956 fix(openapi): Better support for polymorphism
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
Labels: apply-on-master

#8046 fix: fix jdbc repository query for subscription
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcSubscriptionRepository.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/ApiKeyRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/SubscriptionRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/apikey-tests/apiKeys.json
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/subscription-tests/plans.json
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/subscription-tests/subscriptions.json
Labels: apply-on-master

#8054 fix: missing size 0 in v4 analytics queries
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchAverageConnectionDurationQueryAdapter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchAverageMessagesPerRequestQueryAdapter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchRequestsCountQueryAdapter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchResponseStatusRangesQueryAdapter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchAverageConnectionDurationQueryAdapterTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchAverageMessagesPerRequestQueryAdapterTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchRequestsCountQueryAdapterTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchResponseStatusRangesQueryAdapterTest.java
Labels: apply-on-master

#8037 fix(doc): Update documentation about EL API Properties or v2 and v4 apis
  gravitee-apim-console-webui/docs/management-api-policy-studio-properties.md
  gravitee-apim-console-webui/docs/management-api-properties.md
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7987 fix(application): Initialize the application with the first applicati…
  gravitee-apim-console-webui/src/management/application/creation/steps/application-creation-step2.controller.ts
  gravitee-apim-console-webui/src/management/application/creation/steps/application-creation-step2.html
  gravitee-apim-console-webui/src/management/application/creation/steps/application-creation.controller.ts
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#8061 fix: fix wrong getter on subscription#environmentId
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/Subscription.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoSubscriptionRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/model/SubscriptionMongo.java
Labels: apply-on-master

#8062 fix: add upgrader to support subscription without api column
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/environment/MissingEnvironmentUpgrader.java
Labels: apply-on-master

#8048 fix(helm): fix upgrader to apply same changes from non upgrader mode
  helm/templates/api/api-upgrader-job.yaml
  helm/tests/api/job_upgrader_test.yaml
Labels: apply-on-master

#7998 fix(serviceaccount): Do not allow to reset password for a service acc…
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/ServiceAccountNotManageableException.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/UserServiceTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8065 chore(plugin): bump policy cloud-events & ratelimit
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#7991 fix(subscription): Update the plan with latest state of a subscription
  gravitee-apim-gateway/gravitee-apim-gateway-security/gravitee-apim-gateway-security-apikey/src/main/java/io/gravitee/gateway/security/apikey/ApiKeyAuthenticationHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-security/gravitee-apim-gateway-security-apikey/src/test/java/io/gravitee/gateway/security/apikey/ApiKeyAuthenticationHandlerTest.java
Labels: apply-on-4-2-x, apply-on-4-3-x

#8053 fix(mongo-upgrader): make idempotent and consider prefix - 4.4.x
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/accessPoints/AccessPointsStatusAndUpdatedUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/common/MongoUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/dashboards/DashboardTypeUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/environment/MissingEnvironmentUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/plan/PlanDefinitionVersionUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/promotions/RemovePromotionAuthorPictureUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/themes/ThemeTypeUpgrader.java
  pom.xml
Labels: apply-on-master

#8085 Apim 5555
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/installation/query_service/InstallationAccessQueryService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/query_service/installation/InstallationAccessQueryServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/query_service/installation/InstallationAccessQueryServiceImplTest.java
Labels: apply-on-master

#8087 fix: use InstallationAccess service to build email url
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UpgraderServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/notification/NotificationParamsBuilder.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/UserServiceTest.java
Labels: apply-on-master

#8007 fix(subscriptions): Improve GET /subscriptions by expanding on api
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiSubscriptionsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8005 fix(logging): Do not manipulate logging headers if header's value is …
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/processor/transaction/TransactionPostProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/processor/transaction/TransactionPostProcessorTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8082 fix(logging): Set the logging condition to v2 apis when v4 mode is en…
  gravitee-apim-console-webui/src/management/api/analytics/logs/configuration/api-logs-configuration.component.html
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/v4/analytics/AnalyticsUtils.java
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/http/logging/LoggingV4EmulationIntegrationTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8100 [4.3.X] fix(console): update properties EL according to api definition version
  gravitee-apim-console-webui/src/management/api/properties/properties/api-properties.component.html
Labels: apply-on-master, apply-on-4-4-x

#8114 fix: add @Lazy on InstallationAccessQueryServiceImpl to avoid circular dependencies
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/query_service/installation/InstallationAccessQueryServiceImpl.java
Labels: apply-on-master

#8029 fix(apis): Add expand flag to get the primaryOwner while retrieving l…
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApisResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/AbstractResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApisResource_GetApisTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl_findAllTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8141 fix: remove endpoint status from v2 endpoint when exporting as a CRD
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/kubernetes/v1alpha1/ApiDefinitionResource.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/test/resources/io/gravitee/definition/model/kubernetes/v1alpha1/api-definition.json
Labels: apply-on-master

#8144 [Portal next] Do not sort categories by name
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.ts
Labels: apply-on-master

#8145 geteway keys error
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8139 fix: update V4 APIs runtime logs settings condition expression langua…
  gravitee-apim-console-webui/src/management/api/runtime-logs-v4/runtime-logs-settings/runtime-logs-message-settings/api-runtime-logs-message-settings.component.html
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8086 fix(group): Do not allow to add members to a new group during group c…
  gravitee-apim-console-webui/src/management/configuration/groups/group/group.component.ts
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8101 fix(api): Do not check context-path for current API
  gravitee-apim-console-webui/src/management/api/component/gio-form-listeners/gio-form-listeners-context-path/gio-form-listeners-context-path.component.ts
  gravitee-apim-console-webui/src/management/api/component/gio-form-listeners/gio-form-listeners-virtual-host/gio-form-listeners-virtual-host.component.ts
  gravitee-apim-console-webui/src/management/api/entrypoints-v4/api-entrypoints-v4-general.component.html
Labels: apply-on-4-1-x

#8164 fix(tokens): Do not use service to retrieve token by value
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/TokensResource.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8137 fix: implement new terms filter to avoid max clause count issues
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/analytics/query/AbstractQuery.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/analytics/query/AbstractQueryBuilder.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/analytics/query/TermsFilter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/analytics/count.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/analytics/dateHistogram.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/analytics/groupBy.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/analytics/stats.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/resources/freemarker/log/log.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/ElasticsearchAnalyticsRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/ElasticsearchLogRepositoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentAnalyticsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformAnalyticsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformLogsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/EnvironmentAnalyticsResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/PlatformLogsResourceNotAdminTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/PlatformLogsResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/analytics/query/AbstractQuery.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AnalyticsServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/LogsServiceImpl.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8136 [ 4.4.x ] Add expand flag to get the primaryOwner while retrieving list of APIs
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApisResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApisResource_GetApisTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/ApiService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl_findAllTest.java
Labels: apply-on-master

#8165 fix(application): Simple form when DCR is disabled
  gravitee-apim-console-webui/src/management/application/creation/steps/application-creation-step2.controller.ts
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x
