Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-03, with the labels that each got.

#6805 chore: bump gravitee-reporter-api version to 1.28.1
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x

#6483 APIM-3989: Angular Migration: Settings > Portal > API Portal Information
  gravitee-apim-console-webui/src/entities/api-portal-headers/api-portal-headers.fixture.ts
  gravitee-apim-console-webui/src/entities/portal/portalSettings.fixture.ts
  gravitee-apim-console-webui/src/entities/portal/portalSettings.ts
  gravitee-apim-console-webui/src/management/settings/api-logging/api-logging.component.spec.ts
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header-edit-dialog/api-portal-header-edit-dialog.component.html
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header-edit-dialog/api-portal-header-edit-dialog.component.scss
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header-edit-dialog/api-portal-header-edit-dialog.component.ts
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header-edit-dialog/api-portal-header-edit-dialog.harness.ts
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header.component.html
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header.component.scss
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header.component.spec.ts
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header.component.ts
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header.harness..ts
  gravitee-apim-console-webui/src/management/settings/api-portal-header/migrated/api-portal-header.module.ts
  gravitee-apim-console-webui/src/management/settings/settings-routing.module.ts
  gravitee-apim-console-webui/src/management/settings/settings.module.ts
  gravitee-apim-console-webui/src/services-ngx/environment-api-headers.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/environment-api-headers.service.ts
  gravitee-apim-console-webui/src/services-ngx/portal-settings.service.ts
Labels: ready_to_test

#6830 chore: update gravitee node version to 4.8.3
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#6840 Rest-api: fix "Deleted users still appear in query" on multi tenancy env
  gravitee-apim-console-webui/src/components/user-autocomplete/user-autocomplete.html
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ScheduledCommandsRefresherServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ScheduledCommandsRefresherServiceImplTest.java
Labels: apply-on-master, apply-on-4.3.x

#6841 feat: provide (m)tls support in tcp reporter
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x, apply-on-4.3.x

#6833 fix(jdbc-condition-extended): update the flow_steps.condition column to 1024 chars
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v3_20_31/schema.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4.3.x

#6826 fix(hc-improvement): await for HC call to finish before calling another one
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/http/HttpEndpointRuleHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleCronHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/test/java/io/gravitee/gateway/services/healthcheck/http/AbstractManagedEndpointRuleHandlerTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4.3.x

#6861 test: fix flaky metrics integration test
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/messages/logging/MetricsIntegrationTest.java
Labels: apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x, apply-on-4.3.x

#6880 Apim 4185 fix use openapi in doc syntax
  gravitee-apim-portal-webui/src/app/services/markdown.service.spec.ts
  gravitee-apim-portal-webui/src/app/services/markdown.service.ts
Labels: apply-on-master

#6881 fix(portal): match site.title to how console references portal
  gravitee-apim-portal-webui/src/assets/i18n/cs.json
  gravitee-apim-portal-webui/src/assets/i18n/en.json
  gravitee-apim-portal-webui/src/assets/i18n/fr.json
Labels: apply-on-master

#6895 Cj 1242 fix register org license apim
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/license/domain_service/LicenseDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/license/LicenseCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/OrganizationCommandHandler.java
Labels: apply-on-master

#6905 rename cors tab
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.spec.ts
  gravitee-apim-console-webui/src/management/api/api-navigation/api-v4-menu.service.ts
Labels: apply-on-master

#6911 fix: display api key mode choice when subscribing by app
  gravitee-apim-console-webui/src/management/application/details/subscribe/application-subscribe.controller.ts
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6835 Console 4.2.x : Try to fix "Console Menu doesn't work with latency"
  gravitee-apim-console-webui/src/components/documentation/edit-page.component.ajs.ts
  gravitee-apim-console-webui/src/management/api/apis.module.ts
  gravitee-apim-console-webui/src/management/api/apis.route.ts
  gravitee-apim-console-webui/src/management/api/general/plans/list/api-general-plan-list.component.ts
  gravitee-apim-console-webui/src/management/management.run.ts
Labels: ready_to_test

#6909 refactor(rest-api-flow): Added flow id to the v2 management model
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/flow/Flow.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/FlowRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcFlowRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoFlowRepository.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/FlowRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/FlowV4RepositoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/fixtures/FlowFixtures.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/FlowServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/mapper/FlowMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/FlowServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/mapper/FlowMapperTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-test-fixtures/src/main/java/fixtures/FlowModelFixtures.java
Labels: apply-on-4-1-x

#6918 refactor(rest-api-flow): Added flow id to the v2 management model version 4.2
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/flow/Flow.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/FlowRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcFlowRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoFlowRepository.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/FlowRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/FlowV4RepositoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/flow/crud_service/FlowCrudService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/FlowAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/flow/FlowCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/FlowService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/FlowServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/PlanServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/mapper/FlowMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/FlowCrudServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/adapter/FlowAdapterTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/crud_service/flow/FlowCrudServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl_findAllTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/FlowServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/PlanService_CreateOrUpdateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/PlanService_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/PlanService_DeleteTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/PlanService_UpdateTest.java
Labels: apply-on-master, apply-on-4-3-x

#6945 feat(service): only create org license if license non-null
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/license/domain_service/LicenseDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/license/domain_service/LicenseDomainServiceTest.java
Labels: apply-on-master

#6950 fix(console): update ui-particles to fix form-json-schema issue
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/src/management/api/component/plan/api-plan-form.component.spec.ts
Labels: ready_to_test

#6949 fix(repository): set default value for licenses updated at
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_3_0/schema.yml
Labels: apply-on-master

#6951 Console: update ui-particles to fix form-json-schema issue
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/src/management/api/component/plan/api-plan-form.component.spec.ts
  gravitee-apim-console-webui/src/management/api/portal/subscriptions/list/api-portal-subscription-list.component.spec.ts
  gravitee-apim-console-webui/src/shared/components/gio-license-banner/gio-license-banner.module.spec.ts
Labels: apply-on-4-1-x, apply-on-4-2-x

#6921 fix(gateway-hc): handle failing scenarios to always start a new timer
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleCronHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/test/java/io/gravitee/gateway/services/healthcheck/http/AbstractManagedEndpointRuleHandlerTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#6962 Console: ask to create shared api key if fist subscription is in pending
  gravitee-apim-console-webui/src/management/application/applications.route.ts
  gravitee-apim-console-webui/src/management/application/details/subscribe/application-subscribe.controller.ts
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#6920 fix: additional check for url to validate dangerous characters
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/sanitizer/UrlSanitizerUtils.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/sanitizer/UrlSanitizerUtilsTest.java
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#6990 fix: use the envId from route in dashboards component
  gravitee-apim-console-webui/src/management/settings/analytics/dashboard/settings-analytics-dashboard.components.ajs.ts
Labels: apply-on-master

#6894 Console - Settings -> Settings - part1
  gravitee-apim-console-webui/src/entities/portal/portalSettings.fixture.ts
  gravitee-apim-console-webui/src/entities/portal/portalSettings.ts
  gravitee-apim-console-webui/src/management/settings/portal-ng/portal-ng.component.html
  gravitee-apim-console-webui/src/management/settings/portal-ng/portal-ng.component.scss
  gravitee-apim-console-webui/src/management/settings/portal-ng/portal-ng.component.spec.ts
  gravitee-apim-console-webui/src/management/settings/portal-ng/portal-ng.component.ts
  gravitee-apim-console-webui/src/management/settings/portal-ng/portal-ng.module.ts
  gravitee-apim-console-webui/src/management/settings/settings-routing.module.ts
  gravitee-apim-console-webui/src/management/settings/settings.module.ts
Labels: ready_to_test

#6993 fix(console): rename envId to envHrid to avoid any confusion
  gravitee-apim-console-webui/src/app-routing.module.ts
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.ts
  gravitee-apim-console-webui/src/management/application/application-navigation/application-navigation.component.ts
  gravitee-apim-console-webui/src/management/environment.guard.ts
  gravitee-apim-console-webui/src/management/settings/identityProviders/identity-providers.component.ajs.ts
  gravitee-apim-console-webui/src/user/tasks/tasks.component.ts
Labels: apply-on-master

#6963 Application general delete option bug v4.3
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.html
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.scss
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.ts
  gravitee-apim-console-webui/src/services-ngx/application.service.ts
Labels: apply-on-master, ready_to_test, apply-on-4-3-x

#6961 fix: add secret converter for all IdP plugin
  gravitee-apim-rest-api/gravitee-apim-rest-api-idp/gravitee-apim-rest-api-idp-core/src/main/java/io/gravitee/rest/api/idp/core/plugin/impl/IdentityProviderManagerImpl.java
Labels: apply-on-master, apply-on-4-2-x

#7006 fix: handle json mapping exception
  gravitee-apim-e2e/api-test/src/applications/applications.spec.ts
  gravitee-apim-e2e/api-test/src/portal/portal-applications.spec.ts
  gravitee-apim-e2e/lib/fixtures/management/ApplicationsFaker.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/provider/JsonMappingExceptionMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GraviteeManagementApplication.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/provider/JsonMappingExceptionMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/GraviteePortalApplication.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7020 fix(import): Primary Owner should be always added to the API group on import update
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_UpdateTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7035 fix: add columnDataType in not null constraint
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_0_20/schema-dashboards.yml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7037 fix(console): version history location change
  gravitee-apim-console-webui/src/management/api/api-navigation/api-v4-menu.service.ts
Labels: apply-on-master, ready_to_test

#7044 fix: change dashboard type upgrader to work with document db
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/dashboards/DashboardTypeUpgrader.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#7051 Bump dependencies
  pom.xml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7029 fix(console): add nginx server redirect on 404 to `/`
  gravitee-apim-console-webui/docker/config/default.conf
Labels: apply-on-4-0-x, apply-on-master, ready_to_test, apply-on-4-1-x, apply-on-4-2-x

#7065 Console - Settings -> Settings - part2
  gravitee-apim-console-webui/src/management/settings/settings-routing.module.ts
Labels: ready_to_test

#7067 fix: allow to find parameters without environment
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ParameterServiceImpl.java
Labels: apply-on-master

#7024 fix(console): snack bar design fix
  gravitee-apim-console-webui/src/scss/gio-global-style.scss
Labels: apply-on-master, ready_to_test

#7066 fix(rest-api): improve openapi-apis by adding required on discriminator property
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-3-x

#7074 fix: disable jersey wadl by default
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/bin/gravitee
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/bin/gravitee.bat
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#7104 fix: bump gravitee-apim-repository-bridge
  pom.xml
Labels: apply-on-master
