Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-11, with the labels that each got.

#9781 fix(mapi): handle client_certificate not exists on converter
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
Labels: apply-on-master

#9792 chore: update data-cache-policy plugin version [skip ci]
  pom.xml
Labels: apply-on-master

#9807 fix(deps): bump gravitee-reporter-elasticsearch to 5.5.0
  pom.xml
Labels: apply-on-master

#9811 fix(deps): bump gravitee-reporter-elasticsearch to 5.3.3
  pom.xml
Labels: apply-on-4-3-x, apply-on-4-4-x

#9820 chore: bump jwt policy [skip ci]
  pom.xml
Labels: apply-on-master

#9827 fix: return a noop tracer to avoid NPE issue
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/AbstractBaseExecutionContext.java
Labels: apply-on-master

#9231 Align vert.x versions with Gravitee-bom
  pom.xml
Labels: apply-on-master

#9842 chore: bump data-cache policy [skip ci]
  pom.xml
Labels: apply-on-master

#9868 chore(deps): bump endpoint rabbitmq version to 1.3.1
  pom.xml
Labels: apply-on-4-5-x, apply-on-4-3-x, apply-on-4-4-x

#9824 APIM-7318 fix: hide create bar on success
  gravitee-apim-console-webui/src/management/api/endpoints/groups/edit/api-proxy-group-edit.component.html
  gravitee-apim-console-webui/src/management/api/endpoints/groups/edit/api-proxy-group-edit.component.ts
Labels: apply-on-4-5-x, apply-on-master, ready_to_test, apply-on-4-4-x, apply-on-4-6-x

#9902 fix: allow edit on github for gko managed pages
  gravitee-apim-console-webui/src/components/documentation/edit-page.html
Labels: apply-on-master

#9927 fix: disable adding a page for v4 APIs managed by GKO
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-list-navigation-header/api-documentation-v4-list-navigation-header.component.html
Labels: apply-on-master, apply-on-4-6-x

#9918 fix: not create any empty ASIDE folder on API creation using GKO
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorService_CreateWithDefinitionTest.java
Labels: apply-on-4-5-x

#9939 fix: bump gravitee node
  pom.xml
Labels: ready_to_test

#9961 fix(mapi): support x-forwarded-port header
  gravitee-apim-rest-api/gravitee-apim-rest-api-rest/src/main/java/io/gravitee/rest/api/rest/filter/UriBuilderRequestFilter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-rest/src/test/java/io/gravitee/rest/api/rest/filter/PermissionsFilterTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-rest/src/test/java/io/gravitee/rest/api/rest/filter/UriBuilderRequestFilterTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#9971 fix(mapi): support x-forwarded-host header with multiple hosts chain
  gravitee-apim-rest-api/gravitee-apim-rest-api-rest/src/main/java/io/gravitee/rest/api/rest/filter/UriBuilderRequestFilter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-rest/src/test/java/io/gravitee/rest/api/rest/filter/UriBuilderRequestFilterTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#9977 fix: properly handle new interfaces for qos support
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/AbstractConnectorPluginService.java
Labels: run-e2e-tests
