Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-10, with the labels that each got.

#9350 helm: fix changelog
  .circleci/ci/src/jobs/job-release-commit-and-prepare-next-version.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
  helm/Chart.yaml
  helm/README.adoc
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9267 chore: use java image with latest version of alpine
  gravitee-apim-gateway/docker/Dockerfile
  gravitee-apim-gateway/docker/Dockerfile-from-download
  gravitee-apim-rest-api/docker/Dockerfile
  gravitee-apim-rest-api/docker/Dockerfile-from-download
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9352 fix: use custom logo in footer
  gravitee-apim-portal-webui-next/src/app/app.component.html
  gravitee-apim-portal-webui-next/src/components/footer/footer.component.html
  gravitee-apim-portal-webui-next/src/components/footer/footer.component.ts
Labels: apply-on-master

#9297 fix(distributed-sync): properly parse to v2 api handler
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/mapper/ApiMapper.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/distributed/mapper/ApiMapperTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9364 fix(api): ensure proper content_length header size when sending webhook notification
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/notifiers/impl/WebNotifierServiceImpl.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#9380 fix: handle annotations for non nginx ingress
  helm/Chart.yaml
  helm/templates/_helpers.tpl
  helm/tests/api/ingress_management_test.yaml
Labels: apply-on-4-5-x, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9377 fix: handle single header value with comma separated list
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/processor/error/ExecutionFailureMessageHelper.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/processor/error/SimpleFailureProcessorTest.java
Labels: apply-on-4-5-x, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9398 fix: add missing service account for portal and ui
  helm/Chart.yaml
  helm/templates/portal/portal-deployment.yaml
  helm/templates/ui/ui-deployment.yaml
  helm/tests/portal/deployment_test.yaml
  helm/tests/ui/deployment_test.yaml
  helm/values.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9381 fix: solve the issue with github fetcher
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApisResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/documentation/domain_service/ValidatePagesDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/documentation/ValidatePageSourceDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/ImportApiCRDUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/documentation/ValidatePageSourceDomainServiceImplTest.java
Labels: apply-on-4-5-x

#9405 fix: update token permissions to 2500
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/permissions/OrganizationPermission.java
Labels: apply-on-4-2-x

#9406 fix: unlock fetch all button in read only mode
  gravitee-apim-console-webui/src/components/documentation/documentation-management.html
Labels: apply-on-4-5-x

#9414 fix: remove related api flows when delete environment
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteEnvironmentCommandHandler.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteEnvironmentCommandHandlerTest.java
Labels: apply-on-4-5-x, apply-on-master

#9345 fix: undeploy SPG when deleted
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/environment/SharedPolicyGroupResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/shared_policy_group/use_case/DeleteSharedPolicyGroupUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/shared_policy_group/use_case/DeleteSharedPolicyGroupUseCaseTest.java
Labels: apply-on-master

#9292 Console - make default color and custom color for idb work correctly
  gravitee-apim-console-webui/src/assets/logo_graviteeio_am-idp.svg
  gravitee-apim-console-webui/src/auth/login/login.component.html
  gravitee-apim-console-webui/src/auth/login/login.component.scss
  gravitee-apim-console-webui/src/auth/login/login.component.ts
  gravitee-apim-console-webui/src/management/home/components/gio-quick-time-range/gio-quick-time-range.component.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x

#9417 fix: only retrieve fresh GATEWAY_STARTED events (under 5minutes)
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiEventsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/EventQuery.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EventServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/InstanceServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiLoggingConditionUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_StartTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_StopTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/InstanceServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImplTest.java
Labels: apply-on-4-5-x, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9432 fix(integrations): add margin to integration configuration danger zone
  gravitee-apim-console-webui/src/management/integrations/integration-configuration/general/integration-general-configuration.component.scss
Labels: apply-on-4-5-x

#9438 chore: use java image with version 3.18 of alpine
  gravitee-apim-gateway/docker/Dockerfile
  gravitee-apim-gateway/docker/Dockerfile-from-download
  gravitee-apim-rest-api/docker/Dockerfile
  gravitee-apim-rest-api/docker/Dockerfile-from-download
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9452 Apim 6425 refresh settings
  gravitee-apim-portal-webui-next/src/app/app.routes.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-settings/application-tab-settings-edit/application-tab-settings-edit.component.html
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-settings/application-tab-settings-edit/application-tab-settings-edit.component.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-settings/application-tab-settings-read/application-tab-settings-read.component.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-settings/application-tab-settings.component.delete.spec.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-settings/application-tab-settings.component.html
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-settings/application-tab-settings.component.readonly.spec.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-settings/application-tab-settings.component.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-settings/application-tab-settings.component.update.spec.ts
  gravitee-apim-portal-webui-next/src/app/applications/application/application.component.ts
Labels: apply-on-master

#9430 chore: bump groovy policy
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9453 fix: set installation id when publishing Alert Event
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactive/reactor/processor/alert/AlertProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/alert/AlertProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/test/java/io/gravitee/gateway/reactive/reactor/processor/alert/AlertProcessorTest.java
Labels: apply-on-master

#9466 chore: bump policy-generate-jwt
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#9467 chore: bump node
  pom.xml
Labels: apply-on-4-5-x, apply-on-master

#9465 fix: ensure token used by Federation Agent can manipulate integration
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/main/java/io/gravitee/integration/controller/command/IntegrationCommandContext.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/main/java/io/gravitee/integration/controller/command/hello/HelloCommandHandler.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/main/java/io/gravitee/integration/controller/websocket/auth/IntegrationWebsocketControllerAuthentication.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/test/java/io/gravitee/integration/controller/command/hello/HelloCommandHandlerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/test/java/io/gravitee/integration/controller/websocket/auth/IntegrationWebsocketControllerAuthenticationTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/use_case/CheckIntegrationUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/permission/domain_service/PermissionDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/permission/PermissionDomainServiceLegacyWrapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/common/DefaultRoleEntityDefinition.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PermissionServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/RoleServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/EnvironmentFederationAgentRoleUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/integration/use_case/CheckIntegrationUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/permission/domain_service/PermissionDomainServiceTest.java
Labels: apply-on-master

#9482 fix: remove extra space on plan selection rule
  gravitee-apim-console-webui/src/management/api/component/plan/2-secure-step/plan-edit-secure-step.component.html
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9484 fix: ensure token used by Federation Agent can manipulate integration
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/main/java/io/gravitee/integration/controller/command/IntegrationCommandContext.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/main/java/io/gravitee/integration/controller/command/hello/HelloCommandHandler.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/main/java/io/gravitee/integration/controller/websocket/auth/IntegrationWebsocketControllerAuthentication.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/test/java/io/gravitee/integration/controller/command/hello/HelloCommandHandlerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/src/test/java/io/gravitee/integration/controller/websocket/auth/IntegrationWebsocketControllerAuthenticationTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/use_case/CheckIntegrationUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/permission/domain_service/PermissionDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/permission/PermissionDomainServiceLegacyWrapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/common/DefaultRoleEntityDefinition.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PermissionServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/RoleServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/EnvironmentFederationAgentRoleUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/integration/use_case/CheckIntegrationUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/permission/domain_service/PermissionDomainServiceTest.java
Labels: apply-on-master

#9479 deps: update Gravitee Kubernetes Client
  pom.xml
Labels: apply-on-4-5-x

#9492 fix: resolve inconsistencies in crd pages validation
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/documentation/domain_service/ValidatePagesDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/documentation/ValidatePageSourceDomainServiceImpl.java
Labels: apply-on-master

#9468 fix(console): Display only managed apis on console
  gravitee-apim-console-webui/src/management/api/list/api-list.component.spec.ts
  gravitee-apim-console-webui/src/management/api/list/api-list.component.ts
Labels: apply-on-4-5-x, apply-on-master

#9504 refactor(integrations): refactor integration-status into module
  gravitee-apim-console-webui/src/management/integrations/components/integration-status/integration-status.component.html
  gravitee-apim-console-webui/src/management/integrations/components/integration-status/integration-status.component.ts
  gravitee-apim-console-webui/src/management/integrations/integration-agent/integration-agent.component.html
  gravitee-apim-console-webui/src/management/integrations/integration-agent/integration-agent.module.ts
  gravitee-apim-console-webui/src/management/integrations/integrations.module.ts
Labels: apply-on-4-5-x

#9508 fix: handle DefaultOrganizationAdminRoleInitializer error by getting existing role value
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/RoleServiceImpl.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x

#9362 fix: compare decoded certificate with decoded certificate
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
Labels: apply-on-master

#9513 refactor(integrations): refactor integration-overview into module
  gravitee-apim-console-webui/src/management/integrations/integration-overview/integration-overview.module.ts
  gravitee-apim-console-webui/src/management/integrations/integrations.module.ts
Labels: apply-on-4-5-x

#9512 fix(federation): ingest ensure we have only one homepage
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/PageRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcPageRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/test/java/io/gravitee/repository/jdbc/management/JdbcPageRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryCustom.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/documentation/crud_service/PageCrudService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/documentation/domain_service/HomepageDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/documentation/domain_service/UpdateApiDocumentationDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/integration/use_case/IngestFederatedApisUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/documentation/PageCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/PageCrudServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/integration/use_case/IngestFederatedApisUseCaseTest.java
Labels: apply-on-4-5-x

#9517 fix(helm): bad indentation in bridge client example for gateway
  helm/values.yaml
Labels: apply-on-4-5-x, apply-on-master

#9520 chore(deps): bump rate limit policy to 2.1.3
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9527 fix: manage groups dialog miss proper css class
  gravitee-apim-console-webui/src/management/api/user-group-access/groups/api-general-groups.component.scss
Labels: apply-on-master

#9533 ci: missing backslash
  .circleci/ci/src/jobs/job-release-commit-and-prepare-next-version.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9516 fix: ditionaries upgraders ids
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/EventsLatestUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/EventsLatestUpgraderTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9478 fix(console): Set reference id with execution context environment id whenever permission is Scope Environment
  gravitee-apim-e2e/api-test/src/apis/settings/mapi-v1/notification-setting.spec.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/AbstractResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CategoriesResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/CategoryResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalNotificationSettingsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/quality/QualityRulesResource.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, run-e2e-tests

#9553 update default redis insight port exposed
  docker/quick-setup/redis-rate-limit/docker-compose.yml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#9554 chore: bump gateway-api to 3.9.0-alpha.4
  pom.xml
Labels: run-e2e-tests

#9561 Fix release
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/workflows/workflow-full-release.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9571 chore: fix AE's quick setup
  docker/quick-setup/ee-with-alert-engine/docker-compose.yml
Labels: apply-on-master

#9552 feat: add wildcard option for CORS allowed headers and methods
  gravitee-apim-console-webui/src/management/api/cors/api-cors.component.html
  gravitee-apim-console-webui/src/management/api/cors/api-cors.component.spec.ts
  gravitee-apim-console-webui/src/management/api/cors/api-cors.component.ts
  gravitee-apim-console-webui/src/shared/utils/cors.util.ts
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/cors/CorsPreflightRequestProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/processor/cors/CorsPreflightRequestProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/processor/cors/CorsPreflightRequestProcessorTest.java
Labels: run-e2e-tests

#9590 fix: increase integration provider column length
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_12/00_increase_length_integration_provider_column.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
Labels: apply-on-4-5-x, apply-on-master

#9602 feat: add data-cache policy to dev-bundle
  gravitee-apim-distribution/pom.xml
  pom.xml
Labels: apply-on-master

#9584 fix: opensearch quick setup
  docker/quick-setup/opensearch/docker-compose.yml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#9623 feat: update data cache plugin to full release
  pom.xml
Labels: apply-on-master

#9624 chore(deps): update nginx version test
  gravitee-apim-console-webui/docker/Dockerfile
  gravitee-apim-console-webui/docker/Dockerfile-from-download
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/Dockerfile-from-download
Labels: apply-on-4-5-x, apply-on-master, ready_to_test, apply-on-4-3-x, apply-on-4-4-x

#9628 ci: move helm chart release after docker rpm and nexus steps
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/workflows/workflow-full-release.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#9645 fix: link to Gravitee API Management installation guide
  gravitee-apim-console-webui/src/management/integrations/integrations.component.html
Labels: apply-on-master

#9653 fix(categories): avoid NPE when counting API by category
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/CategoriesResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/CategoryResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/CategoriesResourceNotAuthenticatedTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/CategoriesResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/CategoryResourceNotAuthenticatedTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/CategoryResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/ApiCategoryService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiCategoryServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiCategoryServiceImplTest.java
Labels: apply-on-4-5-x

#9658 Fix several typos in OpenAPI definition related to Integrations
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
Labels: apply-on-master

#9654 fix: add heartbeat values entries in helm charts
  helm/Chart.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_test.yaml
  helm/values.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#9580 docs: send groups when user rollback an API
  gravitee-apim-console-webui/src/management/api/audit/history/apiHistory.controller.ajs.spec.ts
  gravitee-apim-console-webui/src/management/api/audit/history/apiHistory.controller.ajs.ts
  gravitee-apim-console-webui/src/management/management.module.ajs.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#9668 chore: bump data-cache policy [skipCI]
  pom.xml
Labels: apply-on-master

#9677 Alert template filtered by environment during API creation
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AlertServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/AlertServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/AlertService_CreateDefaultsTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#9689 Console: Bump Ui Particles
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-4-5-x, apply-on-master

#9694 fix(helm): add missing haproxy mapping attribute - update chart and changelog
  helm/CHANGELOG.md
  helm/Chart.yaml
Labels: apply-on-4-5-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9701 fix: cypress policy studio
  gravitee-apim-e2e/ui-test/integration/apim/ui/apis/policy-studio/ui-ps-delete-flow.spec.ts
  gravitee-apim-e2e/ui-test/support/PageObjects/Apis/PolicyStudio.ts
Labels: run-e2e-tests

#9679 fix: do not check domain name on serve to be able to use multitenant locally
  gravitee-apim-console-webui/package.json
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x

#9711 ci: fix release pipeline
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/workflows/workflow-full-release.ts
  release/ci-steps/generate-changelog.mjs
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#9722 feat: bump jwt policy to 5.1.0
  pom.xml
Labels: apply-on-master

#9733 fix: sync process should not complete when last attempt reached on on…
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/DefaultSyncManager.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/repository/DefaultSyncManagerTest.java
Labels: apply-on-4-5-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#9754 fix: remove warning when role id exist
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/member/domain_service/ValidateCRDMembersDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/domain_service/ValidateCRDMembersDomainServiceTest.java
Labels: apply-on-4-5-x

#9760 fix: sync process should not fail if api
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/synchronizer/api/SubscriptionAppender.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/appender/MemoryAppender.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/repository/synchronizer/api/SubscriptionAppenderTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-4-x
