Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-01, with the labels that each got.

#6288 fix(helm): backward incompatibility during helm upgrade
  helm/templates/api/api-autoscaler.yaml
  helm/templates/api/api-bridge-ingress.yaml
  helm/templates/api/api-configmap.yaml
  helm/templates/api/api-deployment.yaml
  helm/templates/api/api-ingress-management.yaml
  helm/templates/api/api-ingress-portal.yaml
  helm/templates/api/api-pdb.yaml
  helm/templates/api/api-service.yaml
  helm/templates/api/api-technical-ingress.yaml
  helm/templates/api/api-upgrader-job.yaml
  helm/templates/common/rolebinding.yaml
  helm/templates/common/serviceaccount.yaml
  helm/templates/gateway/gateway-autoscaler.yaml
  helm/templates/gateway/gateway-bridge-ingress.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/templates/gateway/gateway-deployment.yaml
  helm/templates/gateway/gateway-ingress.yaml
  helm/templates/gateway/gateway-pdb.yaml
  helm/templates/gateway/gateway-service.yaml
  helm/templates/gateway/gateway-technical-ingress.yaml
  helm/templates/portal/portal-autoscaler.yaml
  helm/templates/portal/portal-configmap.yaml
  helm/templates/portal/portal-deployment.yaml
  helm/templates/portal/portal-ingress.yaml
  helm/templates/portal/portal-pdb.yaml
  helm/templates/portal/portal-service.yaml
  helm/templates/ui/ui-autoscaler.yaml
  helm/templates/ui/ui-configmap.yaml
  helm/templates/ui/ui-deployment.yaml
  helm/templates/ui/ui-ingress.yaml
  helm/templates/ui/ui-pdb.yaml
  helm/templates/ui/ui-service.yaml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6306 fix: add noop license repository implementation
  gravitee-apim-repository/gravitee-apim-repository-noop/src/main/java/io/gravitee/repository/noop/NoOpManagementRepositoryConfiguration.java
  gravitee-apim-repository/gravitee-apim-repository-noop/src/main/java/io/gravitee/repository/noop/management/NoOpLicenseRepository.java
Labels: apply-on-4-2-x

#6310 feat: add host property to el requests
  pom.xml
Labels: apply-on-4-2-x

#6311 feat: add host property to el requests
  pom.xml
Labels: apply-on-4-1-x

#6316 fix(console): make asciidoctor documentation work again into policy studio
  gravitee-apim-console-webui/angular.json
  gravitee-apim-console-webui/src/index.html
Labels: ready_to_test

#6325 chore: bump node version
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#6332 fix(helm): fill changelog about backward incompatibility during helm upgrade
  helm/CHANGELOG.md
  helm/Chart.yaml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6281 Console - application general migration - eighth part
  gravitee-apim-console-webui/src/management/application/details/user-group-access/application-general-user-group.module.ts
  gravitee-apim-console-webui/src/management/application/details/user-group-access/members/application-general-members.component.html
  gravitee-apim-console-webui/src/management/application/details/user-group-access/transfer-ownership/application-general-transfer-ownership.component.html
  gravitee-apim-console-webui/src/management/application/details/user-group-access/transfer-ownership/application-general-transfer-ownership.component.scss
  gravitee-apim-console-webui/src/management/application/details/user-group-access/transfer-ownership/application-general-transfer-ownership.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/user-group-access/transfer-ownership/application-general-transfer-ownership.component.ts
  gravitee-apim-console-webui/src/services-ngx/application-members.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/application-members.service.ts
Labels: ready_to_test

#6330 feat(helm): Added gateway.services.core.http.ssl.keystore.password
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_test.yaml
  helm/values.yaml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6302 fix: pathmapping must ends with /
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ApiDeserializer.java
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
  gravitee-apim-definition/gravitee-apim-definition-jackson/src/test/resources/io/gravitee/definition/jackson/api-without-wildcard-in-path-mapping.json
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6373 fix: allow '|' in path parameter
  gravitee-apim-gateway/gravitee-apim-gateway-flow/src/main/java/io/gravitee/gateway/flow/condition/evaluation/PathPatterns.java
  gravitee-apim-gateway/gravitee-apim-gateway-flow/src/test/java/io/gravitee/gateway/flow/PathBasedConditionEvaluatorTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-flow/src/test/java/io/gravitee/gateway/jupiter/v4/flow/selection/ChannelSelectorConditionFilterTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-flow/src/test/java/io/gravitee/gateway/jupiter/v4/flow/selection/HttpSelectorConditionFilterTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6379 fix: prevent v2 apis from sending unexpected headers to gRPC backend
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6363 Helm post release
  .circleci/ci/src/jobs/helm/job-release-helm.ts
  .circleci/ci/src/jobs/job-release-commit-and-prepare-next-version.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
  .circleci/ci/src/workflows/workflow-pull-requests.ts
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6387 fix: virtual host double check should be done on subDomainHost
  gravitee-apim-console-webui/src/management/api/component/gio-form-listeners/gio-form-listeners-virtual-host/gio-form-listeners-virtual-host.component.ts
  gravitee-apim-console-webui/src/management/api/component/gio-form-listeners/gio-form-listeners-virtual-host/gio-form-listeners-virtual-host.module.spec.ts
Labels: ready_to_test

#6389 fix(rest-api-v2): map the endpoint gRPC type as HttpEndpointV2
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/list/api-proxy-endpoint-list.component.html
  gravitee-apim-console-webui/src/management/api/proxy/endpoints/list/api-proxy-endpoint-list.component.spec.ts
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/Endpoint.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/mapper/EndpointMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/mapper/EndpointMapperTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6390 fix(CI): upgrade helm version
  .circleci/ci/src/jobs/helm/job-release-helm.ts
  .circleci/ci/src/jobs/helm/job-snyk-apim-charts.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm.yml
  .circleci/config.back.yml
  helm/CHANGELOG.md
  helm/Chart.yaml
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x

#6400 fix: handle '|' in path param for request in EL
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/path/impl/AbstractPathResolver.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/processor/pathparameters/PathParameters.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/handlers/api/processor/pathparameters/PathParametersTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6406 fix(e2e): remove duplicate `HttpEndpointV2FromJSONTyped` import
  gravitee-apim-e2e/scripts/update-management-v2-sdk.sh
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6414 fix(CI): Helm release
  .circleci/ci/src/jobs/helm/job-release-helm.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm.yml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6423 fix(console): fix hooks priority order and reload env settings when env change
  gravitee-apim-console-webui/src/management/api/apis.module.ts
  gravitee-apim-console-webui/src/management/management.run.ts
Labels: apply-on-4-0-x, apply-on-4-1-x

#6364 Console - application general migration - nineth part
  gravitee-apim-console-webui/src/entities/application/application.ts
  gravitee-apim-console-webui/src/management/application/application-navigation/application-navigation.component.html
  gravitee-apim-console-webui/src/management/application/application-navigation/application-navigation.component.scss
  gravitee-apim-console-webui/src/management/application/application-navigation/application-navigation.component.ts
  gravitee-apim-console-webui/src/management/application/applications.route.ts
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general-ng.component.html
  gravitee-apim-console-webui/src/management/application/details/general/general-ng/application-general-ng.component.ts
  gravitee-apim-console-webui/src/management/application/details/user-group-access/members/application-general-members.component.ts
  gravitee-apim-console-webui/src/management/application/details/user-group-access/transfer-ownership/application-general-transfer-ownership.component.html
  gravitee-apim-console-webui/src/management/application/details/user-group-access/transfer-ownership/application-general-transfer-ownership.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/user-group-access/transfer-ownership/application-general-transfer-ownership.component.ts
  gravitee-apim-console-webui/src/services-ngx/application-members.service.ts
Labels: ready_to_test

#6439 fix: enforce 3 char path in context path mode
  gravitee-apim-console-webui/src/management/api/component/gio-form-listeners/gio-form-listeners-context-path/gio-form-listeners-context-path.component.ts
  gravitee-apim-console-webui/src/management/api/component/gio-form-listeners/gio-form-listeners-context-path/gio-form-listeners-context-path.module.spec.ts
  gravitee-apim-console-webui/src/management/api/component/gio-form-listeners/gio-form-listeners-virtual-host/gio-form-listeners-virtual-host.component.ts
Labels: apply-on-master

#6473 Dv 397 helm remove depreciated securitycontext
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-deployment.yaml
  helm/templates/gateway/gateway-deployment.yaml
  helm/templates/portal/portal-deployment.yaml
  helm/templates/ui/ui-deployment.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/gateway/deployment_test.yaml
  helm/tests/portal/deployment_test.yaml
  helm/tests/ui/deployment_test.yaml
  helm/values.yaml
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x

#6470 Console - apis audit migration - first part
  gravitee-apim-console-webui/src/management/api/api-audit-list/api-audit-list.component.html
  gravitee-apim-console-webui/src/management/api/api-audit-list/api-audit-list.component.scss
  gravitee-apim-console-webui/src/management/api/api-audit-list/api-audit-list.component.spec.ts
  gravitee-apim-console-webui/src/management/api/api-audit-list/api-audit-list.component.ts
  gravitee-apim-console-webui/src/management/api/api-audit-list/api-audit-list.module.ts
  gravitee-apim-console-webui/src/management/api/apis-routing.module.ts
  gravitee-apim-console-webui/src/management/api/apis.module.ts
  gravitee-apim-console-webui/src/services-ngx/api-audit.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/api-audit.service.ts
Labels: ready_to_test

#6474 fix(doc): update broken link to changelog in helm readme
  helm/README.md
Labels: apply-on-3-20-x, apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x

#6490 fix(console): fixing api audit pagination
  gravitee-apim-console-webui/src/management/api/api-audit-list/api-audit-list.component.spec.ts
  gravitee-apim-console-webui/src/management/api/api-audit-list/api-audit-list.component.ts
  gravitee-apim-console-webui/src/services-ngx/api-audit.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/api-audit.service.ts
Labels: ready_to_test

#6284 fix: extract api,console and portal url from legacy configuration
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/bootstrap/ManagementUIResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/installation/query_service/InstallationAccessQueryService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/query_service/installation/InstallationAccessQueryServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/InstallationAccessQueryServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/query_service/installation/InstallationAccessQueryServiceImplTest.java
Labels: apply-on-master

#6507 chore(deps): upgrade connector-http to 3.0.3
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x
