Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-07, with the labels that each got.

#8183 fix: adapt events to multi-tenancy
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatService.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/impl/HeartbeatEventPublisher.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/impl/HeartbeatEventScheduler.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-heartbeat/src/test/java/io/gravitee/gateway/services/heartbeat/HeartbeatServiceTest.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/search/EventCriteria.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/search/SubscriptionCriteria.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/Event.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcEventLatestRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcEventRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_2/00_add_event_organizations.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/test/java/io/gravitee/repository/jdbc/JdbcTestRepositoryInitializer.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoEventLatestRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoEventRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/eventLatest/event/EventLatestMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/model/EventMongo.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/mapper/GraviteeMapper.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/events/OrganizationsIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/events/PropertiesApiIdTypeEnvsIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/events/PropertiesApiIdUpdatedAtEnvsIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/events/PropertiesDictionaryIdUpdatedEnvsAtIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/eventslatest/EnvironmentsIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/eventslatest/OrganizationsIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/eventslatest/PropertyApiIdTypeEnvsIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/eventslatest/PropertyDictionaryIdEnvsIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/eventslatest/TypeUpdatedAtPropertyApiIdEnvsIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/eventslatest/TypeUpdatedAtPropertyDictionaryIdEnvsIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/organization/MissingOrganizationsOnEventsUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/EventLatestRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/EventRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/event-latest-tests/events.json
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/event-tests/events.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/event/EventCrudServiceLegacyWrapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/EventService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EventServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/OrganizationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/dictionary/DictionaryServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiLoggingConditionUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/event/EventQueryServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/query_service/api/ApiEventQueryServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_DeleteTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_StartTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_StopTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/EventServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/OrganizationService_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/configuration/dictionary/DictionaryServiceImpl_StartTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/configuration/dictionary/DictionaryServiceImpl_StopTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/configuration/dictionary/DictionaryServiceImpl_UpdateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiLoggingConditionUpgraderTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImpl_DeployTest.java
Labels: apply-on-master

#8210 fix: bad SQL grammar for paginated access points queries
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcAccessPointRepository.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/AccessPointRepositoryTest.java
Labels: apply-on-4-4-x

#8213 Archi 383 bridge client examples
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  helm/values.yaml
Labels: apply-on-master

#8195 fix(dashboard): Set the dashboard's type to update it
  gravitee-apim-console-webui/src/components/widget/stats/widget-data-stats-configuration.component.ts
  gravitee-apim-console-webui/src/services/dashboard.service.ts
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8239 fix: add missing primary keys
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_2/00_add_event_organizations.yml
Labels: apply-on-master

#8248 fix: add extra upgrader to handle deprecated api key data
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_0/05_add_environment_id.yml
Labels: apply-on-master

#8238 chore: bump UI particles
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-master, apply-on-4-4-x

#8251 chore: bump ui-component to 4.2.4 ( fix gv-policy-studio policy submit button )
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8206 fix: bump keycloack version
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8281 chore: bump expression-language to 3.2.0
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8240 chore: bump ui-particles to 7.60.0
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-4-1-x, apply-on-4-2-x

#8293 fix: improve isSynchronized method
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/converter/ApiConverter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImpl_IsSynchronizedTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8299 fix: don't use empty constructor on component
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/converter/ApiConverter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/services/ApiServiceCockpitImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_DeleteTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_FindByIdAsMapTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_FindByIdTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_FindByUserTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_SearchTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_StartTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_StopTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_UpdateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiSearchService_SearchTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl_findAllTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiStateServiceImpl_DeployTest.java
Labels: apply-on-4-1-x

#8306 hide sensitive data in the console
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/InstanceServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/InstanceServiceTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8272 fix(media): Make the service transactional to automatically release t…
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MediaServiceImpl.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8340 fix: add TransactionalService to MetadataService
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AbstractReferenceMetadataService.java
Labels: apply-on-4-3-x, apply-on-4-4-x

#8321 APIM-5750 OpenSSL is not available any more
  gravitee-apim-distribution/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-core/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/gravitee-apim-gateway-standalone-distribution-zip/src/main/assembly/plugin-assembly-standalone.xml
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/assembly/plugin-assembly-distribution.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-integration-controller/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-container/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/gravitee-apim-rest-api-standalone-distribution-zip/src/main/assembly/plugin-assembly-standalone.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/assembly/plugin-assembly-distribution.xml
  pom.xml
Labels: apply-on-master, apply-on-4-3-x

#8205 fix: remove only first and last wildcards
  gravitee-apim-console-webui/src/components/logs/logs-filters.controller.ts
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8351 fix: change mapstruct scope to compile
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-container/pom.xml
  pom.xml
Labels: run-e2e-tests

#8356 Fix helm condition
  helm/templates/api/api-configmap.yaml
Labels: apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#8365 fix: e2e test fixing
  gravitee-apim-e2e/ui-test/integration/apim/ui/apis/ui-api-list.spec.ts
Labels: run-e2e-tests

#8369 feat(console) gravitee as a provider
  gravitee-apim-console-webui/src/management/api/list/api-list.component.html
  gravitee-apim-console-webui/src/management/api/list/api-list.component.scss
  gravitee-apim-console-webui/src/management/api/list/api-list.component.spec.ts
  gravitee-apim-console-webui/src/management/api/list/api-list.component.ts
  gravitee-apim-e2e/ui-test/integration/apim/ui/apis/ui-api-list.spec.ts
Labels: run-e2e-tests

#8386 chore: bump ui-particles
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/src/app.module.ts
  gravitee-apim-console-webui/src/management/api/policy-studio-v4/api-v4-policy-studio.module.ts
  gravitee-apim-console-webui/src/management/api/policy-studio-v4/design/api-v4-policy-studio-design.component.spec.ts
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-4-3-x, apply-on-4-4-x

#8375 fix: load audit events page per page without the payload
  gravitee-apim-console-webui/src/management/api/audit/apis.audit.route.ts
  gravitee-apim-console-webui/src/management/api/audit/events/apiEvents.controller.ts
  gravitee-apim-console-webui/src/management/api/audit/events/apiEvents.html
Labels: apply-on-master, ready_to_test, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8379 The gateway appears unhealthy on Cockpit when rate limit type is none instead of healthy
  gravitee-apim-gateway/gravitee-apim-gateway-repository/src/main/java/io/gravitee/gateway/repository/healthcheck/RateLimitRepositoryProbe.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8416 fix: use page id as key if name is null when exporting a CRD
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/kubernetes/v1alpha1/ApiDefinitionResource.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/test/java/io/gravitee/definition/model/kubernetes/v1alpha1/ApiDefinitionResourceTest.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/test/resources/io/gravitee/definition/model/kubernetes/v1alpha1/api-definition-with-page-without-name.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/ApiCRDAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/api/ApiCRDExportDomainServiceImplTest.java
Labels: apply-on-master

#8428 fix: don't remove group on import if the group PO is the API PO
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_UpdateTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-4-x, run-e2e-tests

#8429 feat(federation): update name of Azure provider
  gravitee-apim-console-webui/src/management/integrations/pipes/map-provider-name.pipe.ts
Labels: apply-on-master

#8436 do not allow user to click multiple times on application creation
  gravitee-apim-console-webui/src/management/application/creation-ng/application-creation.component.ts
Labels: apply-on-master, ready_to_test

#8437 feat: support `ROOT` page type in v2 kubernetes import
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/ImportPageEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/PageEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/spring/InfraServiceSpringConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/import/import-api.pages-root.kubernetes.json
Labels: apply-on-4-4-x

#8445 Fix event publisher on accesspoint crud
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/access_point/AccessPointCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/crud_service/access_point/AccessPointCrudServiceImplTest.java
Labels: apply-on-master

#8464 fix(console): issue with ResourceTypeComponent for GioFormJsonSchemaModule
  gravitee-apim-console-webui/src/app.module.ts
  gravitee-apim-console-webui/src/management/api/component/plan/2-secure-step/plan-edit-secure-step.component.ts
  gravitee-apim-console-webui/src/management/api/component/plan/api-plan-form.module.ts
  gravitee-apim-console-webui/src/management/api/policy-studio-v4/design/api-v4-policy-studio-design.component.ts
  gravitee-apim-console-webui/src/shared/components/form-json-schema-extended/form-json-schema-extended.module.ts
  gravitee-apim-console-webui/src/shared/components/form-json-schema-extended/resource-type.component.html
  gravitee-apim-console-webui/src/shared/components/form-json-schema-extended/resource-type.component.scss
  gravitee-apim-console-webui/src/shared/components/form-json-schema-extended/resource-type.component.ts
  gravitee-apim-console-webui/src/shared/components/form-json-schema-extended/resource-type.service.ts
  gravitee-apim-console-webui/src/shared/testing/gio-testing.module.ts
Labels: run-e2e-tests

#8450 fix: avoid empty volume mount
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-deployment.yaml
  helm/tests/api/deployment_cloud_test.yaml
Labels: apply-on-master

#8484 fix: bump node version
  helm/tests/api/deployment_federation_test.yaml
  helm/values.yaml
  pom.xml
Labels: apply-on-4-4-x

#8476 fix(console): fix for opening logs in new tab
  gravitee-apim-console-webui/src/management/analytics/logs/platform-logs.controller.ts
  gravitee-apim-console-webui/src/management/analytics/logs/platform-logs.html
  gravitee-apim-console-webui/src/management/api/analytics/logs/analytics-logs.controller.ajs.ts
  gravitee-apim-console-webui/src/management/api/analytics/logs/analytics-logs.html
  gravitee-apim-console-webui/src/management/application/details/logs/application-logs.controller.ts
  gravitee-apim-console-webui/src/management/application/details/logs/application-logs.html
Labels: apply-on-master, ready_to_test, apply-on-4-4-x

#8478 fix(console): fix for not handled error response
  gravitee-apim-console-webui/src/user/my-accout/token/generateTokenDialog.controller.ts
Labels: apply-on-master, apply-on-4-4-x

#8479 fix: Message reporters lacking api name value
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/AbstractApiReactor.java
  pom.xml
Labels: run-e2e-tests

#8493 chore: bump cloud-reporter to 1.0.1
  pom.xml
Labels: apply-on-master

#8499 chore(docker): add new docker-compose configuration for mssql
  docker/quick-setup/mssql/README.md
  docker/quick-setup/mssql/docker-compose.yml
  docker/quick-setup/mssql/init-db.sh
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#8532 fix: add missing license [skip CI]
  docker/quick-setup/mssql/init-db.sh
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#8539 fix: handle default/custom page for Federated APIs
  gravitee-apim-console-webui/src/management/api/api-navigation/api-federated-menu.service.spec.ts
  gravitee-apim-console-webui/src/management/api/api-navigation/api-federated-menu.service.ts
Labels: apply-on-4-4-x

#8491 Console: Api alerts - fix errors & bad screen behavior
  gravitee-apim-console-webui/src/components/alerts/alert/_alert.scss
  gravitee-apim-console-webui/src/components/alerts/alert/alert.component.ajs.ts
  gravitee-apim-console-webui/src/components/alerts/alert/alert.html
  gravitee-apim-console-webui/src/components/alerts/alert/history/alert-history.component.ts
  gravitee-apim-console-webui/src/components/alerts/alert/notifications/alert-notification.ts
  gravitee-apim-console-webui/src/libraries/angular-schema-form/boostrap-decorator.js
  gravitee-apim-console-webui/src/libraries/angular-schema-form/boostrap-decorator.ts
  gravitee-apim-console-webui/src/libraries/angular-schema-form/codemirror-decorator.js
Labels: apply-on-master, ready_to_test, apply-on-4-4-x

#8544 fix: split hz config for cluster and cache
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-configmap.yaml
  helm/templates/api/api-deployment.yaml
  helm/templates/api/api-service-federation.yaml
  helm/templates/api/api-service.yaml
  helm/tests/api/configmap_federation_test.yaml
Labels: apply-on-master, apply-on-4-4-x

#8530 fix(liquibase): drop not null constraint for environment_id keys table
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_0/05_add_environment_id.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_4/00_drop_not_null_constraint.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
Labels: apply-on-master

#8541 chore(deps): update jwt policy to 4.1.4
  pom.xml
Labels: apply-on-master

#8549 fix(gateway): Missing Api Name setup in log reporters
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/processor/logging/LogInitProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactive/reactor/processor/reporter/ReporterProcessor.java
Labels: run-e2e-tests
