Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-04, with the labels that each got.

#7110 fix: add synchronized on getOrInitialize installation to avoid installation duplication
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/InstallationServiceImpl.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#7116 fix(console): make app work when environment haven't hrids value
  gravitee-apim-console-webui/src/management/environment.guard.ts
Labels: apply-on-master

#7115 fix: handle EL parsing expression
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7129 fix(console): use timestamp parameter in goToLog controller method in…
  gravitee-apim-console-webui/src/management/api/analytics/logs/analytics-log.component.ajs.ts
Labels: apply-on-master, ready_to_test

#7127 feat(plugin): use cron editor format in dynamic-prop & HC json-schema
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-dynamicproperties/gravitee-apim-plugin-apiservice-dynamicproperties-http/src/main/resources/schemas/schema-form.json
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-healthcheck-http/src/main/resources/schemas/schema-form.json
Labels: apply-on-master

#7139 chore(deps): bump gravitee-bom to 7.0.18
  pom.xml
Labels: apply-on-4-3-x

#7143 fix: bump reporter-* versions for Monitor issue
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/pom.xml
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7153 test: regenerate expired certificates
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/ca.key
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/ca.pem
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/client-keystore.jks
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/client-keystore.p12
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/client-truststore.jks
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/client-truststore.p12
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/client-truststore.pem
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/client.cer
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/client.csr
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/client.key
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/server1.dc1.consul.crt
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/server1.dc1.consul.csr
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/config/ssl/server1.dc1.consul.key
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-servicediscovery-consul/src/test/resources/docker/generate-certificates.sh
Labels: apply-on-4-0-x, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7152 chore: update gravitee-bom to 6.0.39
  pom.xml
Labels: apply-on-4-0-x, apply-on-4-1-x

#7118 feat: auth & redirect to portal from cloud
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalRedirectResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/auth/CockpitAuthenticationResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/JerseySpringTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/CockpitAuthenticationResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/resources/auth/ca-truststore.p12
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/resources/auth/keystore.p12
Labels: apply-on-4-3-x

#7163 fix: bump policy-cache version mutable object issue
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7169 fix: bump gravitee-node version HTTP/2 max header limit
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x

#7172 fix: bump gravitee-node version HTTP/2 max header limit
  pom.xml
Labels: apply-on-master

#7134 feat: migrate application subscriptions list
  gravitee-apim-console-webui/src/app.module.ajs.ts
  gravitee-apim-console-webui/src/entities/subscription/subscription.ts
  gravitee-apim-console-webui/src/management/application/applications-routing.module.ts
  gravitee-apim-console-webui/src/management/application/applications.module.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/application-subscriptions-list.component.html
  gravitee-apim-console-webui/src/management/application/details/subscriptions/application-subscriptions-list.component.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/application-subscriptions-list.controller.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/application-subscriptions.component.ajs.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/application-subscriptions.component.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/application-subscriptions.controller.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/application-subscriptions.html
  gravitee-apim-console-webui/src/management/application/details/subscriptions/application-subscriptions.scss
  gravitee-apim-console-webui/src/management/application/details/subscriptions/list/application-subscription-list.component.html
  gravitee-apim-console-webui/src/management/application/details/subscriptions/list/application-subscription-list.component.scss
  gravitee-apim-console-webui/src/management/application/details/subscriptions/list/application-subscription-list.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/list/application-subscription-list.component.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/list/application-subscription-list.harness.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/list/application-subscription-list.module.ts
  gravitee-apim-console-webui/src/services-ngx/application.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/application.service.ts
Labels: ready_to_test

#7144 fix(portal): skip navigation when md page has no navigable elements
  gravitee-apim-portal-webui/src/app/components/gv-page-markdown/gv-page-markdown.component.ts
Labels: apply-on-4-0-x, apply-on-master, ready_to_test, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7180 fix(analytics): improve performance of getting applications for non admin users in analytics
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformAnalyticsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/PlatformAnalyticsResource_NotAdmin_GetTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7200 fix the plugin comparison method
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x

#7198 fix(portal): change default site title
  gravitee-apim-portal-webui/src/index.html
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7210 fix(jdbc): change datatype
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_0_22/schema-idp.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/IdentityProviderRepositoryTest.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7232 fix(portal-next): add config for next in docker
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/config/config-next.json
Labels: ready_to_test

#7245 fix(portal-next): substitute PORTAL_API_URL in config.json
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/config/portal-next-run.sh
Labels: ready_to_test

#7255 fix: bump policy-cache version octet-stream data cache issue
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7240 fix(alpn): configure alpn option even if not secured
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x

#7241 fix(alpn): configure alpn option even if not secured - 4.3.x
  pom.xml
Labels: apply-on-master

#7254 ci: use the same cache for sonar jobs
  .circleci/ci/src/jobs/job-sonarcloud-analysis.ts
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-console-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-portal-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
  .circleci/ci/src/workflows/workflow-pull-requests.ts
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7271 fix: use dedicated formatter for oai 3.1
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/swagger/AbstractDescriptor.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/swagger/OAIDescriptor.java
Labels: apply-on-4-1-x, apply-on-4-2-x

#7269 fix(rest-api): change Error.details.invalidValue to any
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/exceptionMapper/ConstraintValidationExceptionMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/exceptionMapper/ValidationExceptionMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/provider/ObjectMapperResolver.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/management-openapi-v2.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/exceptionMapper/ConstraintValidationExceptionMapperTest.java
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#7284 fix: bump policy-cache version evaluate response condition before store in cache
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7236 fix(console): Filter possible endpoints by selected entrypoint capabilities
  gravitee-apim-console-webui/src/entities/management-api-v2/api/v4/connectorVM.ts
  gravitee-apim-console-webui/src/management/api/creation-v4/api-creation-v4.component.spec.ts
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/step-3-endpoints/step-3-endpoints-1-list.component.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/create/api-endpoint-group-create.component.html
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/create/api-endpoint-group-create.component.spec.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/create/api-endpoint-group-create.component.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/create/api-endpoint-group-create.harness.ts
  gravitee-apim-console-webui/src/management/api/endpoints-v4/endpoint-group/selection/api-endpoint-group-selection.component.ts
  gravitee-apim-console-webui/src/shared/components/gio-connector-list-option/gio-connector-radio-list.harness.ts
Labels: apply-on-master, ready_to_test, apply-on-4-2-x, apply-on-4-3-x

#7291 fix(console): application creation flow fixed on security step
  gravitee-apim-console-webui/src/management/application/creation/steps/application-creation-step2.controller.ts
  gravitee-apim-console-webui/src/management/application/creation/steps/application-creation-step2.html
Labels: apply-on-4-0-x, apply-on-master, apply-on-4-1-x, apply-on-4-3-x

#7325 bump policy cache ttl resolve
  pom.xml
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#7326 debug NPE
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/mapper/DebugApiMapperTest.java
Labels: apply-on-master
