Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-12, with the labels that each got.

#10012 feat: add Transform Status Code Policy
  gravitee-apim-distribution/pom.xml
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x

#9999 fix(console): searching for custom key by and environment_id
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/ApiKeyRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoApiKeyRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/key/ApiKeyMongoRepository.java
  gravitee-apim-repository/gravitee-apim-repository-noop/src/main/java/io/gravitee/repository/noop/management/NoOpApiKeyRepository.java
  gravitee-apim-repository/gravitee-apim-repository-noop/src/test/java/io/gravitee/repository/noop/management/NoOpApiKeyRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/ApiKeyRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/apikey-tests/apiKeys.json
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/apikey-tests/apis.json
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/apikey-tests/applications.json
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/apikey-tests/subscriptions.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApiKeyService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiKeyServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiKeyServiceTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-2-x, apply-on-4-3-x

#10062 feat: validate k8s groups that have a primary owner
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/group/domain_service/ValidateGroupsDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/group/domain_service/ValidateGroupsDomainServiceTest.java
Labels: apply-on-master

#10090 ci: bump postgres test container version and remove unsupported one
  .circleci/ci/src/pipelines/tests/resources/repositories-tests/repositories-tests.yml
  .circleci/ci/src/workflows/workflow-repositories-tests.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x

#10089 ci: bump elastic test container version to latest
  .circleci/ci/src/pipelines/tests/resources/repositories-tests/repositories-tests.yml
  .circleci/ci/src/workflows/workflow-repositories-tests.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x

#10091 fix: application notify members
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewApplicationEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/model/crd/ApplicationCRDSpec.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/converter/ApplicationConverter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/ImportApplicationCRDDomainServiceInMemory.java
Labels: apply-on-4-5-x, apply-on-4-4-x

#10082 fix: remove delete trial events
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/EventService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteEnvironmentCommandHandler.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteOrganizationCommandHandler.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/EventServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteEnvironmentCommandHandlerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteOrganizationCommandHandlerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/EventServiceTest.java
Labels: apply-on-4-5-x

#10128 chore: bump gravitee-entrypoint-webhook [skip ci]
  pom.xml
Labels: apply-on-master

#10168 Apim 7811 publisher can resume failed subscription v2
  gravitee-apim-console-webui/src/management/api/subscriptions/edit/api-subscription-edit.component.html
  gravitee-apim-console-webui/src/management/api/subscriptions/edit/api-subscription-edit.component.spec.ts
  gravitee-apim-console-webui/src/management/api/subscriptions/edit/api-subscription-edit.component.ts
  gravitee-apim-console-webui/src/management/api/subscriptions/edit/api-subscription-edit.harness.ts
  gravitee-apim-console-webui/src/services-ngx/api-subscription-v2.service.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiSubscriptionsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/SubscriptionService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/SubscriptionFailureCustomerStatusRequiredException.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/SubscriptionServiceTest.java
Labels: apply-on-master

#10180 chore(deps): bump gravitee-endpoint-rabbitmq to 1.3.2
  pom.xml
Labels: apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#10156 chore(deps): bump oauth2 resource am and generic to 3.0.0
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x

#10170 fix: make http configuration read only for kubernetes v2 apis
  gravitee-apim-console-webui/src/management/api/endpoints/groups/endpoint/edit/configuration/api-proxy-group-endpoint-configuration.component.ts
Labels: apply-on-4-5-x, apply-on-4-4-x

#10191 feat:Policy - Transform Status Code
  pom.xml
Labels: apply-on-4-5-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#10205 chore(deps): bump connector-http to 4.0.4 and traffic-shadowing to 2.0.2
  pom.xml
Labels: apply-on-4-5-x

#10208 chore(deps): bump connector-http to 5.0.0-alpha.2 and traffic-shadowi…
  pom.xml
Labels: apply-on-master

#10227 chore(deps): replace all alpha dependencies with released version
  pom.xml
Labels: apply-on-master
