Repository gravitee-io/gravitee-api-management, pull requests merged in 2024-08, with the labels that each got.

#8553 feat(console): rename documentation tabs for v4 + federated apis
  gravitee-apim-console-webui/src/management/api/api-navigation/api-federated-menu.service.spec.ts
  gravitee-apim-console-webui/src/management/api/api-navigation/api-federated-menu.service.ts
  gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.spec.ts
  gravitee-apim-console-webui/src/management/api/api-navigation/api-v4-menu.service.ts
  gravitee-apim-console-webui/src/management/api/apis-routing.module.ts
Labels: apply-on-4-4-x

#8564 chore(deps): update callout-http policy to 4.0.0
  pom.xml
Labels: apply-on-master

#8555 feat(portal-next): show banner based upon backend settings
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.html
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.ts
  gravitee-apim-portal-webui-next/src/entities/configuration/configuration-portal-next.ts
  gravitee-apim-portal-webui-next/src/services/config.service.spec.ts
  gravitee-apim-portal-webui-next/src/testing/app-testing.module.ts
Labels: apply-on-4-4-x

#8575 Apim 5445 fix subscription button after T&C cancel
  gravitee-apim-portal-webui-next/src/app/api/subscribe-to-api/subscribe-to-api.component.ts
Labels: apply-on-4-4-x

#8577 fix(portal-next): only show api key mode selection if shared api key enabled
  gravitee-apim-portal-webui-next/src/app/api/subscribe-to-api/subscribe-to-api.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/api/subscribe-to-api/subscribe-to-api.component.ts
Labels: apply-on-4-4-x

#8572 Put default logo and favicon in default portal next theme
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/theme/domain_service/DefaultThemeDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/theme/domain_service/ThemePortalNextAssetsDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/theme/ThemePortalNextAssetsDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/ThemePortalNextAssetsDomainServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/spring/InMemoryConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/theme/domain_service/DefaultThemeDomainServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/theme/use_case/GetCurrentThemeUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/theme/use_case/GetDefaultThemeUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/theme/ThemePortalNextAssetsDomainServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/themes/next/favicon.png
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/themes/next/logo.png
Labels: apply-on-4-4-x

#8588 fix: Include api name in health check report
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-healthcheck-common/src/test/java/io/gravitee/plugin/apiservice/healthcheck/common/HealthCheckManagedEndpointTest.java
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-healthcheck-http/src/main/java/io/gravitee/apim/plugin/apiservice/healthcheck/http/HttpHealthCheckService.java
  pom.xml
Labels: run-e2e-tests

#8590 fix: make sync process sequential
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/DefaultSyncManager.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/repository/DefaultSyncManagerTest.java
Labels: apply-on-4-1-x, apply-on-4-3-x

#8611 Add bundle-default profile in backend build
  .circleci/ci/src/jobs/backend/job-backend-build-and-publish-artifactory.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
Labels: apply-on-master

#8613 fix(console): fix credentials omit option
  gravitee-apim-console-webui/src/index.ts
Labels: apply-on-master, ready_to_test, apply-on-4-4-x

#8615 feat(porta-next): Update text for Last Updated in portal information …
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-details/api-tab-details.component.html
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-details/api-tab-details.component.spec.ts
Labels: apply-on-4-4-x

#8631 chore(console): UI-Particles library bump to version 12.19
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-master, apply-on-4-4-x

#8628 chore(console): UI-Particles library bump to version 7.60.1
  gravitee-apim-console-webui/package-lock.json
  gravitee-apim-console-webui/package.json
Labels: apply-on-4-2-x

#8625 fix(management): repository query should not be limited to all tags when search for commands
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcCommandRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/message/CommandMongoRepositoryCustomImpl.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/CommandRepositoryTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8642 fix: avoid memory leak on successive api redeploy
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactor.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactorTest.java
Labels: apply-on-master

#8646 test(portal-next): remove global time set + deactivate dependent tests
  gravitee-apim-portal-webui-next/package.json
Labels: apply-on-4-4-x

#8570 fix(console): Date range picker sets end range at start of day
  gravitee-apim-console-webui/src/management/api/api-audit-list/api-audit-list.component.spec.ts
  gravitee-apim-console-webui/src/management/api/api-audit-list/api-audit-list.component.ts
  gravitee-apim-console-webui/src/management/api/api-audit-logs/api-audit-logs.component.spec.ts
  gravitee-apim-console-webui/src/management/api/api-audit-logs/components/api-audits-filter-form/api-audits-filter-form.component.ts
  gravitee-apim-console-webui/src/management/audit/env-audit.component.spec.ts
  gravitee-apim-console-webui/src/management/audit/env-audit.component.ts
  gravitee-apim-console-webui/src/organization/configuration/audit/org-settings-audit.component.spec.ts
  gravitee-apim-console-webui/src/organization/configuration/audit/org-settings-audit.component.ts
  gravitee-apim-console-webui/src/util/date.util.ts
Labels: apply-on-master, ready_to_test, apply-on-4-4-x

#8645 fix(portal-next): handle pagination when less than 5 pages better
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-logs/application-tab-logs.component.html
Labels: apply-on-4-4-x

#8624 fix: make API properties readonly with kubernetes origin
  gravitee-apim-console-webui/src/management/api/properties/properties/api-properties.component.html
  gravitee-apim-console-webui/src/management/api/properties/properties/api-properties.component.spec.ts
  gravitee-apim-console-webui/src/management/api/properties/properties/api-properties.component.ts
Labels: apply-on-4-3-x, apply-on-4-4-x

#8648 fix(portal-next): fix app name
  gravitee-apim-portal-webui-next/src/components/application-card/application-card.component.html
  gravitee-apim-portal-webui-next/src/components/application-card/application-card.component.scss
  gravitee-apim-portal-webui-next/src/components/application-card/application-card.component.ts
Labels: apply-on-4-4-x

#8668 test(portal-next): remove dependency on testing-library
  gravitee-apim-portal-webui-next/package.json
  gravitee-apim-portal-webui-next/src/app/applications/application/application-tab-settings/application-tab-settings-edit/application-tab-settings-edit.harness.ts
  gravitee-apim-portal-webui-next/yarn.lock
Labels: apply-on-4-4-x

#8679 fix(portalNext): update app list scroll
  gravitee-apim-portal-webui-next/src/app/applications/applications.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/applications/applications.component.ts
Labels: apply-on-4-4-x

#8670 fix(service): Fix for counting total apis for portal category endpoint
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8698 fix: rework assembly dependencies for the prod bundles
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/gravitee-apim-gateway-standalone-distribution-zip/src/main/assembly/plugin-assembly-standalone.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/gravitee-apim-rest-api-standalone-distribution-zip/src/main/assembly/plugin-assembly-standalone.xml
Labels: apply-on-master

#8703 fix(portal-next): calculate first page of results by page number
  gravitee-apim-portal-webui-next/src/app/applications/applications.component.ts
  gravitee-apim-portal-webui-next/src/app/catalog/catalog.component.ts
Labels: apply-on-4-4-x

#8704 fix(rbac): avoid a NPE
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GroupMembersResource.java
Labels: run-e2e-tests

#8717 fix: check websocket is upgraded when evaluating HTTP response is streaming data
  gravitee-apim-gateway/gravitee-apim-gateway-http/src/main/java/io/gravitee/gateway/http/utils/RequestUtils.java
  gravitee-apim-gateway/gravitee-apim-gateway-http/src/main/java/io/gravitee/gateway/reactive/http/vertx/VertxHttpServerResponse.java
  gravitee-apim-gateway/gravitee-apim-gateway-http/src/test/java/io/gravitee/gateway/http/utils/RequestUtilsTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-http/src/test/java/io/gravitee/gateway/reactive/http/vertx/VertxHttpServerResponseTest.java
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8726 fix cypress API list test
  gravitee-apim-e2e/cypress.config.ts
  gravitee-apim-e2e/ui-test/integration/apim/ui/apis/ui-api-list.spec.ts
Labels: apply-on-master, apply-on-4-4-x

#8740 fix: disable role update for users with only 'organization-user-r' pe…
  gravitee-apim-console-webui/src/organization/configuration/user/detail/org-settings-user-detail.component.ts
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8712 fix: decrypt API properties when we use the debug mode
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/DebugConfiguration.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/reactive/debug/DebugReactorEventListener.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/test/java/io/gravitee/gateway/reactive/debug/DebugReactorEventListenerTest.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x, run-e2e-tests

#8775 fix: fix for 'should add user as api member' e2e test
  gravitee-apim-e2e/api-test/src/apis/mapi-v2/transfer-ownership/api-v4-transfer-ownership.spec.ts
Labels: run-e2e-tests

#8759 fix opensearch tests
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/TestConfiguration.java
Labels: apply-on-master

#8790 ci: set the default version for remote docker
  .circleci/ci/src/config.ts
  .circleci/ci/src/jobs/frontend/job-webui-build.ts
  .circleci/ci/src/jobs/job-build-backend-images.ts
  .circleci/ci/src/jobs/job-publish-prod-docker-images.ts
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-no-dry-run-as-latest.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm-and-docker-images/build-rpm-and-docker-images-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-console-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-portal-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
  .circleci/ci/src/pipelines/tests/resources/run-e2e-tests/run-e2e-tests.yml
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8786 chore(deps): update groovy policy
  pom.xml
Labels: apply-on-4-2-x, apply-on-4-3-x

#8649 feat(console): Add additional metadata for Application creation
  gravitee-apim-console-webui/src/entities/application/Application.ts
  gravitee-apim-console-webui/src/management/application/creation-ng/application-creation.component.spec.ts
  gravitee-apim-console-webui/src/management/application/creation-ng/application-creation.component.ts
  gravitee-apim-console-webui/src/management/application/creation-ng/components/application-creation-form.component.html
  gravitee-apim-console-webui/src/management/application/creation-ng/components/application-creation-form.component.ts
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.html
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/general/application-general.component.ts
  gravitee-apim-console-webui/src/management/application/details/general/application-general.module.ts
  gravitee-apim-console-webui/src/util/gio-form-header.util.spec.ts
  gravitee-apim-console-webui/src/util/gio-form-header.util.ts
  gravitee-apim-portal-webui/projects/portal-webclient-sdk/src/lib/model/oAuthClientSettings.ts
  gravitee-apim-portal-webui/src/app/pages/application/application-creation/application-creation-step2/application-creation-step2.component.html
  gravitee-apim-portal-webui/src/app/pages/application/application-creation/application-creation-step2/application-creation-step2.component.ts
  gravitee-apim-portal-webui/src/app/pages/application/application-creation/application-creation.component.ts
  gravitee-apim-portal-webui/src/assets/i18n/en.json
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/Application.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateApplicationEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/application/OAuthClientSettings.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/application/registration/ClientRegistrationMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/application/registration/ClientRegistrationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ClientRegistrationService_RegisterTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ClientRegistrationService_UpdateTest.java
Labels: run-e2e-tests

#8800 chore(deps): update oauth2 policy to v.3.0.5
  pom.xml
Labels: apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8810 fix: make sure debug does not block the eventloop
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/handler/ReactorEventListener.java
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/test/java/io/gravitee/gateway/reactor/handler/ReactorEventListenerTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/reactive/debug/DebugReactorEventListener.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/reactive/debug/reactor/processor/DebugCompletionProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/test/java/io/gravitee/gateway/reactive/debug/DebugReactorEventListenerTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/test/java/io/gravitee/gateway/reactive/debug/reactor/processor/DebugCompletionProcessorTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-endpoint-discovery/src/main/java/io/gravitee/gateway/services/endpoint/discovery/verticle/EndpointDiscoveryVerticle.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/verticle/EndpointHealthcheckVerticle.java
Labels: apply-on-master, apply-on-4-1-x, apply-on-4-2-x, apply-on-4-3-x

#8819 bump gravitee-expression-language version to 3.2.1
  pom.xml
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8827 fix: add missing @EnableAsync in Rest API configurations
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/spring/RestManagementConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/spring/RestManagementConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/spring/RestPortalConfiguration.java
Labels: apply-on-master, apply-on-4-2-x, apply-on-4-3-x, apply-on-4-4-x

#8833 fix: explicitly declare lazy & autowired on a dependency
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/search/DistributedLuceneIndexer.java
Labels: apply-on-master
