Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-05, with the labels that each got.

#11663 fix: V4 emulation engine and description on rollback e2e test
  gravitee-apim-e2e/api-test/src/apis/rollback/mapi-v1/api-v2-rollback.spec.ts
  gravitee-apim-e2e/api-test/src/apis/rollback/mapi-v2/api-v4-rollback.spec.ts
Labels: apply-on-4-5-x, apply-on-master, run-e2e-tests, apply-on-4-6-x, apply-on-4-7-x

#11736 fix: Schema registry resource URL not fully taken into account
  pom.xml
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x

#11765 fix: align tenant name character limit across UI and API
  gravitee-apim-console-webui/src/organization/configuration/tenants/org-settings-add-tenant.component.html
  gravitee-apim-console-webui/src/organization/configuration/tenants/org-settings-add-tenant.component.spec.ts
  gravitee-apim-console-webui/src/organization/configuration/tenants/org-settings-add-tenant.component.ts
  gravitee-apim-console-webui/src/organization/configuration/tenants/org-settings-tenants.component.spec.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/NewTenantEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/TenantEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/UpdateTenantEntity.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#11757 fix: Alert filter doesn't show list of APIs in selection box
  gravitee-apim-console-webui/src/components/alerts/alert/alert.html
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11767 fix: fix E2E
  pom.xml
Labels: run-e2e-tests

#11780 test: make activation of node monitoring possible on test sdk
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/pom.xml
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/container/GatewayTestContainer.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/GatewayRunner.java
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/tracing/JaegerTestContainer.java
  helm/tests/api/deployment_federation_test.yaml
  helm/values.yaml
  pom.xml
Labels: apply-on-master

#11789 fix: handle null API definition version to ensure alert delivery
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_FindByIdAsMapTest.java
Labels: apply-on-master

#11783 Apim 9518 improve upgrader logs
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/AlertsEnvironmentUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiCategoryOrderUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiKeySubscriptionsUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiLoggingConditionUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiPrimaryOwnerRemovalUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApiV4CategoriesUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ApplicationApiKeyModeUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ClientIdInApiKeySubscriptionsUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/CommandOrganizationUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/DefaultEnvironmentUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/DefaultOrganizationUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/DefaultRolesUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/EventsLatestUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ExecutionModeUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/GenericNotificationConfigUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/InstallationKeyStatusUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/MetadataDefaultReferenceUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/OrphanCategoryUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/PlansDataFixUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/PlansFlowsDefinitionUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/PortalNotificationConfigUpgrader.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/QualityRulesScopingUpgrader.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11797 fix: 🐛 fix Bitnami/elasticsearch replicaCount in values.yaml
  helm/values.yaml
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11734 fix: proxy connector don’t send query chunked if not need
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/main/java/io/gravitee/plugin/endpoint/http/proxy/connector/HttpConnector.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/test/java/io/gravitee/plugin/endpoint/http/proxy/connector/HttpConnectorTest.java
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11821 chore: bump callout http policy to 4.0.2
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11830 feat: bump up gravitee retry policy to version 3.0.0
  pom.xml
Labels: apply-on-4-7-x

#11842 ci: deactivate debug for aqua's job [skip ci]
  .circleci/ci/src/jobs/job-build-docker-image.ts
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run-as-latest.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-distribution-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-gateway-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-integration-tests-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-plugin-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-rest-api-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-console-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-helm-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-portal-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
  .circleci/ci/src/workflows/workflow-pull-requests.ts
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11847 ci: deactivate debug for aqua's job [skip ci] 4.4.x
  .circleci/ci/src/commands/cmd-build-ui-image.ts
  .circleci/ci/src/jobs/job-build-backend-images.ts
  .circleci/ci/src/jobs/job-publish-prod-docker-images.ts
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run-as-latest.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-distribution-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-gateway-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-integration-tests-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-plugin-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-rest-api-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-console-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-helm-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-portal-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
  .circleci/ci/src/workflows/workflow-pull-requests.ts
Labels: apply-on-4-5-x, apply-on-4-6-x

#11850 ci(deps): bump aquasec orb to 1.0.5
  .circleci/ci/src/config.ts
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run-as-latest.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-distribution-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-gateway-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-integration-tests-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-plugin-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-rest-api-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-console-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-helm-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-portal-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11856 chore(deps): bump policy-aws-lambda to 1.3.2
  pom.xml
Labels: apply-on-4-5-x, apply-on-4-6-x

#11879 chore(deps): bump gravitee-policy-xslt.version to 3.1.1
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11860 fix: avoid status 0 in analytics when V4 emulation engine is activate…
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/AbstractResponse.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/adapter/invoker/ConnectionHandlerAdapter.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/adapter/invoker/FlowableProxyResponse.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/adapter/invoker/InvokerAdapter.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/adapter/invoker/InvokerAdapterTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-http/src/main/java/io/gravitee/gateway/reactive/http/vertx/VertxHttpServerResponse.java
Labels: apply-on-4-5-x, apply-on-4-4-x, run-e2e-tests, apply-on-4-6-x, apply-on-4-7-x

#11897 chore(deps): bump connector-http to 5.0.5
  pom.xml
Labels: apply-on-4-6-x, apply-on-4-7-x

#11898 chore(deps): bump connector-http to 4.0.9
  pom.xml
Labels: apply-on-4-4-x

#11927 fix: Change the ordering groups list when requested
  gravitee-apim-console-webui/src/management/settings/groups/groups.component.ajs.ts
  gravitee-apim-console-webui/src/management/settings/groups/groups.html
  gravitee-apim-console-webui/src/services/group.service.ts
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/GroupRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcGroupRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoGroupRepository.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/GroupRepositoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GroupsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/GroupsResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/GroupService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/GroupServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/GroupServiceImplTest.java
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x
