Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-09, with the labels that each got.

#13029 fix(mcp): null & blank check for acceptHeader
  pom.xml
Labels: apply-on-master

#13012 fix: missing dynamic properties in export V4 API, and updated Junit t…
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/GraviteeDefinitionAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/api/ApiExportDomainServiceImplTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#13041 GKO-14131fetcher auto fetch fix
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/model/crd/PageCRD.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/documentation/model/factory/PageModelFactory.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#13030 fix: manage index upgraders with dedicated mongo client to handle lar…
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/ManagementRepositoryConfiguration.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/common/IndexMongoUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/Index.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/IndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/java/io/gravitee/repository/mongodb/MongoTestRepositoryConfiguration.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/java/io/gravitee/repository/mongodb/MongoTestRepositoryInitializer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-container/src/main/java/io/gravitee/rest/api/standalone/node/GraviteeApisNode.java
Labels: apply-on-master

#13076 fix: add lazy initialization for repositories in PortalPageQueryServiceImpl
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/portal_page/PortalPageContextCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/portal_page/PortalPageCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/query_service/portal_page/PortalPageQueryServiceImpl.java
Labels: run-e2e-tests

#13096 fix: audit and events cleaner should be only started on primary node
  gravitee-apim-rest-api/gravitee-apim-rest-api-services/gravitee-apim-rest-api-services-audit/src/main/java/io/gravitee/rest/api/services/audit/ScheduledAuditCleanerService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-services/gravitee-apim-rest-api-services-audit/src/test/java/io/gravitee/rest/api/services/audit/ScheduledAuditCleanerServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-services/gravitee-apim-rest-api-services-events/src/main/java/io/gravitee/rest/api/services/events/ScheduledEventsCleaningService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-services/gravitee-apim-rest-api-services-events/src/test/java/io/gravitee/rest/api/services/events/ScheduledEventsCleaningServiceTest.java
Labels: apply-on-4-8-x

#13068 fix: add support for retrieving secrets using debug mode
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/reactive/debug/DebugReactorEventListener.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/test/java/io/gravitee/gateway/reactive/debug/DebugReactorEventListenerTest.java
Labels: apply-on-master

#13146 fix: restore the full endpoint URL in health-check response
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/HealthCheckServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/HealthCheckServiceImplTest.java
Labels: apply-on-master

#13139 fix: correct group and path-mapping comparison in diff view
  gravitee-apim-console-webui/src/management/api/audit/history/apiHistory.controller.ajs.ts
  gravitee-apim-console-webui/src/management/api/audit/history/apiHistory.controller.spec.ts
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#13174 fix(console): align analytics graph to display local timezone
  gravitee-apim-console-webui/src/shared/components/gio-chart-line/gio-chart-line.component.ts
  gravitee-apim-console-webui/src/shared/utils/timeFrameRanges.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-9-x

#13181 fix(automation API): remove API_KEY from plan
  gravitee-apim-rest-api/gravitee-apim-rest-api-automation/gravitee-apim-rest-api-automation-rest/src/main/java/io/gravitee/apim/rest/api/automation/mapper/ApiMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-automation/gravitee-apim-rest-api-automation-rest/src/main/resources/open-api.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-automation/gravitee-apim-rest-api-automation-rest/src/test/java/io/gravitee/apim/rest/api/automation/resource/ApiResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-automation/gravitee-apim-rest-api-automation-rest/src/test/resources/io/gravitee/apim/rest/api/automation/resource/api-with-cross-id-and-hrid.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-automation/gravitee-apim-rest-api-automation-rest/src/test/resources/io/gravitee/apim/rest/api/automation/resource/api-with-hrid-spg-hrid.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-automation/gravitee-apim-rest-api-automation-rest/src/test/resources/io/gravitee/apim/rest/api/automation/resource/api-with-hrid.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-automation/gravitee-apim-rest-api-automation-rest/src/test/resources/io/gravitee/apim/rest/api/automation/resource/api-with-no-hrid.json
Labels: apply-on-4-9-x

#13214 chore: update transformheader policy
  pom.xml
Labels: apply-on-master

#13231 fix: update expression language dependencies
  pom.xml
Labels: apply-on-master

#13225 chore(jira): switch getJiraIssuesOfVersion from GET to POST /search/jql
  release/helpers/jira-helper.mjs
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#13274 chore(deps): update policies dependency
  pom.xml
Labels: apply-on-master

#13121 fix: default API visibility to PRIVATE when not provided
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApisResource_SearchApisTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/documentation/ApiPagesResourceTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#13222 fix: IPV6 CIDR ranges do not work in the IP filtering policy
  pom.xml
Labels: apply-on-master, apply-on-4-9-x

#13256 fix: resolve CI/CD pipeline error
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
Labels: run-e2e-tests

#13333 ci: update sonar executor version to 11.2 and keeper orb to 0.7.0
  .circleci/ci/src/config.ts
  .circleci/ci/src/jobs/job-sonarcloud-analysis.ts
  .circleci/ci/src/pipelines/tests/resources/bridge-compatibility-tests/bridge-compatibility-tests.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run-as-latest.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm/build-rpm-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm/build-rpm-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm/build-rpm-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm/build-rpm-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/helm-tests/helm-tests.yml
  .circleci/ci/src/pipelines/tests/resources/nexus-staging/nexus-staging-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-distribution-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-gateway-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-integration-tests-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-plugin-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-rest-api-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-console-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-helm-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-portal-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm.yml
  .circleci/ci/src/pipelines/tests/resources/release-notes-apim/release-notes-apim-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release-notes-apim/release-notes-apim-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
  .circleci/ci/src/pipelines/tests/resources/repositories-tests/repositories-tests.yml
  .circleci/ci/src/pipelines/tests/resources/run-e2e-tests/run-e2e-tests.yml
Labels: apply-on-4-6-x, apply-on-4-7-x

#13336 fix(gateway): handle flatten base64 cert body in header
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#13300 feat: rework definition
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/Api.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/ApiDefinition.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/federation/FederatedAgent.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/federation/FederatedApi.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/AbstractApi.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/Api.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/nativeapi/NativeApi.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/processor/ApiProcessorChainFactory.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/v4/processor/ApiProcessorChainFactoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiResource_DeploymentsCurrentTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/model/Api.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/model/property/DynamicApiProperties.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/use_case/GetApiDefinitionUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/use_case/ImportApiCRDUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/GetApiDefinitionUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/ImportApiCRDUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/crud_service/api/ApiCrudServiceImplTest.java
Labels: run-e2e-tests

#13363 chore(deps): bump policy-oas-validation
  pom.xml
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#13361 fix: icons the same color for analytics widgets
  gravitee-apim-console-webui/src/shared/components/gio-widget-layout/gio-widget-layout.component.html
  gravitee-apim-console-webui/src/shared/components/gio-widget-layout/gio-widget-layout.component.scss
Labels: apply-on-4-9-x

#13359 chore: bump ui-particles to fix image size in the subscription dropdown of the application
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#13398 fix: [Portal-Next] Top nav bar buttons shifting when clicking
  gravitee-apim-portal-webui-next/src/components/nav-bar/nav-bar.component.scss
Labels: apply-on-master

#13360 ci: release helm chart in AWS ECR registry
  .circleci/ci/src/config.ts
  .circleci/ci/src/jobs/helm/job-release-helm.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release-helm/release-helm.yml
  release/ci-steps/release-helm.mjs
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#13319 fix: component scope with stack implementation
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/AbstractExecutionContext.java
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/ComponentScope.java
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/diagnostic/DiagnosticReportHelper.java
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/test/java/io/gravitee/gateway/reactive/core/context/diagnostic/DiagnosticReportHelperTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/SyncApiReactor.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/security/AbstractSecurityChain.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/security/SecurityChainDiagnostic.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/security/plan/AbstractSecurityPlan.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactor.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/security/SecurityChainDiagnosticTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-policy/src/main/java/io/gravitee/gateway/reactive/policy/AbstractPolicyChain.java
  pom.xml
Labels: apply-on-master

#13219 feat: add helm chart label on template metadata
  helm/templates/api/api-deployment.yaml
  helm/templates/gateway/gateway-deployment.yaml
  helm/templates/portal/portal-deployment.yaml
  helm/templates/ui/ui-deployment.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/gateway/deployment_test.yaml
  helm/tests/portal/deployment_test.yaml
  helm/tests/ui/deployment_test.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-9-x

#13365 feat: integrate kafka console with apim
  docker/quick-setup/kafka-console/.ssl/server.keystore.jks
  docker/quick-setup/kafka-console/.ssl/server.truststore.jks
  docker/quick-setup/kafka-console/README.md
  docker/quick-setup/kafka-console/docker-compose.yml
  gravitee-apim-console-webui/src/entities/consoleSettings.ts
  gravitee-apim-console-webui/src/management/clusters/list/cluster-list.component.html
  gravitee-apim-console-webui/src/management/clusters/list/cluster-list.component.scss
  gravitee-apim-console-webui/src/management/clusters/list/cluster-list.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/installation/EnvironmentResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/kafka_console/ProxyKafkaConsoleResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/ConsoleConfigEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/ConsoleSettingsEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/KafkaConsole.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
  helm/templates/_helpers.tpl
  helm/templates/api/api-configmap.yaml
  helm/templates/kafkaConsole/kafkaConsole-autoscaler.yaml
  helm/templates/kafkaConsole/kafkaConsole-deployment.yaml
  helm/templates/kafkaConsole/kafkaConsole-pdb.yaml
  helm/templates/kafkaConsole/kafkaConsole-service.yaml
  helm/tests/api/deployment_kafkaConsole_test.yaml
  helm/tests/kafkaConsole/autoscaler_test.yaml
  helm/tests/kafkaConsole/deployment_probes_test.yaml
  helm/tests/kafkaConsole/deployment_test.yaml
  helm/tests/kafkaConsole/pdb_test.yaml
  helm/tests/kafkaConsole/service_test.yaml
  helm/values.yaml
Labels: apply-on-master

#13431 feat: add helm chart label on template metadata
  helm/templates/api/api-deployment.yaml
  helm/templates/gateway/gateway-deployment.yaml
  helm/templates/portal/portal-deployment.yaml
  helm/templates/ui/ui-deployment.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/gateway/deployment_test.yaml
  helm/tests/portal/deployment_test.yaml
  helm/tests/ui/deployment_test.yaml
Labels: apply-on-4-5-x, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-9-x

#13437 fix: publish / unpublish page - 500 resp fix
  gravitee-apim-console-webui/src/portal/homepage/homepage.component.spec.ts
  gravitee-apim-console-webui/src/portal/homepage/homepage.component.ts
  gravitee-apim-console-webui/src/services-ngx/portal-pages.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/portal-pages.service.ts
Labels: apply-on-master

#13371 fix: Request Timeout issue in V4
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/main/java/io/gravitee/plugin/endpoint/http/proxy/HttpProxyEndpointConnector.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/main/java/io/gravitee/plugin/endpoint/http/proxy/HttpProxyEndpointConnectorFactory.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/test/java/io/gravitee/plugin/endpoint/http/proxy/HttpProxyEndpointConnectorTest.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/test/java/io/gravitee/plugin/endpoint/http/proxy/connector/HttpConnectorTest.java
Labels: apply-on-4-5-x, apply-on-master, run-e2e-tests, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-9-x

#13470 make portal next homepage public
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/PortalPagesResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
Labels: apply-on-master

#13465 chore(deps): bump gravitee-policy-kafka-topic-mapping to 1.3.1
  pom.xml
Labels: apply-on-4-7-x, apply-on-4-8-x

#13419 fix: copy all scripts before updating permissions
  gravitee-apim-portal-webui/docker/Dockerfile
Labels: apply-on-master

#13485 fix(test):fix tests for opensearch and events
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/AnatlyticsDatabase.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/DatabaseHydrator.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/TestConfiguration.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/analytics/AnalyticsElasticsearchRepositoryTest.java
  pom.xml
Labels: apply-on-master

#13494 feat: remove backtics of NewtAI responses
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/newtai/NewtAIProviderImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/newtai/NewtAIProviderImplTest.java
Labels: apply-on-master

#13501 fix: clean permission and owner in docker images
  gravitee-apim-portal-webui/docker/Dockerfile
Labels: apply-on-master
