Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-02, with the labels that each got.

#10605 test(mongodb): fix mongo encryption test
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/java/io/gravitee/repository/mongodb/MongoTestRepositoryConfiguration.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/resources/graviteeTest.yml
Labels: apply-on-master

#10615 fix: bump entrypoint-webhook version to 3.1.2
  pom.xml
Labels: apply-on-4-5-x

#10612 fix(helm): add missing fields for kafka
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_kafka_test.yaml
  helm/values.yaml
Labels: apply-on-master

#10617 fix: bump reporter elasticsearch version
  pom.xml
Labels: apply-on-master, apply-on-4-6-x

#10616 fix: bump reporter elasticsearch version
  pom.xml
Labels: apply-on-4-4-x

#10629 fix(helm): update changelog
  helm/CHANGELOG.md
  helm/Chart.yaml
Labels: apply-on-master

#10628 fix: Access public APIs listed in a category when user logged out
  gravitee-apim-e2e/api-test/src/portal/mapi-v1/portal-api-view-and-search.spec.ts
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/test/java/io/gravitee/gateway/reactive/debug/DebugReactorEventListenerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceNotAuthenticatedTest.java
Labels: apply-on-4-5-x, apply-on-4-4-x, run-e2e-tests, apply-on-4-6-x

#10636 fix: access public APIs listed in a category when user is logged out
  gravitee-apim-e2e/api-test/src/portal/mapi-v1/portal-api-view-and-search.spec.ts
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/test/java/io/gravitee/gateway/reactive/debug/DebugReactorEventListenerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApisResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApisResourceNotAuthenticatedTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/category/use_case/GetCategoryApisUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/category/use_case/GetCategoryApisUseCaseTest.java
Labels: apply-on-4-5-x, apply-on-master, run-e2e-tests, apply-on-4-6-x

#10639 fix: declare MediaQueryService for InMemory config
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/query_service/media/MediaQueryServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/spring/InMemoryConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_SearchTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiSearchService_SearchTest.java
Labels: run-e2e-tests

#10599 fix: text overflow in documentation containers
  gravitee-apim-console-webui/src/components/documentation/page/_page.scss
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-edit-page/documentation-edit-page.component.scss
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-documentation/api-tab-documentation.component.scss
  gravitee-apim-portal-webui-next/src/components/page/page-markdown/page-markdown.component.scss
  gravitee-apim-portal-webui/src/app/components/gv-page-markdown/gv-page-markdown.component.css
Labels: apply-on-4-5-x, apply-on-master, ready_to_test, apply-on-4-6-x

#10660 fix: bump kube client and node
  pom.xml
Labels: apply-on-4-6-x

#10656 APIM 8631-revert old commit and add null check for security config
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/plan/model/PlanUpdates.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/plan/use_case/UpdatePlanUseCaseTest.java
Labels: apply-on-master, ready_to_test

#10652 fix(helm): mapping of user.anonymize-on-delete.enabled
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-configmap.yaml
  helm/values.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#10646 feat(helm): remove nginx configuration-snippet by default
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/values.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#10681 fix: bump node to 7.0.5
  pom.xml
Labels: apply-on-4-6-x

#10685 feat: improve ContextAttributeMap with enableGraviteePrefix and fallbackContextAttributeMap options
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/ContextAttributeMap.java
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/test/java/io/gravitee/gateway/reactive/core/context/ContextAttributeMapTest.java
Labels: apply-on-master

#10687 chore: bump kafka gateway dependencies
  pom.xml
Labels: apply-on-master

#10691 update supported version of mongo in APIM
  .circleci/ci/src/workflows/workflow-repositories-tests.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#10550 feat(console): change top APIs to featured APIs in console nav
  gravitee-apim-console-webui/src/management/settings/settings-navigation/settings-navigation.service.spec.ts
  gravitee-apim-console-webui/src/management/settings/settings-navigation/settings-navigation.service.ts
  gravitee-apim-console-webui/src/management/settings/top-apis/top-apis.component.html
Labels: run-e2e-tests

#10715 fix(helm): update cache & cluster plugin version
  helm/tests/api/deployment_federation_test.yaml
  helm/values.yaml
Labels: apply-on-4-6-x

#10710 CI - add TriggerSaasDockerImagesJob for dev latest release
  .circleci/ci/src/jobs/job-trigger-saas-docker-images.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/workflows/workflow-full-release.ts
  .circleci/ci/src/workflows/workflow-pull-requests.ts
Labels: apply-on-master

#10723 chore: no dry-run for TriggerSaasDockerImagesJob when run on master and support branches
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/workflows/workflow-pull-requests.ts
Labels: apply-on-master

#10720 Apim 8612 update documentation of management organization groups memberberships
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/GroupResource.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-6-x

#10689 fix: export analytics logs in csv format
  gravitee-apim-console-webui/src/management/analytics/logs/platform-logs.controller.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#10716 fix: display uuid of groups in paginated view
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApplicationRepository.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApplicationsResourceTest.java
Labels: apply-on-master, apply-on-4-6-x

#10777 fix(deps): bump gravitee/nginx to 1.27.4
  gravitee-apim-console-webui/docker/Dockerfile
  gravitee-apim-console-webui/docker/Dockerfile-from-download
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/Dockerfile-from-download
Labels: run-e2e-tests, apply-on-4-6-x

#10757 fix(analytics): correct status pie-chart data display
  gravitee-apim-console-webui/src/components/dashboard/widget/widget.component.ts
  gravitee-apim-console-webui/src/components/logs/logs-filters.controller.ts
Labels: apply-on-4-5-x, apply-on-master, ready_to_test, apply-on-4-4-x, apply-on-4-6-x

#10805 fix: add quotes for kafka config
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_kafka_test.yaml
Labels: apply-on-master

#10658 fix(portal): persist HTTP status criteria after search validation
  gravitee-apim-portal-webui/src/app/components/gv-analytics-filters/gv-analytics-filters.component.ts
Labels: apply-on-4-5-x, apply-on-master, ready_to_test, apply-on-4-4-x, apply-on-4-6-x

#10795 fix: Issue with Webhook notifications - Lifecycle status changing
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/spring/ServiceConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiNotificationServiceImpl.java
Labels: apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#10847 chore: bump gravitee-plugin
  pom.xml
Labels: apply-on-master

#10863 fix: do not index User custom fields containing base64 image
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/UserDocumentTransformer.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/UserDocumentTransformerTest.java
Labels: apply-on-4-5-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x
