Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-06, with the labels that each got.

#11905 fix: preserve numeric value '1' in custom metrics widgets
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AnalyticsServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/AnalyticsServiceImplTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#11976 chore: move gravitee-policy-ai-prompt-token-tracking in OSS profile
  gravitee-apim-distribution/pom.xml
Labels: apply-on-master

#11991 chore: update policy-ai-tracking to 1.0.0-alpha.3
  pom.xml
Labels: apply-on-4-8-x

#12009 Remove external reference from openapi-environments file
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-environments.yaml
Labels: apply-on-master, apply-on-4-8-x

#12021 fix: safely unwrap response headers when disabled for logging
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/analytics/logging/LoggingHook.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12030 chore(deps): update gravitee-policy-retry.version to 2.1.4
  pom.xml
Labels: apply-on-4-5-x

#12047 fix(helm): update default log file path
  helm/Chart.yaml
  helm/templates/api/api-configmap.yaml
  helm/tests/api/configmap_logback_yaml_test.yaml
  helm/values.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12075 feat(deps): add gravitee-policy-kafka-message-filtering dependency
  gravitee-apim-distribution/pom.xml
  pom.xml
Labels: apply-on-4-8-x

#12077 Portal-next: finish the mcp implementation
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-details.component.html
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-details.component.scss
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-details.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-details.component.ts
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-tools/api-tab-tools.component.html
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-tools/api-tab-tools.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/api/api-details/api-tab-tools/api-tab-tools.component.ts
  gravitee-apim-portal-webui-next/src/app/catalog/components/apis-list/apis-list.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/catalog/components/apis-list/apis-list.component.ts
  gravitee-apim-portal-webui-next/src/assets/images/mcp.svg
  gravitee-apim-portal-webui-next/src/components/api-card/api-card.component.html
  gravitee-apim-portal-webui-next/src/components/api-card/api-card.component.ts
  gravitee-apim-portal-webui-next/src/components/api-card/api-card.harness.ts
  gravitee-apim-portal-webui-next/src/entities/api/api.fixtures.ts
  gravitee-apim-portal-webui-next/src/entities/api/mcp.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ApiMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/portal-openapi.yaml
Labels: apply-on-4-8-x

#12028 fix(console): a2a configurations UI
  gravitee-apim-console-webui/src/management/api-score/rulesets/ruleset-format-mapper.pipe.ts
  gravitee-apim-console-webui/src/management/api/creation-v4/steps/step-2-entrypoints/step-2-entrypoints-2-config.component.ts
  gravitee-apim-console-webui/src/management/integrations/integration-configuration/general/integration-general-configuration.component.html
  gravitee-apim-console-webui/src/management/integrations/integration-configuration/general/integration-general-configuration.component.scss
  gravitee-apim-console-webui/src/management/integrations/integration-configuration/general/integration-general-configuration.component.spec.ts
  gravitee-apim-console-webui/src/management/integrations/integration-configuration/general/integration-general-configuration.component.ts
  gravitee-apim-console-webui/src/management/integrations/integration-configuration/general/integration-general-configuration.harness.ts
  gravitee-apim-console-webui/src/management/integrations/integrations.model.ts
Labels: apply-on-4-8-x

#12099 fix(console):fix naming for a2a integration configuration
  gravitee-apim-console-webui/src/management/integrations/integration-configuration/general/integration-general-configuration.component.html
Labels: apply-on-4-8-x

#12089 feat: enable skip Xms and Xmx with GIO_DISABLE_STARTING_MEMORY
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/bin/gravitee
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/bin/gravitee.bat
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/bin/gravitee
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/bin/gravitee.bat
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12015 Extra / is added in Context path in V4 API
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiEntrypointServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiEntrypointServiceImplTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-8-x

#12120 fix(console): initialize default API and application roles in the email invitation dialog
  gravitee-apim-console-webui/src/management/settings/groups/group/group.component.spec.ts
  gravitee-apim-console-webui/src/management/settings/groups/group/invite-member-dialog/invite-member-dialog.component.ts
Labels: apply-on-4-8-x

#12122 fix(console): correction in the label of the integration role column in org settings
  gravitee-apim-console-webui/src/organization/configuration/user/detail/org-settings-user-detail.component.html
Labels: apply-on-4-8-x

#12125 fix(deps): update gravitee-policy-kafka-message-filtering dependency to include runtime scope and exclusions
  gravitee-apim-distribution/pom.xml
Labels: apply-on-4-8-x

#12135 fix(deps): bump ai policies to latest alpha
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/pom.xml
  pom.xml
Labels: apply-on-master

#12083 fix: use apim.example.com as automation ingress host
  helm/values.yaml
Labels: apply-on-4-8-x

#12157 chore(deps): bump policy-ipfiltering to 1.19.1
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-7-x, apply-on-4-8-x

#12053 fix: display error msg when deleting a non-empty folder
  gravitee-apim-console-webui/src/components/documentation/documentation-management.component.ajs.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12017 chore: add inference service dependency and bump up ai-model-text-classification version
  gravitee-apim-distribution/pom.xml
  pom.xml
Labels: apply-on-master

#12171 fix(helm): use '-' in dictionary multi-tenant name
  helm/templates/gateway/gateway-configmap.yaml
  helm/tests/gateway/configmap_test.yaml
  helm/values.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#12180 fix: align application template metadata and notification styles
  gravitee-apim-console-webui/src/components/gio-metadata/gio-metadata.component.html
  gravitee-apim-console-webui/src/components/gio-metadata/gio-metadata.component.scss
  gravitee-apim-console-webui/src/components/notification/notification-list/notification-list.component.html
  gravitee-apim-console-webui/src/components/notification/notification-list/notification-list.component.scss
Labels: apply-on-master

#12198 chore: bump kafka reactor
  pom.xml
Labels: apply-on-master

#12205 chore(console): bump particles dependency for theme improvements
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-4-8-x

#12209 chore: bump oas validation policy
  pom.xml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12210 chore(deps): update gravitee-policy-kafka-message-filtering version to 1.0.0-alpha.2
  pom.xml
Labels: apply-on-4-8-x

#12232 Bump alpha 4 8 plugins
  pom.xml
Labels: apply-on-master

#12238 fix(console): make a PUT of SPG send complete payload
  gravitee-apim-console-webui/src/entities/management-api-v2/sharedPolicyGroup/SharedPolicyGroup.fixture.ts
  gravitee-apim-console-webui/src/entities/management-api-v2/sharedPolicyGroup/SharedPolicyGroup.ts
  gravitee-apim-console-webui/src/entities/management-api-v2/sharedPolicyGroup/UpdateSharedPolicyGroup.fixture.ts
  gravitee-apim-console-webui/src/entities/management-api-v2/sharedPolicyGroup/UpdateSharedPolicyGroup.ts
  gravitee-apim-console-webui/src/management/settings/shared-policy-groups/shared-policy-group/shared-policy-group-studio/shared-policy-group-studio.component.spec.ts
  gravitee-apim-console-webui/src/management/settings/shared-policy-groups/shared-policy-group/shared-policy-group-studio/shared-policy-group-studio.component.ts
Labels: apply-on-4-8-x

#12245 chore: bump policy-kafka-topic-mapping
  pom.xml
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12291 chore: remove gravitee-inference service from MAPI distribution
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/assembly/plugin-assembly-distribution.xml
Labels: apply-on-master

#12295 Revert "refactor: rename context creation methods for clarity"
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/v4/analytics/AnalyticsContext.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactor.java
Labels: run-e2e-tests

#12256 fix: pagination on portal UI subscription tab of applicaiton
  gravitee-apim-portal-webui/src/app/pages/application/application-subscriptions/application-subscriptions.component.css
  gravitee-apim-portal-webui/src/app/pages/application/application-subscriptions/application-subscriptions.component.html
  gravitee-apim-portal-webui/src/app/pages/application/application-subscriptions/application-subscriptions.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/SubscriptionResourceTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, run-e2e-tests, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12314 fix: fix list items and pagesize equal issue for pagesize 5
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/AbstractResource.java
Labels: run-e2e-tests, apply-on-4-6-x

#12345 fix: updates reporters
  pom.xml
Labels: apply-on-master

#12312 fix: Increase character limit of condition field in flow_selectors table
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_32/00_change_flow_selectors_condition_length.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x
