Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-08, with the labels that each got.

#12677 fix: adjust debug mode timeline legend styling to handle text wrapping
  gravitee-apim-console-webui/src/management/api/debug-mode/components/debug-mode-timeline-legend/debug-mode-timeline-legend.component.scss
Labels: apply-on-master

#12686 ci: use local maven repository [skip ci]
  .circleci/ci/src/jobs/test-container/abstract-job-test-container.ts
  .circleci/ci/src/pipelines/tests/resources/repositories-tests/repositories-tests.yml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12692 chore: use new central sonatype for snapshots
  pom.xml
Labels: apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12714 fix: app client_id unicity check uses status
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApplicationRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/ApplicationRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/application-tests/applications.json
Labels: apply-on-4-5-x, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12716 fix: bump mcp entrypoint
  pom.xml
Labels: apply-on-master

#12773 fix: reindex API after ownership transfer to prevent stale search results
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_AddRoleToMemberOnReferenceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_CreateNewMembershipForApiTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_DeleteMemberTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_EditMemberTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_FindUserMembershipMetadataTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_FindUserMembershipTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_GetMemberPermissionsTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_GetMembersTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_GetMembershipsTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_GetUserMemberTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_IntegrationMembership.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_TransferOwnershipTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_UpdateMembershipForApiTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12793 chore: bump gravitee-common-elasticsearch and gravitee-reporter-elasticsearch version
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/pom.xml
  pom.xml
Labels: run-e2e-tests

#12796 Dependencies upgrade
  pom.xml
Labels: apply-on-master

#12821 chore(deps): bump policy-oas-validation and endpoint-rabbitmq versions
  pom.xml
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12823 fix(console-ui): CSS issues on application logs page
  gravitee-apim-console-webui/src/index.scss
  gravitee-apim-console-webui/src/management/application/details/logs/application-log.html
  gravitee-apim-console-webui/src/management/application/details/logs/application-log.scss
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12836 Revert "chore: bump kafka endpoint"
  pom.xml
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12856 fix: bump kafka endpoint for protocol mediation
  pom.xml
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12903 fix: safely handle orphaned gateway events to prevent UI crash
  gravitee-apim-console-webui/src/entities/instance/instanceListItem.ts
  gravitee-apim-console-webui/src/management/instances/instance-list/instance-list.component.spec.ts
  gravitee-apim-console-webui/src/management/instances/instance-list/instance-list.component.ts
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12915 Fix flaky E2E test exposing a concurrency issue when closing plans
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/PlanRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcPlanRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoPlanRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/plan/PlanMongoRepositoryCustom.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/plan/PlanMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-noop/src/main/java/io/gravitee/repository/noop/management/NoOpPlanRepository.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/PlanRepositoryTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/PlanServiceImpl.java
Labels: apply-on-4-5-x, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12917 fix: preserve flowExecution.matchRequired when importing V4 API definitions
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/model/import_definition/ApiExport.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/ImportApiDefinitionUseCaseTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-8-x

#12897 fix: allow an ADMIN environment role to view newly created documentation pages
  gravitee-apim-console-webui/src/management/settings/settings-navigation/settings-navigation.service.spec.ts
  gravitee-apim-console-webui/src/management/settings/settings-navigation/settings-navigation.service.ts
  gravitee-apim-console-webui/src/management/settings/settings-routing.module.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PortalPagesResource.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-8-x

#12973 fix: make the Primary Owner group field selectable during v2 API creation
  gravitee-apim-console-webui/src/management/api/creation-v2/steps/api-creation-step1-component.spec.ts
  gravitee-apim-console-webui/src/management/api/creation-v2/steps/api-creation-step1.component.ts
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x
