Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-01, with the labels that each got.

#10240 fix: remove duplicate of
  gravitee-apim-portal-webui-next/src/app/api/subscribe-to-api/subscribe-to-api-choose-plan/subscribe-to-api-choose-plan.component.html
Labels: apply-on-master

#10239 fix: ScramLoginModule is a scram package not plain
  gravitee-apim-portal-webui-next/src/components/api-access/native-kafka-api-access/native-kafka-api-access.component.ts
Labels: apply-on-master

#10248 feat: clean up relevant `FIXME: Kafka Gateway` added at the beginning
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/installation/Create Native API.http
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/installation/EnvironmentResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/installation/NativeEventsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-plugins.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/use_case/OAIToImportApiUseCase.java
Labels: apply-on-master

#10232 feat: handle subscriptions and apikeys in local sync
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/local/mapper/ApiKeyMapper.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/local/mapper/ApiMapper.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/local/mapper/SubscriptionMapper.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/local/model/LocalSyncFileDefinition.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/local/spring/LocalSyncConfiguration.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/local/synchronizer/LocalApiSynchronizer.java
Labels: apply-on-master

#10211 fix: flaky IT tests
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/secrets/api/v4/KubernetesHttpProxyHeaderSecretTest.java
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/secrets/conf/KubernetesSecretProviderIntegrationTest.java
  pom.xml
Labels: apply-on-master

#10166 fix: search for TemplateVariableProviderFactory including ancestors
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/AbstractReactorFactory.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactorFactoryTest.java
Labels: apply-on-4-6-x

#10268 fix: bump gravitee-plugin
  pom.xml
Labels: apply-on-master

#10291 fix: bump gravitee-plugin
  pom.xml
Labels: apply-on-master

#10292 chore(deps): bump gravitee-gateway-api to 3.9.1
  pom.xml
Labels: apply-on-master

#10287 chore: bump http-get and http-post entrypoints version
  pom.xml
Labels: apply-on-master, ready_to_test

#10297 chore(deps): bump gravitee-reactor-native-kafka to 1.2.1
  pom.xml
Labels: apply-on-master

#10300 fix(deps): bump ui-particles to 13.9.1
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-master

#10222 feat: add secret support for http proxy endpoint
  gravitee-apim-definition/gravitee-apim-definition-model/pom.xml
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/http/HttpProxyOptions.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/jks/JKSKeyStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/jks/JKSTrustStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/pem/PEMKeyStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/pem/PEMTrustStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/pkcs12/PKCS12KeyStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/pkcs12/PKCS12TrustStore.java
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/http/secrets/SecretsV4IntegrationTest.java
  gravitee-apim-integration-tests/src/test/resources/apis/v4/http/secrets/api-secured-jks-password-secret-static-ref.json
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/README.adoc
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/pom.xml
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/main/java/io/gravitee/plugin/endpoint/http/proxy/HttpProxyEndpointConnectorFactory.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/main/java/io/gravitee/plugin/endpoint/http/proxy/configuration/HttpProxyEndpointConnectorConfiguration.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/main/java/io/gravitee/plugin/endpoint/http/proxy/configuration/HttpProxyEndpointConnectorSharedConfiguration.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/test/java/io/gravitee/plugin/endpoint/http/proxy/HttpProxyEndpointConnectorFactoryTest.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/test/java/io/gravitee/plugin/endpoint/http/proxy/HttpProxyEndpointConnectorTest.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/test/java/io/gravitee/plugin/endpoint/http/proxy/client/HttpClientFactoryTest.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/test/java/io/gravitee/plugin/endpoint/http/proxy/connector/HttpConnectorTest.java
Labels: apply-on-master

#10314 chore: bump oauth-resource-generic
  pom.xml
Labels: apply-on-master

#10321 refactor execution context
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/AbstractBaseExecutionContext.java
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/AbstractExecutionContext.java
Labels: apply-on-master

#10318 chore: bump repository bridge
  pom.xml
Labels: apply-on-master

#10320 fix: bump reactor-native-kafka
  pom.xml
Labels: apply-on-master

#10327 fix: format is not mandatory
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-environments.yaml
Labels: apply-on-4-5-x, apply-on-4-6-x

#10332 Fix EL in KafkaGateway - access API properties
  pom.xml
Labels: apply-on-master

#10333 fix: bump bridge with fixed version
  pom.xml
Labels: apply-on-master

#10330 fix: bump gravitee-endpoint-kafka to 4.0.0
  pom.xml
Labels: apply-on-4-6-x

#10354 fix: remove required constraint from ImportScoringRuleset description
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-environments.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/environment/EnvironmentScoringRulesetsResourceTest.java
Labels: apply-on-4-5-x, apply-on-master

#10326 feat(helm): improve api and gateway scalability configuration
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-autoscaler.yaml
  helm/templates/gateway/gateway-autoscaler.yaml
  helm/templates/portal/portal-autoscaler.yaml
  helm/templates/ui/ui-autoscaler.yaml
  helm/tests/api/autoscaler_test.yaml
  helm/tests/gateway/autoscaler_test.yaml
  helm/tests/portal/autoscaler_test.yaml
  helm/tests/ui/autoscaler_test.yaml
  helm/values.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#10356 fix(deps): update gravitee-endpoint-kafka to 4.0.1
  pom.xml
Labels: apply-on-master, run-e2e-tests

#10364 fix(gateway): fix memory leak on acceptors while deploy and undeploy API
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/SyncApiReactor.java
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/reactive/debug/handlers/api/DebugSyncApiReactor.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x

#10372 fix: bump gravitee plugin
  pom.xml
Labels: apply-on-master

#10352 Apim 7444 enable documentation mode for portal
  gravitee-apim-console-webui/src/entities/portal/portalSettings.fixture.ts
  gravitee-apim-console-webui/src/entities/portal/portalSettings.ts
  gravitee-apim-console-webui/src/management/settings/api-portal-header/api-portal-header.component.spec.ts
  gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.html
  gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/parameters/Key.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/Portal.java
Labels: apply-on-master

#10366 fix: update connector http version
  pom.xml
Labels: apply-on-4-5-x

#10365 fix: update connector http version
  pom.xml
Labels: apply-on-4-3-x

#10367 fix: update connector http version
  pom.xml
Labels: apply-on-master

#10379 fix(deps): update gravitee-connector-kafka to 1.1.2
  pom.xml
Labels: apply-on-master

#10389 Try to fix sqlserver 2017 repo tests
  .circleci/ci/src/executors/executor-ubuntu.ts
  .circleci/ci/src/jobs/test-container/job-jdbc-test-container.ts
  .circleci/ci/src/pipelines/tests/resources/repositories-tests/repositories-tests.yml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x

#10353 test: add integration test using Kafka endpoint and secret
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/messages/httpget/HttpGetEntrypointKafkaEndpointIntegrationTest.java
  gravitee-apim-integration-tests/src/test/resources/apis/v4/messages/http-get/http-get-entrypoint-kafka-endpoint-secret.json
Labels: apply-on-master

#10400 fix(portal-next): remove sign up button
  gravitee-apim-portal-webui-next/src/components/nav-bar/nav-bar.component.html
Labels: apply-on-master

#10391 fix(deps): upgrade gravity-policy-groovy to 3.0.1
  pom.xml
Labels: apply-on-master, run-e2e-tests

#10408 fix: bump dependencies to fix security issues
  pom.xml
Labels: apply-on-master

#10404 feat: APIM 7444 enable documentation only mode in portal
  gravitee-apim-portal-webui/projects/portal-webclient-sdk/src/lib/model/configurationPortalApis.ts
  gravitee-apim-portal-webui/src/app/app-routing.module.ts
  gravitee-apim-portal-webui/src/app/app.component.ts
  gravitee-apim-portal-webui/src/app/components/gv-header-item/gv-header-item.component.ts
  gravitee-apim-portal-webui/src/app/services/feature-guard.service.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ConfigurationMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/portal-openapi.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/expectedPortalConfiguration.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/resources/io/gravitee/rest/api/portal/rest/mapper/portalSettingsEntity.json
Labels: apply-on-master

#10398 fix: export should set the type
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/GraviteeDefinitionAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/api/ApiExportDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/api/ApiExportDomainServiceImplTest.java
Labels: apply-on-4-6-x

#10423 Fix aws-cli version for APIM release
  .circleci/ci/src/config.ts
  .circleci/ci/src/jobs/job-package-bundle.ts
  .circleci/ci/src/orbs/aws-cli.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-no-dry-run.yml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x

#10410 Bump reactor-kafka
  pom.xml
Labels: apply-on-master

#10434 chore: bump graphql-rate-limit policy
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#10433 chore: remove old connector-kafka plugin
  gravitee-apim-distribution/pom.xml
  gravitee-apim-integration-tests/pom.xml
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#10435 Make elastic tests independent of the time
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/DatabaseHydrator.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/TestConfiguration.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/TimeProvider.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/analytics/ElasticsearchAnalyticsRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/log/LogElasticsearchRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/resources/freemarker/health.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/resources/freemarker/log.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/resources/freemarker/monitor.ftl
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/resources/freemarker/request.ftl
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#10203 feat: update first step of creation screen
  gravitee-apim-console-webui/src/management/api/creation-get-started/api-creation-get-started.component.html
  gravitee-apim-console-webui/src/management/api/creation-get-started/api-creation-get-started.component.spec.ts
  gravitee-apim-console-webui/src/management/api/creation-get-started/api-creation-get-started.component.ts
Labels: apply-on-master

#10450 feat(portal): add Montserrat font to portal
  gravitee-apim-console-webui/src/management/settings/portal-theme/portalTheme.controller.ts
  gravitee-apim-portal-webui/package.json
  gravitee-apim-portal-webui/src/styles.scss
  gravitee-apim-portal-webui/yarn.lock
Labels: apply-on-master

#10444 allow users to handle properly baseUrl in portal next for multi tenant installations
  helm/Chart.yaml
  helm/templates/portal/portal-configmap.yaml
  helm/templates/portal/portal-deployment.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x

#10461 chore: bumb gravitee-policy-json-validation to 2.0.2
  pom.xml
Labels: apply-on-master

#10075 feat: upgrade jdk version
  .circleci/ci/src/config.ts
  .circleci/ci/src/pipelines/tests/resources/bridge-compatibility-tests/bridge-compatibility-tests.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/nexus-staging/nexus-staging-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/publish-docker-images/publish-docker-images-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-distribution-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-gateway-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-integration-tests-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-plugin-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch-backend-rest-api-only.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-custom-branch.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-mergify.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-run-e2e.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/release/release-4-2-0-snapshot.yml
  .circleci/ci/src/pipelines/tests/resources/repositories-tests/repositories-tests.yml
  .circleci/ci/src/pipelines/tests/resources/run-e2e-tests/run-e2e-tests.yml
  gravitee-apim-gateway/docker/Dockerfile
  gravitee-apim-gateway/docker/Dockerfile-from-download
  gravitee-apim-rest-api/docker/Dockerfile
  gravitee-apim-rest-api/docker/Dockerfile-from-download
  pom.xml
Labels: run-e2e-tests

#10478 feat(mapi-v2): asciidoc page can be created
  gravitee-apim-console-webui/src/entities/management-api-v2/documentation/pageType.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/api-documentation-v4-add-page-button/api-documentation-v4-add-page-button.component.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/api-documentation-v4-content-editor/api-documentation-v4-content-editor.component.html
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/api-documentation-v4-content-editor/api-documentation-v4-content-editor.component.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-new-page/documentation-new-page.component.ts
  gravitee-apim-console-webui/src/services-ngx/api-documentation-v2.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/api-documentation-v2.service.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/mapper/PageMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/documentation/ApiPagesResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/documentation/ApiPagesResourceTest.java
Labels: run-e2e-tests

#10480 fix: export API CRD plan flows
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/mapper/ApiCRDMapper.java
Labels: apply-on-4-6-x

#10497 chore(deps): bump connector-http to 4.0.6
  pom.xml
Labels: apply-on-4-5-x

#10498 Apim 8141 bump connector
  pom.xml
Labels: apply-on-master

#10502 fix: dictionnary EL var not found
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/AbstractGatewayTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/DictionaryDeployer.java
  gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/GatewayRunner.java
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/el/ELIntegrationTest.java
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/secrets/api/v4/VaultHttpProxyHeaderSecretTest.java
  gravitee-apim-integration-tests/src/test/resources/apis/v4/el/api-with-ELs.json
  pom.xml
Labels: apply-on-master

#10534 chore: bump gateway-api
  pom.xml
Labels: apply-on-master

#10491 fix: add transaction on mongo
  docker/quick-setup/consul-service-discovery/docker-compose.yml
  docker/quick-setup/ee-with-alert-engine/docker-compose.yml
  docker/quick-setup/eureka-service-discovery/docker-compose.yml
  docker/quick-setup/gateway-http-bridge-repository/.env
  docker/quick-setup/gateway-http-bridge-repository/docker-compose.yml
  docker/quick-setup/https-gateway/docker-compose.yml
  docker/quick-setup/https-nginx/docker-compose.yml
  docker/quick-setup/keycloak/docker-compose.yml
  docker/quick-setup/kibana/docker-compose.yml
  docker/quick-setup/mongodb/docker-compose.yml
  docker/quick-setup/native-kafka/docker-compose.yml
  docker/quick-setup/nginx/docker-compose.yml
  docker/quick-setup/opensearch/docker-compose.yml
  docker/quick-setup/opentelemetry-jaeger-tls/docker-compose.yml
  docker/quick-setup/opentelemetry-jaeger/docker-compose.yml
  docker/quick-setup/prometheus/docker-compose.yml
  docker/quick-setup/redis-rate-limit/docker-compose.yml
  docker/quick-setup/systemProxy/docker-compose.yml
  docker/quick-setup/tags-internal-external/docker-compose.yml
  docker/quick-setup/tcp/docker-compose.yml
  gravitee-apim-bom/pom.xml
  gravitee-apim-e2e/docker/common/docker-compose-mongo.yml
  gravitee-apim-repository/gravitee-apim-repository-mongodb/README.md
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/common/AbstractRepositoryConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/pom.xml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/UseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/TransactionRetryableService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TransactionalService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/spring/ServiceConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
  pom.xml
Labels: run-e2e-tests

#10594 feat(helm): add kubernetes access account token projection support
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-deployment.yaml
  helm/templates/gateway/gateway-deployment.yaml
  helm/tests/api/deployment_test.yaml
  helm/tests/gateway/deployment_test.yaml
  helm/values.yaml
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x
