Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-07, with the labels that each got.

#12018 feat(helm): add custom ingress capability for federation
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-ingress-federation-controller.yaml
  helm/tests/api/ingress_federationcontroller_test.yaml
  helm/values.yaml
Labels: apply-on-4-8-x

#12350 fix: restructure analytics schemas to avoid cyclic dependency
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
Labels: run-e2e-tests

#12360 fix(console): import `tinycolor` directly from package
  gravitee-apim-console-webui/src/app.module.ajs.ts
Labels: apply-on-master

#12356 fix: show all accessible applications when subscribing, including group-inherited ones
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationServiceImplTest.java
Labels: apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12373 fix: update gravitee parent
  gravitee-apim-gateway/pom.xml
  pom.xml
Labels: apply-on-master, apply-on-4-8-x

#12387 fix: show all accessible applications when subscribing, including group-inherited ones
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/test/java/io/gravitee/rest/api/portal/rest/resource/ApplicationsResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/ApplicationService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
Labels: apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12402 Revert - feat(federation): define full configuration of federation ingress
  helm/CHANGELOG.md
  helm/Chart.yaml
  helm/templates/api/api-ingress-federation-controller.yaml
  helm/tests/api/ingress_federationcontroller_test.yaml
Labels: apply-on-4-5-x, apply-on-4-6-x, apply-on-4-7-x

#12412 fix(standalone): removed Slf4j usages
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-bootstrap/src/main/java/io/gravitee/rest/api/standalone/boostrap/Bootstrap.java
Labels: run-e2e-tests

#12403 fix(console): invalidate role caches when updating group default roles
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12423 chore: bump gravitee-policy-mock to 1.14.2
  pom.xml
Labels: apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12435 Adapt cloud distribution trigger for debian images
  .circleci/ci/src/jobs/job-trigger-saas-docker-images.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-4-1-x.yml
  .circleci/ci/src/pipelines/tests/resources/pull-requests/pull-requests-master.yml
Labels: apply-on-master

#12324 fix: add validation for cron in page source during import to prevent malformed cron expressions
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/InvalidFetchCronExpressionException.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/PageService_CreateTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/import/import-api.invalid.cron.json
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12440 ci: updating changelog path
  release/ci-steps/generate-changelog.mjs
Labels: apply-on-master

#12474 chore(deps): update gravitee-policy-callout-http.version.version to 5…
  pom.xml
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12442 fix(console): Prevent timeout on API v2 creation by paginating groups scroller
  gravitee-apim-console-webui/jest.config.js
  gravitee-apim-console-webui/src/__mocks__/htmlLoaderMock.js
  gravitee-apim-console-webui/src/management/api/creation-v2/steps/api-creation-step1-component.spec.ts
  gravitee-apim-console-webui/src/management/api/creation-v2/steps/api-creation-step1.component.ts
  gravitee-apim-console-webui/src/management/api/creation-v2/steps/api-creation-step1.html
  gravitee-apim-console-webui/src/management/api/creation-v2/steps/api-creation-v2.component.ts
  gravitee-apim-console-webui/src/management/api/creation-v2/steps/api-creation-v2.controller.ajs.spec.ts
  gravitee-apim-console-webui/src/management/api/creation-v2/steps/api-creation-v2.controller.ajs.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12504 chore(console): bump ui-particles to 15.2.1
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-4-5-x, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12509 fix: handle tag removal when the environment contains V4 native APIs
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiTagServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/ApiTagServiceImplTest.java
Labels: apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12510 fix: expose CLIENT_ABORTED_DURING_RESPONSE_ERROR in alert UI dropdown
  gravitee-apim-console-webui/src/entities/gateway-error-keys/GatewayErrorKeys.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12498 fix: Portal Try it Out feature taking a long time to load
  gravitee-apim-console-webui/src/components/documentation/edit-tabs/edit-page-configuration.html
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-edit-page/documentation-edit-page.component.html
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-edit-page/documentation-edit-page.component.spec.ts
  gravitee-apim-console-webui/src/management/api/documentation-v4/components/documentation-edit-page/documentation-edit-page.component.ts
  gravitee-apim-portal-webui-next/src/components/page/page-swagger/page-swagger.component.ts
  gravitee-apim-portal-webui-next/src/entities/page/page-configuration.ts
  gravitee-apim-portal-webui/projects/portal-webclient-sdk/src/lib/model/pageConfiguration.ts
  gravitee-apim-portal-webui/src/app/components/gv-page-swaggerui/gv-page-swaggerui.component.ts
  gravitee-apim-portal-webui/tsconfig.json
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/PageRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/page-tests/pages.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/PageConfigurationKeys.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/PageMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/portal-openapi.yaml
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x

#12592 chore(deps): update gravitee-exchange to 1.8.5
  pom.xml
Labels: apply-on-master

#12613 fix: resolve potential memory leak by implementing equals/hashCode on SSL config classes
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/KeyStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/SslOptions.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/TrustStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/jks/JKSKeyStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/jks/JKSTrustStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/pem/PEMKeyStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/pem/PEMTrustStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/pkcs12/PKCS12KeyStore.java
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/v4/ssl/pkcs12/PKCS12TrustStore.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-7-x, apply-on-4-8-x

#12651 fix: set installation id when publishing health check Alert Event
  docker/quick-setup/ee-with-alert-engine/docker-compose.yml
  gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-healthcheck/src/main/java/io/gravitee/gateway/services/healthcheck/rule/EndpointRuleHandler.java
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-healthcheck-common/src/main/java/io/gravitee/plugin/apiservice/healthcheck/common/HealthCheckManagedEndpoint.java
  gravitee-apim-plugin/gravitee-apim-plugin-apiservice/gravitee-apim-plugin-apiservice-healthcheck-common/src/test/java/io/gravitee/plugin/apiservice/healthcheck/common/HealthCheckManagedEndpointTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#12642 fix(mapi): implement caching mechanism for CORS configurations
  gravitee-apim-rest-api/gravitee-apim-rest-api-security/src/main/java/io/gravitee/rest/api/security/cors/AbstractGraviteeUrlBasedCorsConfigurationSource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-security/src/test/java/io/gravitee/rest/api/security/cors/AbstractGraviteeUrlBasedCorsConfigurationSourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml
Labels: apply-on-master
