Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-04, with the labels that each got.

#11349 fix: Use Java Date instead of SQL now() for updated_at timestamp
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11360 fix(portal-next): mark global white-space for code tag as important t…
  gravitee-apim-portal-webui-next/src/scss/helper.scss
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#11377 fix: do not use cors methods in api v2 debug mode
  gravitee-apim-console-webui/src/management/api/policy-studio-v2/debug/components/policy-studio-debug-request/policy-studio-debug-request.component.ts
Labels: apply-on-master, apply-on-4-7-x

#11370 fix(service): only load context path for swagger page for v2 and v4 h…
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java
Labels: apply-on-master, apply-on-4-7-x

#11224 fix: add excluded groups validation on plan update
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/GroupService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/GroupServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/GroupService_FindAllTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/PlanService_UpdateTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11373 fix: disable searching members beyond max invitations limit in a group
  gravitee-apim-console-webui/src/management/settings/groups/group/add-members-dialog/add-members-dialog.component.ts
  gravitee-apim-console-webui/src/management/settings/groups/group/group.component.spec.ts
Labels: apply-on-4-7-x

#11388 fix: add excluded groups validation on plan update
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/jackson/ser/api/ApiSerializer.java
Labels: run-e2e-tests

#11391 fix: group handling is managed by the class itself
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/Application.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_CreateTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11358 fix(export): fix export of members, metadata & plans of APIs v4
  gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/Rule.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApisResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/model/import_definition/GraviteeDefinition.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/metadata/crud_service/MetadataCrudService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/GraviteeDefinitionAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/MemberAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/crud_service/metadata/MetadataCrudServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/api/ApiExportDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/inmemory/MetadataCrudServiceInMemory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/ExportApiUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/api/ApiExportDomainServiceImplTest.java
Labels: apply-on-master

#11408 fix: add excluded groups validation on v4 apis
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiPlansResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiPlansResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/PlanServiceImpl.java
Labels: apply-on-master, apply-on-4-7-x

#11273 fix: apply custom API key in API plan subscription when used
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiSubscriptionsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/fixtures/SubscriptionFixtures.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiSubscriptionsResourceTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11390 [UI BUG] Global Alert configuration does not refresh properly after change
  gravitee-apim-console-webui/src/components/alerts/alert/alert.component.ts
Labels: apply-on-4-5-x, apply-on-master, ready_to_test, apply-on-4-6-x, apply-on-4-7-x

#11428 fix:APIM-9123 Global Alert configuration does not refresh properly af…
  gravitee-apim-console-webui/src/components/alerts/alert/alert.component.ts
Labels: apply-on-master, ready_to_test

#11400 fix: restrict modification of Primary Owner role for applications
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_EditMemberTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MembershipService_UpdateMembershipForApiTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11444 chore(deps): bump gravitee-policy-ipfiltering to 1.18.1
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11387 fix: APIM-8604: Alert rate condition, removing the aggregation field does not trigger the UPDATE button
  gravitee-apim-console-webui/src/components/alerts/alert/triggers/projections/trigger-projections.component.ts
  gravitee-apim-console-webui/src/components/alerts/alert/triggers/trigger-metrics-rate.html
Labels: apply-on-master, ready_to_test, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11465 fix(gateway): enable jemalloc usage
  gravitee-apim-gateway/docker/Dockerfile
  gravitee-apim-gateway/docker/Dockerfile-from-download
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11466 chore(deps): update ipfiltering policy to v1.19.0
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11477 fix: improve role cache management
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11484 fix: add default group only at creation time
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/validation/ApiValidationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/validation/GroupValidationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/validation/GroupValidationService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/validation/ApiValidationServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/v4/impl/validation/GroupValidationServiceImplTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11489 fix(deps): bump redoc to 2.4.0
  gravitee-apim-portal-webui/package.json
  gravitee-apim-portal-webui/yarn.lock
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x

#11479 fix: APIM-9162: Dev portal - Application alert displays miss value after save
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
  gravitee-apim-portal-webui/package.json
  gravitee-apim-portal-webui/yarn.lock
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11502 fix: APIM-8604: Apply the fix also for the aggregated metrics
  gravitee-apim-console-webui/src/components/alerts/alert/triggers/trigger-metrics-aggregation.html
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11517 chore(deps): update ui-components version to 4.3.3
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-master, apply-on-4-7-x

#11520 fix(console): bump ui-particles
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-4-5-x

#11522 fix(console): bump ui-particles
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-master, apply-on-4-7-x

#11511 fix: reset hasBeenResumed flag to false in onResume()
  gravitee-apim-gateway/gravitee-apim-gateway-policy/src/main/java/io/gravitee/gateway/reactive/policy/adapter/context/RequestAdapter.java
Labels: apply-on-4-6-x, apply-on-4-7-x

#11531 chore(deps): update gravitee-connector-http to version 5.0.4
  pom.xml
Labels: apply-on-master, apply-on-4-7-x

#11538 fix: Logs filter display Unpublished plan
  gravitee-apim-console-webui/src/management/api/analytics/logs/analytics-logs.controller.ajs.ts
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11537 fix: add APIv4 plan validation
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApisResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/spring/ResourceContextConfiguration.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/domain_service/ValidateApiCRDDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/documentation/model/factory/PageModelFactory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/plan/domain_service/ValidatePlanDomainService.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/plan/model/factory/PlanModelFactory.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/ApiCRDAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/domain_service/ValidateApiCRDDomainServiceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/ImportApiCRDUseCaseTest.java
Labels: apply-on-master

#11562 fix: keep auto associations with groups for GKO apis
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/v4/impl/validation/ApiValidationServiceImpl.java
Labels: apply-on-master

#11536 fix: correct order for policy execution with jdbc
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcFlowRepository.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/FlowRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/FlowV4RepositoryTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11546 fix(service): return no apis on search if api authorization result empty
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/filtering/FilteringServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/FilteringServiceTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11580 fix: access settings page for message api
  gravitee-apim-console-webui/src/entities/portal/portalSettings.fixture.ts
  gravitee-apim-console-webui/src/entities/portal/portalSettings.ts
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs-settings/runtime-logs-message-settings/api-runtime-logs-message-settings.component.spec.ts
  gravitee-apim-console-webui/src/management/api/api-traffic-v4/runtime-logs-settings/runtime-logs-message-settings/api-runtime-logs-message-settings.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/PortalConfigEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/settings/PortalSettingsEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ConfigServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ConfigServiceTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11568 chore: bump ui-particles
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: ready_to_test

#11593 chore(deps): bump gravitee-common to 4.7.0
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11592 chore: bump nginx base image for 1.27.5
  gravitee-apim-console-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/Dockerfile
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11577 Dashboard analytics error - the given id must not be null
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/environment/EnvironmentAnalyticsResource.java
Labels: apply-on-master

#11545 fix: Application search does not work if search term pattern matches _id pattern
  gravitee-apim-console-webui/src/services-ngx/application.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/application.service.ts
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApplicationRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/test/java/io/gravitee/repository/jdbc/management/JdbcApplicationRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepositoryImplTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/ApplicationRepositoryTest.java
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11576 fix(api): Some IdPs do not support the optional application_type parameter in DCR
  docker/quick-setup/keycloak/docker-compose.yml
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/application/registration/ClientRegistrationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/configuration/application/registration/client/DynamicClientRegistrationProviderClient.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ClientRegistrationService_RegisterTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11621 feat: replace the in-product docs with a link to the user guide
  gravitee-apim-console-webui/src/entities/Constants.ts
  gravitee-apim-console-webui/src/index.ts
  gravitee-apim-console-webui/src/management/integrations/create-integration/create-integration.component.html
  gravitee-apim-console-webui/src/management/integrations/create-integration/create-integration.component.spec.ts
  gravitee-apim-console-webui/src/management/integrations/create-integration/create-integration.component.ts
  gravitee-apim-console-webui/src/management/integrations/integration-agent/integration-agent.component.html
  gravitee-apim-console-webui/src/management/integrations/integration-agent/integration-agent.component.scss
  gravitee-apim-console-webui/src/management/integrations/integration-agent/integration-agent.component.spec.ts
  gravitee-apim-console-webui/src/management/integrations/integration-agent/integration-agent.component.ts
  gravitee-apim-console-webui/src/management/integrations/integration-provider.service.spec.ts
  gravitee-apim-console-webui/src/management/integrations/integration-provider.service.ts
  gravitee-apim-console-webui/src/management/integrations/integrations.model.ts
  gravitee-apim-console-webui/src/shared/testing/gio-testing.module.ts
Labels: apply-on-4-7-x

#11624 fix: V4 emulation engine and description on rollback
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/RollbackApiEntity.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/use_case/RollbackApiUseCase.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/RollbackApiUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_RollbackTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11317 ci(rpm): Sign RPM with Gravitee PGP key
  .circleci/ci/README.md
  .circleci/ci/src/config.ts
  .circleci/ci/src/jobs/frontend/job-console-webui-build.ts
  .circleci/ci/src/jobs/frontend/job-portal-webui-build.ts
  .circleci/ci/src/jobs/job-publish-rpm-packages.ts
  .circleci/ci/src/pipelines/config-factory.ts
  .circleci/ci/src/pipelines/pipeline-build-docker-images.ts
  .circleci/ci/src/pipelines/pipeline-build-rpm.ts
  .circleci/ci/src/pipelines/pipeline.ts
  .circleci/ci/src/pipelines/tests/pipeline-build-docker-images.spec.ts
  .circleci/ci/src/pipelines/tests/pipeline-build-rpm.spec.ts
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run-as-latest.yml
  .circleci/ci/src/pipelines/tests/resources/build-docker-images/build-docker-images-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm/build-rpm-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm/build-rpm-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm/build-rpm-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/build-rpm/build-rpm-release-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/workflows/index.ts
  .circleci/ci/src/workflows/workflow-build-docker-images.ts
  .circleci/ci/src/workflows/workflow-build-rpm.ts
  .circleci/config.yml
  release/package.json
  release/steps/3-docker.mjs
  release/steps/4-rpms.mjs
  release/steps/5-helm-chart.mjs
  release/steps/6-generate_release_notes.mjs
  release/steps/7-nexus_sync.mjs
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#11622 fix: Non admin user can see other applications when searching by name
  gravitee-apim-console-webui/src/services-ngx/application.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/application.service.ts
  gravitee-apim-e2e/README.md
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/search/ApplicationCriteria.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApplicationRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/test/java/io/gravitee/repository/jdbc/management/JdbcApplicationRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepositoryImpl.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/test/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepositoryImplTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/ApplicationRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/application-tests/applications.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationsResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/application/ApplicationQuery.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApplicationServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_FindByIdsAndStatusTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_FindByIdsTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_FindByOrganizationTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_FindByUserTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationService_FindIdsByUserTest.java
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11654 fix: 502 errors when keepalive activated with v4 emulation engine
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/adapter/invoker/FlowableProxyResponse.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/adapter/invoker/FlowableProxyResponseTest.java
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11616 chore(deps): bump gravitee-reporter-api to 1.32.1
  gravitee-apim-gateway/gravitee-apim-gateway-policy/src/test/java/io/gravitee/gateway/reactive/policy/adapter/context/MetricsAdapterTest.java
  gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/test/java/io/gravitee/gateway/reactive/reactor/processor/NotFoundProcessorChainFactoryTest.java
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/messages/logging/MetricsIntegrationTest.java
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11668 fix: Correct the ApplicationServiceImplTest.buildSearchCriteria() method
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApplicationServiceImplTest.java
Labels: apply-on-4-5-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x
