Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-10, with the labels that each got.

#13517 fix: add cause metrics to v4 5xx error
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/diagnostic/DiagnosticReportHelper.java
  gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-http-proxy/src/main/java/io/gravitee/plugin/endpoint/http/proxy/HttpProxyEndpointConnector.java
Labels: apply-on-master, run-e2e-tests

#13529 feat: add snackbar notifications for feedback submission in Newt AI service
  gravitee-apim-console-webui/src/services-ngx/newtai.service.spec.ts
  gravitee-apim-console-webui/src/services-ngx/newtai.service.ts
Labels: apply-on-4-9-x

#13539 chore(deps): update gravitee-entrypoint-webhook.version to 5.0.1
  gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/messages/webhook/WebhookTestingActions.java
  pom.xml
Labels: apply-on-master

#13468 fix: delete handler test and missed delete
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/ClusterRepository.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/PortalPageContextRepository.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/api/PortalPageRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcClusterRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcPortalPageContextRepository.java
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcPortalPageRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoClusterRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoPortalPageContextRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoPortalPageRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/clusters/ClusterMongoRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/portalpage/PortalPageMongoRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/portalpagecontext/PortalPageContextMongoRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/clusters/ClustersEnvironmentIdIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/clusters/OrganizationIdIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/portalpage/EnvironmentIdIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/portalpagecontexts/EnvironmentIdIndexUpgrader.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/ClusterRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/PortalPageContextRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/PortalPageRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/portalpage-tests/portalPages.json
  gravitee-apim-repository/gravitee-apim-repository-test/src/test/resources/data/portalpagecontext-tests/portalPageContexts.json
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteEnvironmentCommandHandler.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteOrganizationCommandHandler.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteCommandHandlerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteEnvironmentCommandHandlerTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteOrganizationCommandHandlerTest.java
Labels: apply-on-4-9-x

#13556 fix: update policies quota, rate limit & spike arrest
  pom.xml
Labels: apply-on-master

#13569 chore: bump gravitee-reporter-tcp
  pom.xml
Labels: apply-on-4-7-x

#13570 Slack Enquiry - Viewing Kafka messages/logs causes exception in UI
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/log/adapter/message/SearchMessageLogResponseAdapter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/log/adapter/message/SearchMessageLogResponseAdapterTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-9-x

#13589 APIM 11374 and 11378 navigation fix
  gravitee-apim-portal-webui-next/src/app/catalog/tabs-view/tabs-view.component.spec.ts
  gravitee-apim-portal-webui-next/src/app/catalog/tabs-view/tabs-view.component.ts
Labels: apply-on-master

#13491 fix: publish theme in portal
  gravitee-apim-console-webui/src/portal/theme/portal-theme.component.html
  gravitee-apim-console-webui/src/portal/theme/portal-theme.component.spec.ts
  gravitee-apim-console-webui/src/portal/theme/portal-theme.component.ts
  gravitee-apim-console-webui/src/portal/theme/portal-theme.harness.ts
Labels: apply-on-master

#13597 fix: allow custom API keys up to 128 characters in UI and backend
  gravitee-apim-console-webui/src/management/api/subscriptions/components/api-key-validation/api-key-validation.component.html
  gravitee-apim-console-webui/src/management/api/subscriptions/components/api-key-validation/api-key-validation.component.spec.ts
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_29/00_increase_key_length.yml
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/validator/CustomApiKey.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/test/java/io/gravitee/rest/api/validator/CustomApiKeyTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x, apply-on-4-8-x, apply-on-4-9-x

#13528 APIM 11329 fix advanced css section
  gravitee-apim-console-webui/src/portal/theme/portal-theme.component.html
  gravitee-apim-console-webui/src/portal/theme/portal-theme.component.scss
Labels: apply-on-master

#13639 fix: notification settings are showing error in applications
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PortalNotificationConfigServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/PortalNotificationConfigService_FindByIdTest.java
Labels: apply-on-master, apply-on-4-9-x
