Repository gravitee-io/gravitee-api-management, pull requests merged in 2025-03, with the labels that each got.

#10852 fix: shared policy group audit errors
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/Audit.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#10878 fix: allow document view with read permission
  gravitee-apim-console-webui/src/management/api/apis-routing.module.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#10894 chore: fix delombok plugin with java 21
  gravitee-apim-definition/gravitee-apim-definition-model/pom.xml
  pom.xml
Labels: apply-on-master

#10914 ci: fix package bundle
  .circleci/ci/src/jobs/job-package-bundle.ts
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-alpha.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-latest.yml
  .circleci/ci/src/pipelines/tests/resources/full-release/release-4-2-0-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-prerelease-no-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-dry-run.yml
  .circleci/ci/src/pipelines/tests/resources/package-bundle/package-bundle-release-no-dry-run.yml
  .circleci/ci/src/workflows/workflow-package-bundle.ts
  release/ci-steps/package-bundles.mjs
Labels: apply-on-master

#10918 fix: portal Dockerfile-from-download
  gravitee-apim-portal-webui/docker/Dockerfile-from-download
Labels: apply-on-master

#10874 fix: remove SSE, wesocket & webhook or response time over time widget
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/analytics/AnalyticsElasticsearchRepository.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchResponseStatusOverTimeAdapter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/analytics/AnalyticsElasticsearchRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/SearchResponseStatusOverTimeAdapterTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/resources/freemarker-v4-analytics/v4-metrics.ftl
Labels: apply-on-4-7-x

#10893 Error for v4 api logs when analytics is disabled
  gravitee-apim-console-webui/src/management/home/home-overview/home-overview.component.ts
  gravitee-apim-repository/gravitee-apim-repository-noop/src/main/java/io/gravitee/repository/noop/NoOpAnalyticsRepositoryConfiguration.java
  gravitee-apim-repository/gravitee-apim-repository-noop/src/main/java/io/gravitee/repository/noop/log/v4/NoOpAnalyticsRepository.java
  gravitee-apim-repository/gravitee-apim-repository-noop/src/test/java/io/gravitee/repository/noop/log/v4/NoOpAnalyticsRepositoryTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#10923 fix: hide associations from groups for unauthorized users
  gravitee-apim-console-webui/src/management/settings/groups/group/group.html
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#10972 fix: hide associations from groups for unauthorized users
  gravitee-apim-console-webui/src/management/settings/groups/group/group.html
Labels: apply-on-master

#10872 fix: add script to configure IPv4-only Nginx setup and update Dockerfile
  gravitee-apim-console-webui/docker/Dockerfile
  gravitee-apim-console-webui/docker/Dockerfile-from-download
  gravitee-apim-console-webui/docker/config/check_ip_config.sh
  gravitee-apim-console-webui/docker/config/default.no-ipv6.conf
  gravitee-apim-portal-webui/docker/Dockerfile
  gravitee-apim-portal-webui/docker/Dockerfile-from-download
  gravitee-apim-portal-webui/docker/config/check_ip_config.sh
  gravitee-apim-portal-webui/docker/config/default.no-ipv6.conf
Labels: apply-on-master, apply-on-4-7-x

#10958 fix: remove SSE, websocket & webhook frpm analytics response time
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/ResponseTimeRangeQueryAdapter.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/analytics/AnalyticsElasticsearchRepositoryTest.java
  gravitee-apim-repository/gravitee-apim-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/v4/analytics/adapter/ResponseTimeRangeQueryAdapterTest.java
Labels: apply-on-4-7-x

#10993 fix: do not use absolute link on console and portal assets
  gravitee-apim-console-webui/src/auth/login/login.component.html
  gravitee-apim-console-webui/src/auth/reset-password/reset-password.component.html
  gravitee-apim-console-webui/src/auth/sign-up-confirm/sign-up-confirm.component.html
  gravitee-apim-console-webui/src/auth/sign-up/sign-up.component.html
  gravitee-apim-console-webui/src/management/api/general-info/api-general-info-promote-dialog/api-general-info-promote-dialog.component.html
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#10925 fix(portal): wrap long strings in Table of Contents to prevent floating
  gravitee-apim-portal-webui/src/app/components/gv-page-markdown/gv-page-markdown.component.css
Labels: apply-on-4-5-x, apply-on-master, ready_to_test, apply-on-4-4-x, apply-on-4-6-x

#10779 fix: instance of policies not properly released
  gravitee-apim-gateway/gravitee-apim-gateway-policy/src/main/java/io/gravitee/gateway/reactive/policy/DefaultPolicyFactory.java
  gravitee-apim-gateway/gravitee-apim-gateway-policy/src/test/java/io/gravitee/gateway/reactive/policy/DefaultPolicyFactoryTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#10888 chore: bump version of jwt policy to 6.1.0
  pom.xml
Labels: apply-on-master, apply-on-4-7-x

#10933 chore(deps): bump Regex Threat Protection to 1.6.0
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11029 fix: handle missing userinfo attributes for IDP condition evaluation
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/UserServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/UserServiceTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-6-x, apply-on-4-7-x

#11052 chore: bump mock policy
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x

#11053 chore(console): bump ui-particles
  gravitee-apim-console-webui/package.json
  gravitee-apim-console-webui/yarn.lock
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11061 fix: complete current templateContext with subscriptionVariable inste…
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/DefaultExecutionContext.java
  gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/context/HttpExecutionContextInternal.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/context/SubscriptionTemplateVariableProvider.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/processor/subscription/SubscriptionProcessor.java
  gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/reactive/handlers/api/processor/subscription/SubscriptionProcessorTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x

#11101 fix: documentation tab for read only users
  gravitee-apim-console-webui/src/management/api/apis-routing.module.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11100 Display the scoring error in first hour after it occurs
  gravitee-apim-console-webui/src/management/api/scoring/api-scoring.component.ts
Labels: apply-on-master

#11110 Bump kafka acl policy
  pom.xml
Labels: apply-on-master, apply-on-4-7-x

#11111 fix(new portal): display documentation without breaking words
  gravitee-apim-portal-webui-next/src/components/page/page-markdown/page-markdown.component.scss
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11125 fix: bump gravitee-node and update helm values
  helm/tests/api/deployment_federation_test.yaml
  helm/values.yaml
  pom.xml
Labels: apply-on-master, apply-on-4-7-x

#11128 chore(deps): bump JWT policy to 4.2.1
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11129 chore(deps): bump JSON validation to 2.0.3
  pom.xml
Labels: apply-on-master, apply-on-4-7-x

#11136 chore: bump reactor kafka - 4.7
  pom.xml
Labels: apply-on-master

#10959 fix: improve search performance by removing leading default wildcard
  gravitee-apim-console-webui/src/components/logs/logs-filters.controller.ts
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11112 fix: display user column in logs
  gravitee-apim-console-webui/src/management/api/analytics/logs/analytics-logs.controller.ajs.ts
Labels: apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11161 fix: missing updateAt in async jobs
  gravitee-apim-console-webui/src/management/api/scoring/api-scoring.component.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/resources/openapi/openapi-apis.yaml
Labels: apply-on-master

#11185 fix(e2e): adapt error message for log not found
  gravitee-apim-e2e/api-test/src/portal/mapi-v1/portal-business-error-applications.spec.ts
Labels: apply-on-master

#11171 fix: ignore unknown access control groups during import
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImplTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorService_CreateWithDefinitionTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiDuplicatorService_UpdateWithDefinitionTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/resources/io/gravitee/rest/api/management/service/import/import-api.pages.with-access-controls.json
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11195 fix(console): do not edit a closed subscription
  gravitee-apim-console-webui/src/components/subscription-edit-push-config/subscription-edit-push-config.component.html
  gravitee-apim-console-webui/src/components/subscription-edit-push-config/subscription-edit-push-config.component.spec.ts
  gravitee-apim-console-webui/src/components/subscription-edit-push-config/subscription-edit-push-config.component.ts
  gravitee-apim-console-webui/src/components/subscription-edit-push-config/subscription-edit-push-config.harness.ts
  gravitee-apim-console-webui/src/management/api/subscriptions/edit/api-subscription-edit.component.html
  gravitee-apim-console-webui/src/management/api/subscriptions/edit/api-subscription-edit.component.spec.ts
  gravitee-apim-console-webui/src/management/application/details/subscriptions/subscription/application-subscription.component.html
  gravitee-apim-console-webui/src/management/application/details/subscriptions/subscription/application-subscription.component.spec.ts
Labels: apply-on-master

#11199 fix: add missing mapping between repository and entity
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/SubscriptionServiceImpl.java
Labels: apply-on-master

#11183 fix: remove group from application after deletion
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/Api.java
  gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/management/model/Application.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/GroupServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/GroupService_DeleteTest.java
Labels: apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11209 test: fix breaking integration test for gko
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiDuplicatorServiceImpl.java
Labels: apply-on-4-5-x, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x

#11222 chore(deps): bump common to 3.4.2
  pom.xml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x

#11223 fix(portal-next): apply word break to all documentation
  gravitee-apim-portal-webui-next/src/components/page/page-async-api/page-async-api.component.scss
  gravitee-apim-portal-webui-next/src/components/page/page-async-api/page-async-api.component.ts
  gravitee-apim-portal-webui-next/src/components/page/page-markdown/page-markdown.component.scss
  gravitee-apim-portal-webui-next/src/components/page/page.component.scss
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-4-x, apply-on-4-6-x

#11242 feat(console): text update for api rulesets import
  gravitee-apim-console-webui/src/management/api-score/rulesets/api-score-rulesets.component.html
  gravitee-apim-console-webui/src/management/api-score/rulesets/import/import-api-score-ruleset.component.html
  gravitee-apim-console-webui/src/management/api-score/rulesets/import/import-api-score-ruleset.component.ts
Labels: apply-on-4-7-x

#11254 docs: improve explanation of KG configuration [skip ci]
  gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
  helm/values.yaml
Labels: apply-on-master, apply-on-4-7-x

#11259 fix: bump kg reactor
  pom.xml
Labels: apply-on-master

#11276 chore(deps): bump gravitee-reactor-message to 6.0.1
  pom.xml
Labels: apply-on-master

#11282 fix(console): health-check list
  gravitee-apim-console-webui/src/management/home/home-api-health-check/home-api-health-check.component.ts
  gravitee-apim-console-webui/src/management/home/home-overview/home-overview.component.ts
Labels: apply-on-4-7-x

#11289 Bump kafka-acl
  pom.xml
Labels: apply-on-master, apply-on-4-7-x

#11302 Fix race condition causing missing subscription keys by synchronizing key table update.
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/subscription/domain_service/AcceptSubscriptionDomainService.java
Labels: apply-on-4-5-x, apply-on-4-4-x

#11314 fix: bump policy-jwt
  pom.xml
Labels: apply-on-4-6-x, apply-on-4-7-x

#11318 fix: init retry on fail with null values
  gravitee-apim-portal-webui-next/src/components/subscription/webhook/consumer-configuration-retry/consumer-configuration-retry.component.ts
Labels: apply-on-master

#11320 fix(mapi-v2): add plan validation to plan updates
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiPlansResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/plan/model/PlanUpdates.java
Labels: apply-on-master, apply-on-4-7-x

#11323 feat: allow to see alerts and trigg notification for V4 APIs
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/PlanAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiService_FindByIdAsMapTest.java
Labels: apply-on-master

#11327 filter current user groups
  gravitee-apim-console-webui/src/user/my-accout/user.controller.ts
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/organization/CurrentUserResource.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/CurrentUserResourceTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/portal-openapi.yaml
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-6-x, apply-on-4-7-x

#11326 fix: export missing flow
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/mapper/PlanMapper.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiResource_ExportApiDefinitionTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/model/import_definition/GraviteeDefinition.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/model/import_definition/PlanDescriptor.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/adapter/GraviteeDefinitionAdapter.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/infra/domain_service/api/ApiExportDomainServiceImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/ExportApiUseCaseTest.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/infra/domain_service/api/ApiExportDomainServiceImplTest.java
Labels: apply-on-master

#11174 fix: Fix unauthorized API key exception when using the shared API key…
  gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
  gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/key/ApiKeyMongoRepositoryImpl.java
  gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/ApiKeyServiceTest.java
Labels: apply-on-4-5-x, apply-on-master, apply-on-4-3-x, apply-on-4-4-x, apply-on-4-6-x, apply-on-4-7-x
